### PR TITLE
[json-rpc]: remove the json field metadata if the value is null

### PR DESCRIPTION
**Pull request by xli**
## Motivation

1. To keep consistent behavior when output null value field.
2. Current Rust jsonrpc types generated from protobuf definition does not accept field value == null case for a string type; this change avoids the problem for the client.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Unit Test

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Review by dmitri-perelman — APPROVED** [review]

**Comment by bmwill** [comment]
While this does fix the issue that was seen, the real root cause is that the structs generated from the proto file are incorrect and unable to handle optional values.

**Review by bmwill — APPROVED** [review]
This highlights a big problem with the protobuf generated structs, you can't tell the difference between when a field isn't set vs the empty string. The ideal solution for clients would be to migrate to the new client which doesn't use the protobuf structs.

**Pull request merged**
