### PR TITLE
[x] move to the latest nextest

### PR DESCRIPTION
**Pull request by sunshowers**
This version comes with a number of fixes and config file support -- we
can run tests in CI with the CI profile now.

### CODE REVIEW

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M structopt 0.3.25 (direct third-party, crates.io)
    * version upgraded from 0.3.21
    * (unchanged features: default)
  M aho-corasick 0.7.18 (transitive third-party, crates.io)
    * version upgraded from 0.7.15
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)

host packages:
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: [none])
  M structopt-derive 0.4.18 (transitive third-party, crates.io)
    * version upgraded from 0.4.14
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M structopt 0.3.25 (direct third-party, crates.io)
    * version upgraded from 0.3.21
    * (unchanged features: default)
  M aho-corasick 0.7.18 (transitive third-party, crates.io)
    * version upgraded from 0.7.15
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)

host packages:
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M structopt-derive 0.4.18 (transitive third-party, crates.io)
    * version upgraded from 0.4.14
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M structopt 0.3.25 (direct third-party, crates.io)
    * version upgraded from 0.3.21
    * (unchanged features: default)
  M aho-corasick 0.7.18 (transitive third-party, crates.io)
    * version upgraded from 0.7.15
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)

host packages:
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: [none])
  M structopt-derive 0.4.18 (transitive third-party, crates.io)
    * version upgraded from 0.4.14
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M structopt 0.3.25 (direct third-party, crates.io)
    * version upgraded from 0.3.21
    * (unchanged features: default)
  M aho-corasick 0.7.18 (transitive third-party, crates.io)
    * version upgraded from 0.7.15
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)

host packages:
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M structopt-derive 0.4.18 (transitive third-party, crates.io)
    * version upgraded from 0.4.14
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M structopt 0.3.25 (direct third-party, crates.io)
    * version upgraded from 0.3.21
    * (unchanged features: default)
  M aho-corasick 0.7.18 (transitive third-party, crates.io)
    * version upgraded from 0.7.15
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)

host packages:
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: [none])
  M structopt-derive 0.4.18 (transitive third-party, crates.io)
    * version upgraded from 0.4.14
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A itoa 1.0.1 (transitive third-party, crates.io) (other versions: 0.4.7)
    * features: [none]
  M serde_json 1.0.73 (direct third-party, crates.io)
    * version upgraded from 1.0.68
    * (unchanged features: default, std)
  M structopt 0.3.25 (direct third-party, crates.io)
    * version upgraded from 0.3.21
    * (unchanged features: default)
  M aho-corasick 0.7.18 (transitive third-party, crates.io)
    * version upgraded from 0.7.15
    * (unchanged features: default, std)
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M memoffset 0.6.5 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: default)

host packages:
  M libc 0.2.112 (transitive third-party, crates.io)
    * version upgraded from 0.2.99
    * (unchanged features: default, std)
  M structopt-derive 0.4.18 (transitive third-party, crates.io)
    * version upgraded from 0.4.14
    * (unchanged features: [none])
```

**Review by bmwill — DISMISSED** [review]
@sunshowers How close are we from being able to drop the custom bash retry logic we have for the e2e tests and just use nextest directly?

**Comment by sunshowers** [comment]
@bmwill Really close! I've added in support for partitioning tests as well, my hope was to move everything over to nextest before I went on leave (also so that we get e2e tests in allure)

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Pull request closed without merging**
