### PR TITLE
[dependency] upgrading anyhow -> 1.0.52

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation

to overcome this when building the release target:
···
error[E0554]: `#![feature]` may not be used on the stable release channel
···

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
Y
## Test Plan
existing coverage

### CODE REVIEW

**Comment by libra-action** [comment]
## Dependency update review
### anyhow updated: 1.0.40 --> 1.0.52

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:x:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>31</td></tr><tr><td>total rust files changed</td><td>20</td></tr><tr><td>total loc change</td><td>2,051</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` tests/test_macros.rs `
   * ` src/chain.rs `
   * ` Cargo.toml `
   * ` .cargo_vcs_info.json `
   * ` src/ptr.rs `
   * ` tests/test_downcast.rs `
   * ` src/ensure.rs `
   * ` tests/test_context.rs `
   * ` Cargo.toml.orig `
   * ` build.rs `
   * ` .github/workflows/ci.yml `
   * ` tests/test_boxed.rs `
   * ` tests/test_ensure.rs `
   * ` tests/ui/empty-ensure.rs `
   * ` src/backtrace.rs `
   * ` tests/drop/mod.rs `
   * ` src/kind.rs `
   * ` src/error.rs `
   * ` src/lib.rs `
   * ` tests/test_convert.rs `
   * ` src/macros.rs `
   * ` tests/ui/wrong-interpolation.rs `
   * ` tests/test_chain.rs `
   * ` tests/ui/empty-ensure.stderr `
   * ` README.md `
   * ` tests/ui/no-impl.stderr `
   * ` tests/ui/chained-comparison.rs `
   * ` tests/ui/wrong-interpolation.stderr `
   * ` rust-toolchain.toml `
   * ` tests/ui/chained-comparison.stderr `
   * ` tests/ui/temporary-value.stderr `
</details><details>
	<summary>Click to show modified build scripts</summary><br>

   * ` build.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/backtrace.rs `
   * ` src/ensure.rs `
   * ` src/error.rs `
   * ` src/ptr.rs `
</details>
</details>

**Review by aching — APPROVED** [review]
LGTM

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M anyhow 1.0.52 (direct third-party, crates.io)
    * version upgraded from 1.0.40
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M anyhow 1.0.52 (direct third-party, crates.io)
    * version upgraded from 1.0.40
    * (unchanged features: default, std)

host packages:
  M anyhow 1.0.52 (transitive third-party, crates.io)
    * version upgraded from 1.0.40
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M anyhow 1.0.52 (direct third-party, crates.io)
    * version upgraded from 1.0.40
    * (unchanged features: default, std)

host packages:
  M anyhow 1.0.52 (transitive third-party, crates.io)
    * version upgraded from 1.0.40
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
## Dependency update review
### anyhow updated: 1.0.40 --> 1.0.52

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:x:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>31</td></tr><tr><td>total rust files changed</td><td>20</td></tr><tr><td>total loc change</td><td>2,051</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` build.rs `
   * ` rust-toolchain.toml `
   * ` tests/test_convert.rs `
   * ` tests/ui/wrong-interpolation.stderr `
   * ` tests/ui/no-impl.stderr `
   * ` tests/test_ensure.rs `
   * ` Cargo.toml `
   * ` src/backtrace.rs `
   * ` tests/test_downcast.rs `
   * ` .cargo_vcs_info.json `
   * ` README.md `
   * ` src/chain.rs `
   * ` tests/test_context.rs `
   * ` tests/test_boxed.rs `
   * ` Cargo.toml.orig `
   * ` tests/ui/chained-comparison.stderr `
   * ` src/ptr.rs `
   * ` tests/test_chain.rs `
   * ` src/lib.rs `
   * ` tests/ui/chained-comparison.rs `
   * ` .github/workflows/ci.yml `
   * ` src/ensure.rs `
   * ` src/error.rs `
   * ` src/macros.rs `
   * ` src/kind.rs `
   * ` tests/test_macros.rs `
   * ` tests/ui/temporary-value.stderr `
   * ` tests/drop/mod.rs `
   * ` tests/ui/empty-ensure.stderr `
   * ` tests/ui/wrong-interpolation.rs `
   * ` tests/ui/empty-ensure.rs `
</details><details>
	<summary>Click to show modified build scripts</summary><br>

   * ` build.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/backtrace.rs `
   * ` src/ensure.rs `
   * ` src/error.rs `
   * ` src/ptr.rs `
</details>
</details>

**Pull request merged**
