### PR TITLE
[move-prover] Cleanup benchmarks and add a new benchmark for opaque/ignore opaque

### PR DESCRIPTION
**Pull request by wrwg**
This cleans up the lab including historical data removing all use of jupyterbook and instead generated SVG files included into markdown.

It also adds a new benchmark for comparing opaque vs non-opaque verification, leveraging the new flags for ignoring the opaque pragma. [As expected, verification ignoring opaque is significantly slower](https://github.com/wrwg/diem/blob/bench/language/move-prover/lab/data/opaque/README.md). 

## Motivation

Benchmarking

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

NA

## Related PRs

NA

### CODE REVIEW

**Comment by mengxu-fb** [comment]
Now I am nervous... I am not expecting it to be faster than the opaque/default version...

**Comment by wrwg** [comment]
> Now I am nervous... I am not expecting it to be faster than the opaque/default version...

There is something wrong with the benchmarking, so you can relax. Manual results look as expected:

```
(bench) ~/gh/diem/language/diem-framework/modules: mvp DiemAccount.move
    Finished dev [unoptimized + debuginfo] target(s) in 1.33s
     Running `/home/wrwg/gh/diem/target/debug/move-prover DiemAccount.move`
[INFO] translating module DiemAccount
[INFO] running solver
[INFO] 3.812s build, 4.680s trafo, 2.031s gen, 6.102s verify
(bench) ~/gh/diem/language/diem-framework/modules: mvp --ignore-pragma-opaque-when-possible DiemAccount.move
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `/home/wrwg/gh/diem/target/debug/move-prover --ignore-pragma-opaque-when-possible DiemAccount.move`
[INFO] translating module DiemAccount
[INFO] running solver
[INFO] 3.699s build, 4.321s trafo, 1.807s gen, 24.338s verify
```

**Comment by wrwg** [comment]
> > Now I am nervous... I am not expecting it to be faster than the opaque/default version...
> 
> There is something wrong with the benchmarking, so you can relax. Manual results look as expected:
> 
> ```
> (bench) ~/gh/diem/language/diem-framework/modules: mvp DiemAccount.move
>     Finished dev [unoptimized + debuginfo] target(s) in 1.33s
>      Running `/home/wrwg/gh/diem/target/debug/move-prover DiemAccount.move`
> [INFO] translating module DiemAccount
> [INFO] running solver
> [INFO] 3.812s build, 4.680s trafo, 2.031s gen, 6.102s verify
> (bench) ~/gh/diem/language/diem-framework/modules: mvp --ignore-pragma-opaque-when-possible DiemAccount.move
>     Finished dev [unoptimized + debuginfo] target(s) in 0.48s
>      Running `/home/wrwg/gh/diem/target/debug/move-prover --ignore-pragma-opaque-when-possible DiemAccount.move`
> [INFO] translating module DiemAccount
> [INFO] running solver
> [INFO] 3.699s build, 4.321s trafo, 1.807s gen, 24.338s verify
> ```

The problem has been identified and fixed. The benchmarking code did not use the new function `un_model_builder_with options`. Now the result linked to from the PR description looks more reasonable; we are looking at a factor of 4 in worst case scenarios.

**Comment by mengxu-fb** [comment]
Thank you for the quick update! Now the data looks much more reasonable.

4x slower is actually not bad, especially considering that this includes the time of verifying the specs for private functions as well which, in many cases, is not necessary if the spec conditions are removed as well.

**Review by mengxu-fb — DISMISSED** [review]

**Pull request merged**
