### PR TITLE
Merge developers.diem.com infra and content into diem codebase

### PR DESCRIPTION
**Pull request by JoelMarcey**
## Motivation

Just like we did with developers.libra.org, have developers.diem.com be integrated with the Diem code for consolidation and having docs with code.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Local Docusaurus testing.
Netlify testing with the PR

## Related PRs

N/A

### CODE REVIEW

**Review by bmwill — APPROVED** [review]
Land it when you're ready!

**Comment by JoelMarcey** [comment]
cc @sausagee

**Pull request closed without merging**
