### PR TITLE
Log JSONRPC calls as info

### PR DESCRIPTION
**Pull request by CapCap**
## Motivation
 By logging the JSONRPC calls, we can perform metrics in aggregate across user agents (specifically SDK versions)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
yes

## Test Plan
logging change

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.
## If targeting a release branch, please fill the below out as well

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M byteorder 1.4.3 (transitive third-party, crates.io)
    * version upgraded from 1.4.2
    * (unchanged features: i128)
  M libc 0.2.89 (transitive third-party, crates.io)
    * version upgraded from 0.2.88
    * (unchanged features: default, std)

host packages:
  M syn 1.0.64 (direct third-party, crates.io)
    * version upgraded from 1.0.62
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-stdlib 0.1.0 (workspace, path 'language/move-stdlib')
    * features: [none]
  M byteorder 1.4.3 (direct third-party, crates.io)
    * version upgraded from 1.4.2
    * (unchanged features: default, i128, std)
  M serde-generate 0.19.1 (direct third-party, crates.io)
    * version upgraded from 0.19.0
    * (unchanged features: [none])
  M libc 0.2.89 (transitive third-party, crates.io)
    * version upgraded from 0.2.88
    * (unchanged features: align, default, std)
  M regex-syntax 0.6.23 (transitive third-party, crates.io)
    * version upgraded from 0.6.22
    * (unchanged features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)

host packages:
  M syn 1.0.64 (direct third-party, crates.io)
    * version upgraded from 1.0.62
    * (unchanged features: clone-impls, default, derive, extra-traits, fold, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M libc 0.2.89 (transitive third-party, crates.io)
    * version upgraded from 0.2.88
    * (unchanged features: default, std)
  M regex-syntax 0.6.23 (transitive third-party, crates.io)
    * version upgraded from 0.6.22
    * (unchanged features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M byteorder 1.4.3 (transitive third-party, crates.io)
    * version upgraded from 1.4.2
    * (unchanged features: i128)
  M libc 0.2.89 (transitive third-party, crates.io)
    * version upgraded from 0.2.88
    * (unchanged features: align, default, std)

host packages:
  M syn 1.0.64 (direct third-party, crates.io)
    * version upgraded from 1.0.62
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
```

**Review by bmwill — COMMENTED** [review]
IIRC this used to be at info level but we downgraded it because it produced too high of a volume of logs maybe we can get @opsguy or @mgorven to comment on if we're ok with the higher load on the logging service this will cause.

**Comment by mgorven** [comment]
This will be very noisy, both for operators looking at pod logs and central log aggregation.

**Pull request closed without merging**
