### PR TITLE
[lbt] add missing checkout step in image lookup

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
Add the missing step to fetch past refs so that LBT can look up base_ref.

## Test Plan
Canary https://github.com/diem/diem/runs/2240245638?check_suite_focus=true

### CODE REVIEW

**Review by zihaoccc — APPROVED** [review]
thx for fixing this

**Review by zihaoccc — APPROVED** [review]

**Review by rexhoffman — APPROVED** [review]

**Pull request merged**
