### PR TITLE
[move-prover] Tech report: global invariants first take

### PR DESCRIPTION
**Pull request by wrwg**
This adds a draft section about global invariants in general, and the specific problem of genericity and monomorphization.

[PDF](https://github.com/wrwg/diem/blob/globalinv/language/move-prover/doc/report/main.pdf)

Writing this gave some interesting insights which might be relevant for the ongoing work on generic invariants. Specifically, the problem of monomorphization should be seen independently of that of invariant injection.

This does not yet tackle modular verification and suspension of invariants.

## Motivation

Tech report

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

NA

### CODE REVIEW

**Comment by mengxu-fb** [comment]
> Specifically, the problem of monomorphization should be seen independently of that of invariant injection.

Totally agreed on this! And right now this is seen in our implementation as well:
- invariant injection bounded within `global_invariant_instrumentation_v2.rs`
- monomorphization is bounded within `mono_analysis.rs`

In fact, monomorphization pass does not care whether a type quantifier comes from global invariant instrumentation or not. In an extreme case, if the user writes an in-line spec with an assertion like `assert forall t: type: property-of-t...`, the mono pass will happily monomorphize the `assert` expression as well.

**Comment by wrwg** [comment]
> In fact, monomorphization pass does not care whether a type quantifier comes from global invariant instrumentation or not. 

Well, in the way it is described in the paper, type quantifiers (really generic `invariant<T>` the only source) are eliminated at invariant instrumentation time, by just instantiating T when inserting the invariant. What monomorphization does is dealing with a `f<T>` which uses both `S<T>` and `S<u64>`, whether this comes from an invariant or the user has written it doesn't matter, covering the case `move_to<S<T>>(...); move_to<S<u64>>(..)`. Please check whether we are on the same page regards this.

**Comment by mengxu-fb** [comment]
Sorry that I misread the paper. I read 3.3.5 last night but did not go through 3.4.

I think there are two items (four sub-items) we need to consider and it is a matter of giving consistent names to them
1) specialize generic functions based on the memory checked by the expressions
  1.1) `f<T>` that modifies `S<T>` and a global invariant `I` checks on `S<u64>`
  1.2) Type dependent code (e.g., the `move_to<S<T>>(...); move_to<S<u64>>(..)` case).
         (BTW, we do have type dependent code in the `DesignatedDealer::publish_designated_dealer_credential`)

2) specialize generic expressions based on the memory touched by the function
  2.1) A generic invariant `I<T>` about `S<T>` is instrumented in a concrete function `f` that modifies `S<u64>`
  2.2) Ad-hoc, type quantified expressions in in-line spec (which is probably not going be useful though).

My original terminology is calling 1) `instantiation` and 2) `monomorphization` (hence, my comments above). The reason for the separation is mainly from an implementation point of view: broadly speaking, `instantiation` is specializing types in the `Bytecode` while `monomorphization` is specializing types in the `Exp`. The paper seems to have a different naming  for these items, which I could not completely map back to the above categories. This is likely because I haven't figured out everything clearly in my head too.

**Review by mengxu-fb — DISMISSED** [review]
/land

**Pull request merged**
