### PR TITLE
updating rand_core

### PR DESCRIPTION
**Pull request by mimoo**

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A rand_core 0.6.0 (direct third-party, crates.io)
    * features: [none]
  M rand_core 0.5.1 (transitive third-party, crates.io)
    * status changed from direct third-party
    * (unchanged features: alloc, getrandom, std)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A rand_core 0.6.0 (direct third-party, crates.io)
    * features: [none]
  M rand_core 0.5.1 (transitive third-party, crates.io)
    * status changed from direct third-party
    * (unchanged features: alloc, getrandom, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A rand_core 0.6.0 (direct third-party, crates.io) (other versions: 0.3.1, 0.4.2)
    * features: [none]
  M rand_core 0.5.1 (transitive third-party, crates.io) (other versions: 0.3.1, 0.4.2)
    * status changed from direct third-party
    * (unchanged features: alloc, getrandom, std)
```

**Review by jnaulty — APPROVED** [review]

**Comment by rexhoffman** [comment]
Nice thanks for digging in.

**Comment by mimoo** [comment]
seems like an unrelated error, rebasing + re-trying

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A rand_core 0.6.0 (direct third-party, crates.io)
    * features: [none]
  M rand_core 0.5.1 (transitive third-party, crates.io)
    * status changed from direct third-party
    * (unchanged features: alloc, getrandom, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A rand_core 0.6.0 (direct third-party, crates.io)
    * features: [none]
  M rand_core 0.5.1 (transitive third-party, crates.io)
    * status changed from direct third-party
    * (unchanged features: alloc, getrandom, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A rand_core 0.6.0 (direct third-party, crates.io) (other versions: 0.3.1, 0.4.2)
    * features: [none]
  M rand_core 0.5.1 (transitive third-party, crates.io) (other versions: 0.3.1, 0.4.2)
    * status changed from direct third-party
    * (unchanged features: alloc, getrandom, std)
```

**Pull request closed without merging**
