### PR TITLE
[language][diem-framework] fix DPN release tests

### PR DESCRIPTION
**Pull request by vgao1996**
In a recent refactoring, we renamed `diem-framework/DPN/releases/artifact/current/modules` to `sources`, which broke `tests::can_deserialize_and_verify_modules_from_all_versions`. This renames it back to modules to get the test fixed and make it consistent with the other artifacts.

### CODE REVIEW

**Review by sunmilee — DISMISSED** [review]

**Comment by bmwill** [comment]
Looks like there's some tooling that is creating the sources directory, causing the check that requires theres no dirty files after a test to fail.

**Comment by bmwill** [comment]
In the original PR https://github.com/diem/diem/pull/9246 there's also a ton of generated documentation with links that may still be out of date after this PR

**Comment by vgao1996** [comment]
> In the original PR #9246 there's also a ton of generated documentation with links that may still be out of date after this PR

The docs seem fine to me. I'll fix the other issue though. Thanks for pointing that out!

**Review by tzakian — DISMISSED** [review]

**Pull request closed without merging**
