### PR TITLE
[x] update guppy + move more code over to camino paths

### PR DESCRIPTION
**Pull request by sunshowers**

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Review by bmwill — APPROVED** [review]
/land

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Review by bmwill — DISMISSED** [review]
/land

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M itertools 0.10.1 (direct third-party, crates.io)
    * version upgraded from 0.10.0
    * (unchanged features: default, use_alloc, use_std)
  M serde 1.0.130 (direct third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.67 (direct third-party, crates.io)
    * version upgraded from 1.0.64
    * (unchanged features: default, std)
  M globset 0.4.8 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])

host packages:
  M serde_derive 1.0.130 (transitive third-party, crates.io)
    * version upgraded from 1.0.127
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Review by bmwill — APPROVED** [review]
/land

**Comment by libra-action** [comment]
`This PR contains dependency updates.
However, Depdive update review report exceeds max. characters allowed in a GitHub comment.
Please, run depdive locally or check actions.`

**Pull request merged**
