### PR TITLE
[scripts] fallback to default pkg manager and install more in forge

### PR DESCRIPTION
**Pull request by rustielin**
## Motivation

Give the `forge` image more tools, some of which are installed via the default package manager. Also make `docker/forge/build.sh` executable.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Build the image locally `docker/forge/build.sh` and observe that the `dev_setup.sh` step executes successfully. Run the image locally and `docker exec` into it and check manually that it has the following tools: `kubectl`, `helm`, `aws`, `git`

### CODE REVIEW

**Review by rexhoffman — COMMENTED** [review]
looks good.

**Comment by rustielin** [comment]
> looks good.

@rexhoffman did you mean to stamp..? 😄

**Review by zihaoccc — DISMISSED** [review]

**Review by rexhoffman — APPROVED** [review]
Indeed I did.

**Pull request closed without merging**
