### PR TITLE
[crypto][dependency-only] Update crypto dependencies

### PR DESCRIPTION
**Pull request by huitseeker**
Picks up Dalek 3.0.2 & fiat-crypto 0.1.6

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M curve25519-dalek 3.0.2 (direct third-party, external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat4#611127c2460937b61097caf867b7e518f4b78295')
    * version upgraded from 3.0.0
    * source changed from external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2'
    * (unchanged features: alloc, fiat-crypto, fiat_u64_backend, std)
  M ed25519-dalek 1.0.1 (direct third-party, external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat6#8ca0470c78f65c4f91b86e51cdc002675a41f573')
    * source changed from external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat5#88603ebf0196015e9b4106844f9f47ed6c01e951'
    * (unchanged features: fiat_u64_backend, rand, serde, serde_bytes, serde_crate, std)
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat5#266ea5a0c2b703a6fd75f47f24864413a17724f0')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6'
    * (unchanged features: fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M curve25519-dalek 3.0.2 (direct third-party, external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat4#611127c2460937b61097caf867b7e518f4b78295')
    * version upgraded from 3.0.0
    * source changed from external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2'
    * (unchanged features: alloc, fiat-crypto, fiat_u64_backend, std)
  M ed25519-dalek 1.0.1 (direct third-party, external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat6#8ca0470c78f65c4f91b86e51cdc002675a41f573')
    * source changed from external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat5#88603ebf0196015e9b4106844f9f47ed6c01e951'
    * (unchanged features: fiat_u64_backend, rand, serde, serde_bytes, serde_crate, std)
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat5#266ea5a0c2b703a6fd75f47f24864413a17724f0')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6'
    * (unchanged features: fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M curve25519-dalek 3.0.2 (direct third-party, external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat4#611127c2460937b61097caf867b7e518f4b78295')
    * version upgraded from 3.0.0
    * source changed from external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2'
    * (unchanged features: alloc, fiat-crypto, fiat_u64_backend, std)
  M ed25519-dalek 1.0.1 (direct third-party, external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat6#8ca0470c78f65c4f91b86e51cdc002675a41f573')
    * source changed from external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat5#88603ebf0196015e9b4106844f9f47ed6c01e951'
    * (unchanged features: fiat_u64_backend, rand, serde, serde_bytes, serde_crate, std)
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat5#266ea5a0c2b703a6fd75f47f24864413a17724f0')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6'
    * (unchanged features: fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M curve25519-dalek 3.0.2 (direct third-party, external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat4#611127c2460937b61097caf867b7e518f4b78295')
    * version upgraded from 3.0.0
    * source changed from external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2'
    * (unchanged features: alloc, fiat-crypto, fiat_u64_backend, std)
  M ed25519-dalek 1.0.1 (direct third-party, external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat6#8ca0470c78f65c4f91b86e51cdc002675a41f573')
    * source changed from external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat5#88603ebf0196015e9b4106844f9f47ed6c01e951'
    * (unchanged features: fiat_u64_backend, rand, serde, serde_bytes, serde_crate, std)
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat5#266ea5a0c2b703a6fd75f47f24864413a17724f0')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6'
    * (unchanged features: fiat_u64_backend, std)
```

**Review by rexhoffman — COMMENTED** [review]
This looks fine to me, @kchalkias?

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M curve25519-dalek 3.0.2 (direct third-party, external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat4#611127c2460937b61097caf867b7e518f4b78295')
    * version upgraded from 3.0.0
    * source changed from external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2'
    * (unchanged features: alloc, fiat-crypto, fiat_u64_backend, std)
  M ed25519-dalek 1.0.1 (direct third-party, external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat6#8ca0470c78f65c4f91b86e51cdc002675a41f573')
    * source changed from external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat5#88603ebf0196015e9b4106844f9f47ed6c01e951'
    * (unchanged features: fiat_u64_backend, rand, serde, serde_bytes, serde_crate, std)
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat5#266ea5a0c2b703a6fd75f47f24864413a17724f0')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6'
    * (unchanged features: fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M curve25519-dalek 3.0.2 (direct third-party, external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat4#611127c2460937b61097caf867b7e518f4b78295')
    * version upgraded from 3.0.0
    * source changed from external 'git+https://github.com/novifinancial/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2'
    * (unchanged features: alloc, fiat-crypto, fiat_u64_backend, std)
  M ed25519-dalek 1.0.1 (direct third-party, external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat6#8ca0470c78f65c4f91b86e51cdc002675a41f573')
    * source changed from external 'git+https://github.com/novifinancial/ed25519-dalek.git?branch=fiat5#88603ebf0196015e9b4106844f9f47ed6c01e951'
    * (unchanged features: fiat_u64_backend, rand, serde, serde_bytes, serde_crate, std)
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat5#266ea5a0c2b703a6fd75f47f24864413a17724f0')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6'
    * (unchanged features: fiat_u64_backend, std)
```

**Review by kchalkias — APPROVED** [review]
Yes, all versions in the 3 crates, have been reviewed and crosschecked.

**Pull request closed without merging**
