### PR TITLE
[language] rename 'vm' to 'move-binary-format'

### PR DESCRIPTION
**Pull request by vgao1996**
Crate `vm` got its name a long time ago. A lot has happened afterwards and the name `vm` is no longer an accurate description of the contents of the crate. It's also very confusing when you have both `vm` and a bunch of `move-vm` crates. This PR gets it renamed to `move-binary-format`, one of the names we reserved on crates.io.

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
```

**Comment by tnowacki** [comment]
Oh boy we are renaming things? Can we rename `diem-vm`? :D

**Comment by tnowacki** [comment]
Overall I'm cool with renaming this. Perhaps we should discuss it in the meeting today before landing

**Comment by bob-wilson** [comment]
> Oh boy we are renaming things? Can we rename `diem-vm`? :D

IMO, that one should be renamed to "move-adapter" and also move outside the language directory

**Comment by tnowacki** [comment]
It needs to be outside of the language crate eventually. diem-move-adapter is a bit more to my taste, albeit rather pedantic. I think regardless we are on the same page about the "adapter" naming convention

**Comment by vgao1996** [comment]
> move outside the language directory
Agreed

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
```

**Review by tnowacki — APPROVED** [review]

**Pull request merged**
