### PR TITLE
[genesis] do not bump sequence number for DiemRoot

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

In older versions of Diem, the genesis transaction was a signed transaction sent from the DiemRoot account. To reflect this, the genesis write set incremented the sequence number for DiemRoot so that the first transaction sent from this account would have sequence number 1.

Since then, genesis has been given its own transaction type with no sender address. Thus, we no longer need this sequence number bump.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Review by gregnazario — COMMENTED** [review]
I don't see any issues with this, what's the reasoning for this?  Is it just to clean up that it was 1 instead of 0?

**Review by gregnazario — APPROVED** [review]
/land

**Comment by zekun000** [comment]
/cancel

still some tests failing

**Review by wqfish — APPROVED** [review]

**Pull request merged**
