### PR TITLE
[benchmark] add cpu time measurement

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

use cpu-time instead of wall-time, hopefully get more stable measurement.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan

run bench

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Review by gregnazario — APPROVED** [review]
Looks fine to me unless there was something specific you were looking for.

Curious though, has this helped you see any significant difference / tell directly changes in performance so far?

**Comment by zekun000** [comment]
@gregnazario thanks for reviewing! this is intended to setup a stable baseline (hopefully) since the wall time measurement is not stable enough across multiple runs (~10% difference). I still see ~5% difference with cpu-time but still better.

**Pull request closed without merging**
