### PR TITLE
Update reset-cookie.js

### PR DESCRIPTION
**Pull request by louis3x0**
When the user click "Click to reset cookies" the button doesn't work and this fix it

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
https://stackoverflow.com/a/57644049

suggests

document.cookie = 'COOKIE_NAME=; Max-Age=0; path=/; domain=' + location.host;

which differs from yours on what to put for the domain. Leaving it to you and @JoelMarcey

**Comment by davidiw** [comment]
Thanks for the contribution by the way!

**Comment by JoelMarcey** [comment]
I think you can delete the cookie this way; there might be a few ways to do the same thing. https://www.google.com/search?q=reset+a+cookie+with+JavaScript

That said, I believe @oriooctopus added this maybe, so want to make sure he knows we are making this change.

**Comment by oriooctopus** [comment]
The change looks good to me. Honestly I don't know about the differences that domain=' + location.host would bring, but I agree with Joel, there are probably multiple ways to do this. I tested it and the behavior works

**Review by JoelMarcey — APPROVED** [review]

**Pull request merged**
