### PR TITLE
Rename DiemID move resources and rust structures to VASPDomain

### PR DESCRIPTION
**Pull request by sunmilee**
## Motivation

Updating move resources for DiemID to VASPDomain to reflect DIP 10: https://github.com/diem/dip/blob/main/dips/dip-182.md

## Test Plan

cargo x test -p move-lang-functional-tests vasp_domain.move
language/tools/move-cli and set UPDATE_BASELINE=1 and run cargo test in there. It should update the failing test's .exp file
cargo x test -p diem-json-rpc --test integration_test
cargo x test in client/faucet

## Related PRs

#8336

### CODE REVIEW

**Comment by sunmilee** [comment]
@tzakian can i just remove the DiemId.md file? seems like documentation that doesn't get removed when i cargo run

**Comment by sblackshear** [comment]
> @tzakian @sblackshear can i just remove the diem-framework/modules/doc/DiemId.md file? seems like documentation that doesn't get removed when i cargo run

Yes, this should be safe to remove. We should fix the tooling so it does this for you; I will file a task.

> also looks like a move-cli test is failing due to the changed name, but i can't figure out what script needs to be run to fix it. Any ideas?

`UB=1 cargo nexttest` in the CLI directory should do the trick

**Review by tzakian — APPROVED** [review]
This looks good to me! Only thing to keep in mind is that this will need to be a part of a release where the `DiemId` module has not yet been published yet. So if/when the 1.3 release branch gets deployed at some point this would need to be cherry-picked into that (otherwise this can go out with the 1.4 cut).

**Comment by bob-wilson** [comment]
> So if/when the 1.3 release branch gets deployed at some point this would need to be cherry-picked into that (otherwise this can go out with the 1.4 cut).

Putting this into 1.3 would be fine, since AFAIK this is renaming resources that were not present in 1.2. But, if it goes out with 1.4, will there be any compatibility issues? What if some of the resources were published on-chain with the old names using the 1.3 release?

**Comment by sunmilee** [comment]
Seems like we will not have a 1.3 framework release and skip to 1.4, so I don't think there will be any compatibility issues @bob-wilson @sherry-x

**Pull request closed without merging**
