### PR TITLE
[move-prover] Representing structs as ADTs instead of vectors.

### PR DESCRIPTION
**Pull request by wrwg**
[The PR was shelved a week ago or so to first get the new prover-lab and feature testing in so it could be leveraged here]

This PR forks the Boogie backend, this time into a new `boogie-backend-exp`. The new backend implements Move structs as Boogie datatypes instead of vectors.

The advantage of this representation is that no boxing of the field data is needed, as is the case for the vector representation `Vec $Value`. (Boxing is still required if the field has a generic type.) Moreover, as long as structs do not contain vectors, extensional equality holds. However, the `$Value` type is still needed with this PR, since we do not (yet) fully monomorphize. This leads to a representation of `$Value` as such:

```
type {:datatype} $Value;
// Predefined constructors
fun {:constuctor} $Integer(i: int): $Value
..

// Generated constructors
fun {:constructor} $Struct1_box(s: $Struct1): $Value;
fun {:constructor} $Struct2_box(s: $Struct2): $Value;
.. // and so on for all structs part of the verification problem
```

Benchmak data in the new lab `lab/data/struct-as-adt` ([pdf report](https://github.com/wrwg/diem/blob/mono/language/move-prover/lab/data/struct-as-adt/notebook.pdf)) shows that the ADT representation is slightly slower *but* has less timeouts. This might be because update of fields in ADT representation might be more expensive than update on vectors, as long as they are represented as Boogie/smt arrays. However, a final verdict cannot be made until the monomorphization work is finished and all usage of the `$Value` type has been eliminated.

For now, the new struct representation is not on by default but guarded by the flag `--bexp`. All tests are executed for both the default and the `bexp` feature (and pass).

Note that this is a larger PR because many rewrites of prelude and code generation had to be done. We can unfortunately not see a diff from forking of the boogie backend. **However I created a shadow PR #8181 which shows the diff between boogie-backend and boogie-backend-exp** by simply copying the later over the former, so see there if interested.

## Motivation

Determine best encoding of structs.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

New feature tests for `--bexp` for existing test cases.

## Related PRs

NA

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A boogie-backend-exp 0.1.0 (workspace, path 'language/move-prover/boogie-backend-exp')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A boogie-backend-exp 0.1.0 (workspace, path 'language/move-prover/boogie-backend-exp')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A boogie-backend-exp 0.1.0 (workspace, path 'language/move-prover/boogie-backend-exp')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A boogie-backend-exp 0.1.0 (workspace, path 'language/move-prover/boogie-backend-exp')
    * features: [none]
```

**Review by shazqadeer — APPROVED** [review]

**Pull request merged**
