### PR TITLE
[Move SDK codegen] Bump textwrap from 0.13.2 to 0.13.3

### PR DESCRIPTION
**Pull request by matbd**
## Motivation

Update textwrap correctly

## Test Plan

CI

## Related PRs

https://github.com/diem/diem/pull/7694

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M textwrap 0.13.3 (direct third-party, crates.io) (other versions: 0.11.0, 0.12.1)
    * version upgraded from 0.13.2
    * (unchanged features: default, smawk, unicode-width)
```

**Review by rexhoffman — APPROVED** [review]
Unfortunate that textwrap's output isn't more tightly defined.

**Comment by matbd** [comment]
> Unfortunate that textwrap's output isn't more tightly defined.

I left a comment to suggest bumping the major version number in this case.

**Pull request merged**
