### PR TITLE
[dependency] updating smallvec

### PR DESCRIPTION
**Pull request by mimoo**

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M smallvec 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M smallvec 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M smallvec 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
```

**Review by sausagee — APPROVED** [review]

**Pull request merged**
