### PR TITLE
[RUSTSEC-2021-0093][rel-1.3] crossbeam-deque 0.8.0 -> 0.8.1

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation
https://github.com/diem/diem/issues/9009
https://rustsec.org/advisories/RUSTSEC-2021-0093

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
y

## Test Plan

existing coverage

## Related PRs

(If this PR adds or changes functionality, please take some time to update or suggest changes to the docs at https://developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
dependency update

 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
existing tests

 * Why we must have it for V1 launch.
Vulnerability seems real.
 
 * What workarounds and alternative we have if we do not push the PR.
Wait for 1.5 roll.

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Review by sausagee — APPROVED** [review]
As discussed offline after reviewing the diff (P452304942), this pick is accepted.

**Pull request merged**
