### PR TITLE
[release-1.1] Gha fixes/utils, there will be more for pushing to diem.

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Cherry pick of several prs.

[gha] Move's audit logic to daily.yml
[gha] Audit logic runs of release-1.1
[gha] Audit needs the actions files used to reside in release-1.1 (the audit will break until they do).
[gha] Make the docker release target the correct branches (auto, release-1.1)
[gha] Makes e2e test failures in the auto branch get sent to slack
[gha] Makes audit failures get sent to slack as well.
[gha] Adds back in docker images for master ( for the 4 hour test of images in test cluster).
[gha] Uses full length git shas (needed before 2/15)
[gha] Moves dockerhub push to diem, Republished to libra
[gha] Adds better error handling to notify if a dockerpush fails.

### Have you read the [Contributing Guidelines on pull requests]

Y

## Test Plan

CI (this pr will trigger pre-release in auto branch and release to dockerhub in release-1.1 branch. 

## Related PRs

https://github.com/diem/diem/pull/7304
https://github.com/diem/diem/pull/7325
https://github.com/diem/diem/pull/7332
https://github.com/diem/diem/pull/7361
https://github.com/diem/diem/pull/7356
https://github.com/diem/diem/pull/7366
https://github.com/diem/diem/pull/7373

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Review by sausagee — APPROVED** [review]
/land

**Pull request merged**
