### PR TITLE
fix clippy error

### PR DESCRIPTION
**Pull request by zgfzgf**
optimize code

### CODE REVIEW

**Review by phlip9 — DISMISSED** [review]
Thanks! LGTM

**Comment by phlip9** [comment]
Looks like this PR (https://github.com/diem/diem/pull/7289) broke master briefly. You'll need to rebase onto master again before I can land : )

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M sha2 0.9.3 (direct third-party, crates.io)
    * version upgraded from 0.9.2
    * (unchanged features: default, std)
  M libc 0.2.85 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M sha2 0.9.3 (direct third-party, crates.io)
    * version upgraded from 0.9.2
    * (unchanged features: default, std)
  M smallvec 1.6.1 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M tokio 1.1.1 (direct third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: bytes, default, fs, full, io-std, io-util, libc, macros, memchr, mio, net, num_cpus, once_cell, parking_lot, process, rt, rt-multi-thread, signal, signal-hook-registry, sync, time, tokio-macros, winapi)
  M libc 0.2.85 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: align, default, std)
  M tokio-util 0.6.3 (transitive third-party, crates.io)
    * version upgraded from 0.6.2
    * (unchanged features: codec, default)
  R async-stream 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])
  R tokio-stream 0.1.2 (transitive third-party, crates.io)
    * (old features: default, time)

host packages:
  R async-stream-impl 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-client 0.1.0 (workspace, path 'sdk/client')
    * features: blocking, proxy, ureq
  A rental 0.5.5 (direct third-party, crates.io)
    * features: default, std
  A stable_deref_trait 1.2.0 (transitive third-party, crates.io)
    * features: alloc, std
  M sha2 0.9.3 (direct third-party, crates.io)
    * version upgraded from 0.9.2
    * (unchanged features: default, std)
  M smallvec 1.6.1 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M tokio 1.1.1 (direct third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: bytes, default, fs, full, io-std, io-util, libc, macros, memchr, mio, net, num_cpus, once_cell, parking_lot, process, rt, rt-multi-thread, signal, signal-hook-registry, sync, time, tokio-macros, winapi)
  M tokio-util 0.6.3 (direct third-party, crates.io)
    * version upgraded from 0.6.2
    * (unchanged features: codec, compat, default, futures-io, io)
  M libc 0.2.85 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: align, default, std)
  M sha-1 0.9.3 (transitive third-party, crates.io) (other versions: 0.8.2)
    * version upgraded from 0.9.2
    * (unchanged features: default, std)
  R diem-secure-json-rpc 0.1.0 (workspace, path 'secure/json-rpc')
    * (old features: [none])
  R async-stream 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  A rental-impl 0.5.5 (transitive third-party, crates.io)
    * features: [none]
  M syn 1.0.60 (direct third-party, crates.io)
    * added features: fold
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M libc 0.2.85 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: default, std)
  R async-stream-impl 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Review by davidiw — CHANGES_REQUESTED** [review]
not sure what's going on here, we might want to create a new PR or fix the strange merge issue that happened.

**Review by davidiw — APPROVED** [review]
that looks better!
/land

**Pull request closed without merging**
