### PR TITLE
[diem-vm] Create the parallel execution api for diem-vm

### PR DESCRIPTION
**Pull request by runtian-zhou**
## Motivation

Parallel execute diem transactions via the `parallel-executor` crate implemented previously by implementing a few adapter traits needed by the parallel executor.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Implemented a few simple test to test correctness for p2p transactions. Proptests are also upgraded to run with sequential and parallel execution to make sure the execution results are the same.

Here's the benchmark result for running 1000 transactions in parallel:

```
peer_to_peer            time:   [408.74 ms 415.81 ms 422.46 ms]                       
                        change: [-88.342% -88.048% -87.747%] (p = 0.00 < 0.05)
                        Performance has improved.

peer_to_peer_parallel   time:   [170.13 ms 183.82 ms 199.73 ms]                                
                        change: [-83.878% -82.464% -80.356%] (p = 0.00 < 0.05)
                        Performance has improved.
```

And the numbers for 5000 transactions:
```
Benchmarking peer_to_peer: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 24.6s.
peer_to_peer            time:   [1.8377 s 1.9229 s 2.0069 s]                          
                        change: [+342.04% +362.44% +383.44%] (p = 0.00 < 0.05)
                        Performance has regressed.

Benchmarking peer_to_peer_parallel: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 10.1s.
peer_to_peer_parallel   time:   [580.81 ms 609.38 ms 641.22 ms]                                
                        change: [+201.81% +231.50% +264.16%] (p = 0.00 < 0.05)
                        Performance has regressed.
```

All those transactions are generated by randomly transacting between 100 accounts.

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A diem-parallel-executor 0.1.0 (workspace, path 'language/diem-vm/parallel-executor')
    * features: [none]
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A mvhashmap 0.1.0 (workspace, path 'language/diem-vm/mvhashmap')
    * features: [none]
  A read-write-set 0.1.0 (workspace, path 'language/tools/read-write-set')
    * features: [none]
  A resource-viewer 0.1.0 (workspace, path 'language/tools/resource-viewer')
    * features: [none]
  A criterion 0.3.4 (direct third-party, crates.io)
    * features: cargo_bench_support, default
  A crossbeam-queue 0.3.1 (direct third-party, crates.io)
    * features: alloc, default, std
  A proptest 1.0.0 (direct third-party, crates.io)
    * features: bit-set, break-dead-code, default, fork, lazy_static, quick-error, regex-syntax, rusty-fork, std, tempfile, timeout
  A bit-set 0.5.2 (transitive third-party, crates.io)
    * features: default, std
  A bit-vec 0.6.3 (transitive third-party, crates.io)
    * features: std
  A cast 0.2.3 (transitive third-party, crates.io)
    * features: default, std
  A criterion-plot 0.4.3 (transitive third-party, crates.io)
    * features: [none]
  A csv 1.1.6 (transitive third-party, crates.io)
    * features: [none]
  A csv-core 0.1.10 (transitive third-party, crates.io)
    * features: default
  A half 1.7.1 (transitive third-party, crates.io)
    * features: [none]
  A itertools 0.9.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: default, use_std
  A oorandom 11.1.3 (transitive third-party, crates.io)
    * features: [none]
  A plotters 0.3.0 (transitive third-party, crates.io)
    * features: area_series, line_series, plotters-svg, svg_backend
  A plotters-backend 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A plotters-svg 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A quick-error 1.2.3 (transitive third-party, crates.io)
    * features: [none]
  A quick-error 2.0.0 (transitive third-party, crates.io)
    * features: [none]
  A rand_xorshift 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A rusty-fork 0.3.0 (transitive third-party, crates.io)
    * features: timeout, wait-timeout
  A serde_cbor 0.11.1 (transitive third-party, crates.io)
    * features: default, std
  A tinytemplate 1.2.1 (transitive third-party, crates.io)
    * features: [none]
  A wait-timeout 0.2.0 (transitive third-party, crates.io)
    * features: [none]
  M num_cpus 1.13.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M bstr 0.2.15 (transitive third-party, crates.io)
    * added features: default, lazy_static, regex-automata, serde, serde1, serde1-nostd, unicode
    * (unchanged features: std)
  M byteorder 1.4.3 (transitive third-party, crates.io)
    * added features: std
    * (unchanged features: i128)
  M num-traits 0.2.14 (transitive third-party, crates.io)
    * added features: default
    * (unchanged features: i128, std)

host packages:
  A proptest-derive 0.3.0 (direct third-party, crates.io)
    * features: [none]
  A proc-macro2 0.4.30 (transitive third-party, crates.io) (other versions: 1.0.28)
    * features: default, proc-macro
  A quote 0.6.13 (transitive third-party, crates.io) (other versions: 1.0.9)
    * features: default, proc-macro
  A rustc_version 0.2.3 (transitive third-party, crates.io)
    * features: [none]
  A semver 0.9.0 (transitive third-party, crates.io)
    * features: default
  A semver-parser 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A syn 0.15.44 (transitive third-party, crates.io) (other versions: 1.0.74)
    * features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit
  A unicode-xid 0.1.0 (transitive third-party, crates.io) (other versions: 0.2.2)
    * features: default
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-parallel-executor 0.1.0 (workspace, path 'language/diem-vm/parallel-executor')
    * features: [none]
  A mvhashmap 0.1.0 (workspace, path 'language/diem-vm/mvhashmap')
    * features: [none]
  A read-write-set 0.1.0 (workspace, path 'language/tools/read-write-set')
    * features: [none]
  A criterion 0.3.4 (direct third-party, crates.io)
    * features: cargo_bench_support, default
  A crossbeam-queue 0.3.1 (direct third-party, crates.io)
    * features: alloc, default, std
  A proptest 1.0.0 (direct third-party, crates.io)
    * features: bit-set, break-dead-code, default, fork, lazy_static, quick-error, regex-syntax, rusty-fork, std, tempfile, timeout
  A bit-set 0.5.2 (transitive third-party, crates.io)
    * features: default, std
  A bit-vec 0.6.3 (transitive third-party, crates.io)
    * features: std
  A cast 0.2.3 (transitive third-party, crates.io)
    * features: default, std
  A criterion-plot 0.4.3 (transitive third-party, crates.io)
    * features: [none]
  A csv 1.1.6 (transitive third-party, crates.io)
    * features: [none]
  A csv-core 0.1.10 (transitive third-party, crates.io)
    * features: default
  A half 1.7.1 (transitive third-party, crates.io)
    * features: [none]
  A itertools 0.9.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: default, use_std
  A oorandom 11.1.3 (transitive third-party, crates.io)
    * features: [none]
  A plotters 0.3.0 (transitive third-party, crates.io)
    * features: area_series, line_series, plotters-svg, svg_backend
  A plotters-backend 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A plotters-svg 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A quick-error 2.0.0 (transitive third-party, crates.io) (other versions: 1.2.3)
    * features: [none]
  A rand_xorshift 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A rusty-fork 0.3.0 (transitive third-party, crates.io)
    * features: timeout, wait-timeout
  A serde_cbor 0.11.1 (transitive third-party, crates.io)
    * features: default, std
  A tinytemplate 1.2.1 (transitive third-party, crates.io)
    * features: [none]
  A wait-timeout 0.2.0 (transitive third-party, crates.io)
    * features: [none]
  M bstr 0.2.15 (transitive third-party, crates.io)
    * added features: default, lazy_static, regex-automata, serde, serde1, serde1-nostd, unicode
    * (unchanged features: std)

host packages:
  A proptest-derive 0.3.0 (direct third-party, crates.io)
    * features: [none]
  A proc-macro2 0.4.30 (transitive third-party, crates.io) (other versions: 1.0.28)
    * features: default, proc-macro
  A quote 0.6.13 (transitive third-party, crates.io) (other versions: 1.0.9)
    * features: default, proc-macro
  A rustc_version 0.2.3 (transitive third-party, crates.io)
    * features: [none]
  A semver 0.9.0 (transitive third-party, crates.io)
    * features: default
  A semver-parser 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A syn 0.15.44 (transitive third-party, crates.io) (other versions: 1.0.74)
    * features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit
  A unicode-xid 0.1.0 (transitive third-party, crates.io) (other versions: 0.2.2)
    * features: default
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A diem-parallel-executor 0.1.0 (workspace, path 'language/diem-vm/parallel-executor')
    * features: [none]
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A mvhashmap 0.1.0 (workspace, path 'language/diem-vm/mvhashmap')
    * features: [none]
  A read-write-set 0.1.0 (workspace, path 'language/tools/read-write-set')
    * features: [none]
  A resource-viewer 0.1.0 (workspace, path 'language/tools/resource-viewer')
    * features: [none]
  A criterion 0.3.4 (direct third-party, crates.io)
    * features: cargo_bench_support, default
  A crossbeam-queue 0.3.1 (direct third-party, crates.io)
    * features: alloc, default, std
  A proptest 1.0.0 (direct third-party, crates.io)
    * features: bit-set, break-dead-code, default, fork, lazy_static, quick-error, regex-syntax, rusty-fork, std, tempfile, timeout
  A bit-set 0.5.2 (transitive third-party, crates.io)
    * features: default, std
  A bit-vec 0.6.3 (transitive third-party, crates.io)
    * features: std
  A cast 0.2.3 (transitive third-party, crates.io)
    * features: default, std
  A criterion-plot 0.4.3 (transitive third-party, crates.io)
    * features: [none]
  A csv 1.1.6 (transitive third-party, crates.io)
    * features: [none]
  A csv-core 0.1.10 (transitive third-party, crates.io)
    * features: default
  A half 1.7.1 (transitive third-party, crates.io)
    * features: [none]
  A itertools 0.9.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: default, use_std
  A oorandom 11.1.3 (transitive third-party, crates.io)
    * features: [none]
  A plotters 0.3.0 (transitive third-party, crates.io)
    * features: area_series, line_series, plotters-svg, svg_backend
  A plotters-backend 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A plotters-svg 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A quick-error 1.2.3 (transitive third-party, crates.io)
    * features: [none]
  A quick-error 2.0.0 (transitive third-party, crates.io)
    * features: [none]
  A rand_xorshift 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A rusty-fork 0.3.0 (transitive third-party, crates.io)
    * features: timeout, wait-timeout
  A serde_cbor 0.11.1 (transitive third-party, crates.io)
    * features: default, std
  A tinytemplate 1.2.1 (transitive third-party, crates.io)
    * features: [none]
  A wait-timeout 0.2.0 (transitive third-party, crates.io)
    * features: [none]
  M num_cpus 1.13.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M bstr 0.2.15 (transitive third-party, crates.io)
    * added features: default, lazy_static, regex-automata, serde, serde1, serde1-nostd, unicode
    * (unchanged features: std)
  M byteorder 1.4.3 (transitive third-party, crates.io)
    * added features: std
    * (unchanged features: i128)
  M num-traits 0.2.14 (transitive third-party, crates.io)
    * added features: default
    * (unchanged features: i128, std)

host packages:
  A proptest-derive 0.3.0 (direct third-party, crates.io)
    * features: [none]
  A proc-macro2 0.4.30 (transitive third-party, crates.io) (other versions: 1.0.28)
    * features: default, proc-macro
  A quote 0.6.13 (transitive third-party, crates.io) (other versions: 1.0.9)
    * features: default, proc-macro
  A rustc_version 0.2.3 (transitive third-party, crates.io)
    * features: [none]
  A semver 0.9.0 (transitive third-party, crates.io)
    * features: default
  A semver-parser 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A syn 0.15.44 (transitive third-party, crates.io) (other versions: 1.0.74)
    * features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit
  A unicode-xid 0.1.0 (transitive third-party, crates.io) (other versions: 0.2.2)
    * features: default
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A diem-parallel-executor 0.1.0 (workspace, path 'language/diem-vm/parallel-executor')
    * features: [none]
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A mvhashmap 0.1.0 (workspace, path 'language/diem-vm/mvhashmap')
    * features: [none]
  A read-write-set 0.1.0 (workspace, path 'language/tools/read-write-set')
    * features: [none]
  A resource-viewer 0.1.0 (workspace, path 'language/tools/resource-viewer')
    * features: [none]
  A crossbeam-queue 0.3.1 (direct third-party, crates.io)
    * features: alloc, default, std
  M num_cpus 1.13.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
```

**Review by sblackshear — DISMISSED** [review]

**Pull request closed without merging**
