### PR TITLE
Cherry-Picking trusted-waypoint support of the restore/backup-verify tools

### PR DESCRIPTION
**Pull request by msmouse**
Cherry picking 
https://github.com/diem/diem/pull/7329
https://github.com/diem/diem/pull/7414 

* Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
The db-backup-verify and db-restore tools fail running after a writeset txn drill without this.

* Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
unit tests, smoke test

* Why we must have it for V1 launch.
To demonstrate and verify everything still works after a writeset txn.

* What workarounds and alternative we have if we do not push the PR.
Assume there will be no writetxn in production before next release.

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M socket2 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M socket2 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Review by sausagee — APPROVED** [review]
Please fix up the warp dep before landing.

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M socket2 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M socket2 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Pull request merged**
