### PR TITLE
[crypto] ECDSA secp256r1 in diem-crypto

### PR DESCRIPTION
**Pull request by kchalkias**
## Motivation

Supporting ECDSA with secp256r1 curve (known as NIST P-256 as well) in `diem-crypto` crate.
This algorithm might boost Diem's adoption due to being compatible with all major HSM devices (even old ones) and mobile secure enclaves. The latter can also allow for mobile-phone hardware wallets which might help on ceremonies, unhosted wallets etc.

This PR is only adding signature operations via the RustCrypto p256 crate (+ some reasonable compatibility modifications), and at the moment **it is not introducing a new blockchain Authenticator**, which means it won't affect any of the blockchain operations. This is on purpose, so we can properly review the algorithm first and keep the related PRs (i.e., extensive tests) as manageable as possible, as we're not targeting V1. **Ideally, we could add it under a "crypto-experimental' feature.**

Note that this work required significant effort by evaluating various implementations, to ensure compatibility with iPhone and Android native signatures + unlike Bitcoin's variable 70-72byte signature, we use a 64byte fixed compressed signature size.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

YES

## Test Plan

`sign_verify` and `serialization_full_cycle`

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A p256 0.9.0 (direct third-party, crates.io)
    * features: arithmetic, default, digest, ecdsa, ecdsa-core, pkcs8, sha2, sha256, std, zeroize
  A const-oid 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A crypto-bigint 0.2.0 (transitive third-party, crates.io)
    * features: generic-array
  A crypto-mac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: [none]
  A der 0.4.0 (transitive third-party, crates.io)
    * features: const-oid, oid
  A ecdsa 0.12.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, der, digest, hazmat, hmac, sign, std, verify, zeroize
  A elliptic-curve 0.10.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, ff, group, hazmat, pkcs8, std, zeroize
  A ff 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A group 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A hmac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: [none]
  A pkcs8 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A spki 0.4.0 (transitive third-party, crates.io)
    * features: [none]
  M signature 1.3.0 (transitive third-party, crates.io)
    * added features: digest, digest-preview, rand-preview, rand_core
    * (unchanged features: std)
  M subtle 2.4.0 (transitive third-party, crates.io)
    * added features: i128
    * (unchanged features: std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A p256 0.9.0 (direct third-party, crates.io)
    * features: arithmetic, default, digest, ecdsa, ecdsa-core, pkcs8, sha2, sha256, std, zeroize
  A const-oid 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A crypto-bigint 0.2.0 (transitive third-party, crates.io)
    * features: generic-array
  A crypto-mac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: [none]
  A der 0.4.0 (transitive third-party, crates.io)
    * features: const-oid, oid
  A ecdsa 0.12.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, der, digest, hazmat, hmac, sign, std, verify, zeroize
  A elliptic-curve 0.10.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, ff, group, hazmat, pkcs8, std, zeroize
  A ff 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A group 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A hmac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: [none]
  A pkcs8 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A spki 0.4.0 (transitive third-party, crates.io)
    * features: [none]
  M signature 1.3.0 (transitive third-party, crates.io)
    * added features: digest, digest-preview, rand-preview, rand_core
    * (unchanged features: std)
  M subtle 2.4.0 (transitive third-party, crates.io)
    * added features: i128
    * (unchanged features: std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A p256 0.9.0 (direct third-party, crates.io)
    * features: arithmetic, default, digest, ecdsa, ecdsa-core, pkcs8, sha2, sha256, std, zeroize
  A const-oid 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A crypto-bigint 0.2.0 (transitive third-party, crates.io)
    * features: generic-array
  A crypto-mac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: [none]
  A der 0.4.0 (transitive third-party, crates.io)
    * features: const-oid, oid
  A ecdsa 0.12.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, der, digest, hazmat, hmac, sign, std, verify, zeroize
  A elliptic-curve 0.10.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, ff, group, hazmat, pkcs8, std, zeroize
  A ff 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A group 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A hmac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: [none]
  A pkcs8 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A spki 0.4.0 (transitive third-party, crates.io)
    * features: [none]
  M signature 1.3.0 (transitive third-party, crates.io)
    * added features: digest, digest-preview, rand-preview, rand_core
    * (unchanged features: std)
  M subtle 2.4.0 (transitive third-party, crates.io)
    * added features: i128
    * (unchanged features: std)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A p256 0.9.0 (direct third-party, crates.io)
    * features: arithmetic, default, digest, ecdsa, ecdsa-core, pkcs8, sha2, sha256, std, zeroize
  A const-oid 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A crypto-bigint 0.2.0 (transitive third-party, crates.io)
    * features: generic-array
  A crypto-mac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: [none]
  A der 0.4.0 (transitive third-party, crates.io)
    * features: const-oid, oid
  A ecdsa 0.12.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, der, digest, hazmat, hmac, sign, std, verify, zeroize
  A elliptic-curve 0.10.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, ff, group, hazmat, pkcs8, std, zeroize
  A ff 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A group 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A hmac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: [none]
  A pkcs8 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A spki 0.4.0 (transitive third-party, crates.io)
    * features: [none]
  M signature 1.3.0 (transitive third-party, crates.io)
    * added features: digest, digest-preview, rand-preview, rand_core
    * (unchanged features: std)
  M subtle 2.4.0 (transitive third-party, crates.io)
    * added features: i128
    * (unchanged features: std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A p256 0.9.0 (direct third-party, crates.io)
    * features: arithmetic, default, digest, ecdsa, ecdsa-core, pkcs8, sha2, sha256, std, zeroize
  A const-oid 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A crypto-bigint 0.2.0 (transitive third-party, crates.io)
    * features: generic-array
  A crypto-mac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: [none]
  A der 0.4.0 (transitive third-party, crates.io)
    * features: const-oid, oid
  A ecdsa 0.12.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, der, digest, hazmat, hmac, sign, std, verify, zeroize
  A elliptic-curve 0.10.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, ff, group, hazmat, pkcs8, std, zeroize
  A ff 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A group 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A hmac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: [none]
  A pkcs8 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A spki 0.4.0 (transitive third-party, crates.io)
    * features: [none]
  M signature 1.3.0 (transitive third-party, crates.io)
    * added features: digest, digest-preview, rand-preview, rand_core
    * (unchanged features: std)
  M subtle 2.4.0 (transitive third-party, crates.io)
    * added features: i128
    * (unchanged features: std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A p256 0.9.0 (direct third-party, crates.io)
    * features: arithmetic, default, digest, ecdsa, ecdsa-core, pkcs8, sha2, sha256, std, zeroize
  A const-oid 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A crypto-bigint 0.2.0 (transitive third-party, crates.io)
    * features: generic-array
  A crypto-mac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: [none]
  A der 0.4.0 (transitive third-party, crates.io)
    * features: const-oid, oid
  A ecdsa 0.12.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, der, digest, hazmat, hmac, sign, std, verify, zeroize
  A elliptic-curve 0.10.2 (transitive third-party, crates.io)
    * features: alloc, arithmetic, ff, group, hazmat, pkcs8, std, zeroize
  A ff 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A group 0.10.0 (transitive third-party, crates.io)
    * features: [none]
  A hmac 0.11.0 (transitive third-party, crates.io) (other versions: 0.10.1)
    * features: [none]
  A pkcs8 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A spki 0.4.0 (transitive third-party, crates.io)
    * features: [none]
  M signature 1.3.0 (transitive third-party, crates.io)
    * added features: digest, digest-preview, rand-preview, rand_core
    * (unchanged features: std)
  M subtle 2.4.0 (transitive third-party, crates.io)
    * added features: i128
    * (unchanged features: std)
```

**Comment by davidiw** [comment]
Do we have an application for this?

**Comment by davidiw** [comment]
So my only ask is that we figure out how to add some features around this so that codebases only need to take the portions of the libraries that they want to take in. Given all the amazing advances in crypto that might be useful for a blockchain, I do worry this could be a dumping ground. While ECDSA might be useful for explorations in the space, it has no practical application in our current validator network, but this would pull in additional source code into TCBs.

**Comment by kchalkias** [comment]
After many discussions re reducing the TCB's deps, I'm going to park this PR, mainly waiting until agile authenticators are in place and ECDSA will be officially requested by the community. Thanks for the feedback and brainstorming @davidiw @aching @dmitri-perelman.

**Comment by bmwill** [comment]
If we wanted to carry this code in the codebase it wouldn't be very hard to just gate it with a compile-time feature flag, disabling it by default. But waiting till we have more clarity on how we want to enable agility is also a reasonable approach :)

**Pull request closed without merging**
