### PR TITLE
halp halp halp

### PR DESCRIPTION
**Pull request by patcon**
:)

### CODE REVIEW

**Comment by bob-wilson** [comment]
Seems like an obvious, if trivial, fix. A more informative title for the PR would be helpful.... I'll defer to someone working on consensus to approve

**Comment by patcon** [comment]
No shame in closing this if it's too tiny a thing to pass through the seemingly big process y'all have. If this takes anyone else's valuable attention, it's prob too much

**Review by davidiw — COMMENTED** [review]
rofl, might as well, but as @bob-wilson said a PR that says "consensus doc nit" would have been useful.

as you can imagine we get a couple PRs every now and then that have interesting titles that have 0 value, so :)

/land

**Review by davidiw — APPROVED** [review]
/land

**Pull request closed without merging**
