### PR TITLE
[language] rename 'stdlib' to 'diem-framework'

### PR DESCRIPTION
**Pull request by vgao1996**
This is the first step to split `stdlib` into `diem-stdlib` and`move-stdlib`. Most existing contents are diem-related so it makes sense to prefix the current crate with diem and split out the Move ones later.

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-stdlib 0.1.0 (workspace, path 'language/diem-stdlib')
    * features: default
  M compiled-stdlib 0.1.0 (workspace, path 'language/diem-stdlib/compiled')
    * source changed from path 'language/stdlib/compiled'
    * (unchanged features: default)
  R stdlib 0.1.0 (workspace, path 'language/stdlib')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-stdlib 0.1.0 (workspace, path 'language/diem-stdlib')
    * features: default
  M compiled-stdlib 0.1.0 (workspace, path 'language/diem-stdlib/compiled')
    * source changed from path 'language/stdlib/compiled'
    * (unchanged features: default)
  R stdlib 0.1.0 (workspace, path 'language/stdlib')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-stdlib 0.1.0 (workspace, path 'language/diem-stdlib')
    * features: default
  M compiled-stdlib 0.1.0 (workspace, path 'language/diem-stdlib/compiled')
    * source changed from path 'language/stdlib/compiled'
    * (unchanged features: default)
  R stdlib 0.1.0 (workspace, path 'language/stdlib')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-stdlib 0.1.0 (workspace, path 'language/diem-stdlib')
    * features: default
  M compiled-stdlib 0.1.0 (workspace, path 'language/diem-stdlib/compiled')
    * source changed from path 'language/stdlib/compiled'
    * (unchanged features: default)
  R stdlib 0.1.0 (workspace, path 'language/stdlib')
    * (old features: default)
```

**Comment by sblackshear** [comment]
As long as we're renaming, could we call it `diem-framework` to match the name we use elsewhere?

**Comment by vgao1996** [comment]
@sblackshear sounds good to me!

**Comment by vgao1996** [comment]
@sblackshear done with the renaming

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-framework 0.1.0 (workspace, path 'language/diem-framework')
    * features: default
  M compiled-stdlib 0.1.0 (workspace, path 'language/diem-framework/compiled')
    * source changed from path 'language/stdlib/compiled'
    * (unchanged features: default)
  R stdlib 0.1.0 (workspace, path 'language/stdlib')
    * (old features: default)
```

**Comment by vgao1996** [comment]
Looks like I might have broken a bunch of things inside `transaction-builder`. Will get them fixed.

**Review by tzakian — APPROVED** [review]
I'm liking the new name :)

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-framework 0.1.0 (workspace, path 'language/diem-framework')
    * features: default
  M compiled-stdlib 0.1.0 (workspace, path 'language/diem-framework/compiled')
    * source changed from path 'language/stdlib/compiled'
    * (unchanged features: default)
  R stdlib 0.1.0 (workspace, path 'language/stdlib')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-framework 0.1.0 (workspace, path 'language/diem-framework')
    * features: default
  M compiled-stdlib 0.1.0 (workspace, path 'language/diem-framework/compiled')
    * source changed from path 'language/stdlib/compiled'
    * (unchanged features: default)
  R stdlib 0.1.0 (workspace, path 'language/stdlib')
    * (old features: default)
```

**Comment by vgao1996** [comment]
cc @matbd 

I was able to manually run and pass all but one tests in `language/transaction_builder`. Didn't manage to get the go one running, even on master, so I don't know what state it is in. You might want to have a look.

**Pull request closed without merging**
