### PR TITLE
[gha] fail on failed sccache unit test runs.

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Clean up things I forgot

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

CI

## Related PRs

None

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Review by bmwill — APPROVED** [review]
/land

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R boogie-backend-exp 0.1.0 (workspace, path 'language/move-prover/boogie-backend-exp')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R boogie-backend-exp 0.1.0 (workspace, path 'language/move-prover/boogie-backend-exp')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R boogie-backend-exp 0.1.0 (workspace, path 'language/move-prover/boogie-backend-exp')
    * (old features: [none])
```

**Pull request merged**
