### PR TITLE
diem-types and move-core-types dependency cleanups

### PR DESCRIPTION
**Pull request by bmwill**
This PR does 2 things:
* Remove the dependency on proptest-helpers for diem-types
* remove the dependency on diem-crypto for move-core-types

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M move-core-types 0.1.0 (workspace, path 'language/move-core/types')
    * removed features: fiat
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M move-core-types 0.1.0 (workspace, path 'language/move-core/types')
    * removed features: fiat
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M move-core-types 0.1.0 (workspace, path 'language/move-core/types')
    * removed features: fiat
    * (unchanged features: default)
```

**Review by metajack — APPROVED** [review]
Looks good, although I think the `mod hasher { ... }` construction needs explanatory comments.

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M move-core-types 0.1.0 (workspace, path 'language/move-core/types')
    * removed features: fiat
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M move-core-types 0.1.0 (workspace, path 'language/move-core/types')
    * removed features: fiat
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M move-core-types 0.1.0 (workspace, path 'language/move-core/types')
    * removed features: fiat
    * (unchanged features: default)
```

**Comment by sblackshear** [comment]
Thanks for this @bmwill!

**Pull request merged**
