### PR TITLE
[cli] Fix the logic for fetching diem_root account in the cli.

### PR DESCRIPTION
**Pull request by runtian-zhou**
## Motivation

This PR aims to fix the issue mentioned [here](https://community.diem.com/t/how-to-compile-publish-modules-using-diem-cli-client-connected-to-a-local-test-validator-network/3534). The current cli can't get the account for diem_root account or tc account, causing functionalities like module publishing to fail.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Tested the module publishing flow via following command:
```
diem% dev c 0000000000000000000000000a550c18 <PATH_TO_MODULE>
diem% dev publish 0000000000000000000000000a550c18   <PATH_TO_COMPILED_MV>
```

### CODE REVIEW

**Comment by sblackshear** [comment]
Thanks for the fix!

A test for fetching the root account might be useful to ensure this keeps working.

**Review by sblackshear — APPROVED** [review]

**Review by xli — APPROVED** [review]

**Comment by runtian-zhou** [comment]
> A test for fetching the root account might be useful to ensure this keeps working.

I fetched the root account with module publishing command and it worked!

**Comment by alftom** [comment]
I just did a git pull, cargo run diem-node/cli, and then got the following:

diem% account create
>> Creating/retrieving next local account from wallet
Created/retrieved local account #0 address 543e98a2844490fee7d1291aae65a802
diem% account list
User account index: 0, address: 543e98a2844490fee7d1291aae65a802, private_key: "20350bd5782a6ecdae6d1f32d7b9d29fffbac262adf2c6ed79083eecb396eaf9", sequence number: 0, status: Local
AssocRoot account address: 0000000000000000000000000a550c18, sequence_number: 1, status: Persisted
TC account address: 0000000000000000000000000b1e55ed, sequence_number: 0, status: Persisted
Testnet DD account address: 000000000000000000000000000000dd, sequence_number: 0, status: Persisted
diem% dev c 0000000000000000000000000a550c18 [folder]/src/modules /home/alfriko/diem/language/move-stdlib/nursery [folder]/diem/language/move-stdlib/modules
>> Compiling program
    Finished dev [unoptimized + debuginfo] target(s) in 1.77s
     Running `target/debug/move-build 0000000000000000000000000a550c18 -o /tmp/5b05103ccae87f19341d05041f418da4 -d /home/alfriko/lumian-diem/src/modules -d [folder]/diem/language/move-stdlib/nursery -d [folder]/diem/language/move-stdlib/modules`
Error: No such file or directory '0000000000000000000000000a550c18'
compilation failed
diem% 

Any reason why it thinks 0000000000000000000000000a550c18 should be a file or directory?  When I remove 0000000000000000000000000a550c18 the modules seem to compile fine, but that might be causing other issues I'm seeing.

**Pull request merged**
