### PR TITLE
[GHA]Merge LBT workflow into ci-test workflow

### PR DESCRIPTION
**Pull request by zihaoccc**
Justification: The change merged LBT workflow into main ci-test workflow allows CI/CD has one unified single signal instead of two places which will beneficial on call procedure. Also new unified workflow can save one time of code building

    
Cherry-pick following prs:

[GHA] Added build-images step into ci-test workflow(https://github.com/diem/diem/pull/7821)
[GHA] Merge LBT workflow into ci-test(https://github.com/diem/diem/pull/7856)
[GHA]unify LBT switch job into LBT(https://github.com/diem/diem/pull/7939)

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Comment by zihaoccc** [comment]
Justification: The change merged LBT workflow into main ci-test workflow allows CI/CD has an unify single signal instead of two places. Saving one time of code build

Workarounds: Stop bors listening derecated LBT workflow and delete non-used LBT workflow

**Review by sausagee — APPROVED** [review]

**Pull request merged**
