### PR TITLE
crates: move the remaining common crates to the crates directory

### PR DESCRIPTION
**Pull request by bmwill**

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M diem-infallible 0.1.0 (workspace, path 'crates/diem-infallible')
    * source changed from path 'common/infallible'
    * (unchanged features: [none])
  M diem-logger 0.1.0 (workspace, path 'crates/diem-logger')
    * source changed from path 'common/logger'
    * (unchanged features: [none])
  M diem-metrics 0.1.0 (workspace, path 'crates/diem-metrics')
    * source changed from path 'common/metrics'
    * (unchanged features: [none])
  M diem-metrics-core 0.1.0 (workspace, path 'crates/diem-metrics-core')
    * source changed from path 'common/metrics-core'
    * (unchanged features: [none])
  M diem-temppath 0.1.0 (workspace, path 'crates/diem-temppath')
    * source changed from path 'common/temppath'
    * (unchanged features: [none])
  M diem-time-service 0.1.0 (workspace, path 'crates/diem-time-service')
    * source changed from path 'common/time-service'
    * (unchanged features: default)
  M short-hex-str 0.1.0 (workspace, path 'crates/short-hex-str')
    * source changed from path 'common/short-hex-str'
    * (unchanged features: [none])

host packages:
  M diem-log-derive 0.1.0 (workspace, path 'crates/diem-log-derive')
    * source changed from path 'common/logger/derive'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M crash-handler 0.1.0 (workspace, path 'crates/crash-handler')
    * source changed from path 'common/crash-handler'
    * (unchanged features: [none])
  M diem-infallible 0.1.0 (workspace, path 'crates/diem-infallible')
    * source changed from path 'common/infallible'
    * (unchanged features: [none])
  M diem-logger 0.1.0 (workspace, path 'crates/diem-logger')
    * source changed from path 'common/logger'
    * (unchanged features: [none])
  M diem-metrics-core 0.1.0 (workspace, path 'crates/diem-metrics-core')
    * source changed from path 'common/metrics-core'
    * (unchanged features: [none])
  M diem-temppath 0.1.0 (workspace, path 'crates/diem-temppath')
    * source changed from path 'common/temppath'
    * (unchanged features: [none])
  M diem-time-service 0.1.0 (workspace, path 'crates/diem-time-service')
    * source changed from path 'common/time-service'
    * (unchanged features: default)
  M short-hex-str 0.1.0 (workspace, path 'crates/short-hex-str')
    * source changed from path 'common/short-hex-str'
    * (unchanged features: [none])

host packages:
  M diem-log-derive 0.1.0 (workspace, path 'crates/diem-log-derive')
    * source changed from path 'common/logger/derive'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M channel 0.1.0 (workspace, path 'crates/channel')
    * source changed from path 'common/channel'
    * (unchanged features: [none])
  M crash-handler 0.1.0 (workspace, path 'crates/crash-handler')
    * source changed from path 'common/crash-handler'
    * (unchanged features: [none])
  M debug-interface 0.1.0 (workspace, path 'crates/debug-interface')
    * source changed from path 'common/debug-interface'
    * (unchanged features: [none])
  M diem-id-generator 0.1.0 (workspace, path 'crates/diem-id-generator')
    * source changed from path 'common/id-generator'
    * (unchanged features: [none])
  M diem-infallible 0.1.0 (workspace, path 'crates/diem-infallible')
    * source changed from path 'common/infallible'
    * (unchanged features: [none])
  M diem-logger 0.1.0 (workspace, path 'crates/diem-logger')
    * source changed from path 'common/logger'
    * (unchanged features: [none])
  M diem-metrics 0.1.0 (workspace, path 'crates/diem-metrics')
    * source changed from path 'common/metrics'
    * (unchanged features: [none])
  M diem-metrics-core 0.1.0 (workspace, path 'crates/diem-metrics-core')
    * source changed from path 'common/metrics-core'
    * (unchanged features: [none])
  M diem-rate-limiter 0.1.0 (workspace, path 'crates/diem-rate-limiter')
    * source changed from path 'common/rate-limiter'
    * (unchanged features: [none])
  M diem-temppath 0.1.0 (workspace, path 'crates/diem-temppath')
    * source changed from path 'common/temppath'
    * (unchanged features: [none])
  M diem-time-service 0.1.0 (workspace, path 'crates/diem-time-service')
    * source changed from path 'common/time-service'
    * (unchanged features: async, default, futures, pin-project, tokio)
  M fallible 0.1.0 (workspace, path 'crates/fallible')
    * source changed from path 'common/fallible'
    * (unchanged features: [none])
  M short-hex-str 0.1.0 (workspace, path 'crates/short-hex-str')
    * source changed from path 'common/short-hex-str'
    * (unchanged features: [none])

host packages:
  M diem-log-derive 0.1.0 (workspace, path 'crates/diem-log-derive')
    * source changed from path 'common/logger/derive'
    * (unchanged features: [none])
  M num-variants 0.1.0 (workspace, path 'crates/num-variants')
    * source changed from path 'common/num-variants'
    * (unchanged features: [none])
```

**Review by JoshLind — DISMISSED** [review]

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M crash-handler 0.1.0 (workspace, path 'crates/crash-handler')
    * source changed from path 'common/crash-handler'
    * (unchanged features: [none])
  M diem-infallible 0.1.0 (workspace, path 'crates/diem-infallible')
    * source changed from path 'common/infallible'
    * (unchanged features: [none])
  M diem-logger 0.1.0 (workspace, path 'crates/diem-logger')
    * source changed from path 'common/logger'
    * (unchanged features: [none])
  M diem-metrics-core 0.1.0 (workspace, path 'crates/diem-metrics-core')
    * source changed from path 'common/metrics-core'
    * (unchanged features: [none])
  M diem-temppath 0.1.0 (workspace, path 'crates/diem-temppath')
    * source changed from path 'common/temppath'
    * (unchanged features: [none])
  M diem-time-service 0.1.0 (workspace, path 'crates/diem-time-service')
    * source changed from path 'common/time-service'
    * (unchanged features: default)
  M short-hex-str 0.1.0 (workspace, path 'crates/short-hex-str')
    * source changed from path 'common/short-hex-str'
    * (unchanged features: [none])

host packages:
  M diem-log-derive 0.1.0 (workspace, path 'crates/diem-log-derive')
    * source changed from path 'common/logger/derive'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M channel 0.1.0 (workspace, path 'crates/channel')
    * source changed from path 'common/channel'
    * (unchanged features: [none])
  M crash-handler 0.1.0 (workspace, path 'crates/crash-handler')
    * source changed from path 'common/crash-handler'
    * (unchanged features: [none])
  M debug-interface 0.1.0 (workspace, path 'crates/debug-interface')
    * source changed from path 'common/debug-interface'
    * (unchanged features: [none])
  M diem-id-generator 0.1.0 (workspace, path 'crates/diem-id-generator')
    * source changed from path 'common/id-generator'
    * (unchanged features: [none])
  M diem-infallible 0.1.0 (workspace, path 'crates/diem-infallible')
    * source changed from path 'common/infallible'
    * (unchanged features: [none])
  M diem-logger 0.1.0 (workspace, path 'crates/diem-logger')
    * source changed from path 'common/logger'
    * (unchanged features: [none])
  M diem-metrics 0.1.0 (workspace, path 'crates/diem-metrics')
    * source changed from path 'common/metrics'
    * (unchanged features: [none])
  M diem-metrics-core 0.1.0 (workspace, path 'crates/diem-metrics-core')
    * source changed from path 'common/metrics-core'
    * (unchanged features: [none])
  M diem-rate-limiter 0.1.0 (workspace, path 'crates/diem-rate-limiter')
    * source changed from path 'common/rate-limiter'
    * (unchanged features: [none])
  M diem-temppath 0.1.0 (workspace, path 'crates/diem-temppath')
    * source changed from path 'common/temppath'
    * (unchanged features: [none])
  M diem-time-service 0.1.0 (workspace, path 'crates/diem-time-service')
    * source changed from path 'common/time-service'
    * (unchanged features: async, default, futures, pin-project, tokio)
  M fallible 0.1.0 (workspace, path 'crates/fallible')
    * source changed from path 'common/fallible'
    * (unchanged features: [none])
  M short-hex-str 0.1.0 (workspace, path 'crates/short-hex-str')
    * source changed from path 'common/short-hex-str'
    * (unchanged features: [none])

host packages:
  M diem-log-derive 0.1.0 (workspace, path 'crates/diem-log-derive')
    * source changed from path 'common/logger/derive'
    * (unchanged features: [none])
  M num-variants 0.1.0 (workspace, path 'crates/num-variants')
    * source changed from path 'common/num-variants'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M diem-infallible 0.1.0 (workspace, path 'crates/diem-infallible')
    * source changed from path 'common/infallible'
    * (unchanged features: [none])
  M diem-logger 0.1.0 (workspace, path 'crates/diem-logger')
    * source changed from path 'common/logger'
    * (unchanged features: [none])
  M diem-metrics 0.1.0 (workspace, path 'crates/diem-metrics')
    * source changed from path 'common/metrics'
    * (unchanged features: [none])
  M diem-metrics-core 0.1.0 (workspace, path 'crates/diem-metrics-core')
    * source changed from path 'common/metrics-core'
    * (unchanged features: [none])
  M diem-temppath 0.1.0 (workspace, path 'crates/diem-temppath')
    * source changed from path 'common/temppath'
    * (unchanged features: [none])
  M diem-time-service 0.1.0 (workspace, path 'crates/diem-time-service')
    * source changed from path 'common/time-service'
    * (unchanged features: default)
  M short-hex-str 0.1.0 (workspace, path 'crates/short-hex-str')
    * source changed from path 'common/short-hex-str'
    * (unchanged features: [none])

host packages:
  M diem-log-derive 0.1.0 (workspace, path 'crates/diem-log-derive')
    * source changed from path 'common/logger/derive'
    * (unchanged features: [none])
```

**Pull request merged**
