### PR TITLE
Rusoto

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Handle landing rusoto update which must land together.

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

Canary

## Related PRs

Open rusoto prs.

### CODE REVIEW

**Comment by metajack** [comment]
Why is the first commit in this PR?

**Review by metajack — APPROVED** [review]

**Comment by rexhoffman** [comment]
There's one commit in this pr, as I saved a minute to work from master rather than pulling one of the 4 open prs to build on.  I could have done that and stamped myself.   I can still do that if you prefer.

**Comment by rexhoffman** [comment]
thanks for the stamp

**Comment by rexhoffman** [comment]
Well damn:

```
thread 'main' panicked at 'not currently running on the Tokio runtime.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/runtime/blocking/pool.rs:84:33
```

**Comment by rexhoffman** [comment]
@bmwill this appears to be contingent on tokio.   may drill in more later.

**Comment by bmwill** [comment]
@rexhoffman Yep there's like 10 deps that need to be updated in lock step due to the tokio upgrade. I'm going to be digging into that today so I'll cherry-pick this commit into my series

**Pull request closed without merging**
