### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

All the debian docker updates in one go, on top of the disabling of arch pr that I'm waiting to land.   https://github.com/diem/diem/pull/7553

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

CI

## Related PRs

https://github.com/diem/diem/pull/7553

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/master/developers.diem.com, and link to your PR here.)

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
What does this mean for me as an Arch user?

**Comment by rexhoffman** [comment]
@davidiw once arch sorts their glibc issues nothing, until then I wouldn't update much unless you want to spend some time fixing your system.   Not going to investigate too deeply as I lost too much of my life learning the ins and outs of linux via unstable debian/gentoo a decade ago.

**Pull request merged**
