### PR TITLE
[diem adapter] fix multi agent: include secondary signers for script funs

### PR DESCRIPTION
**Pull request by emmazzz**
## Motivation

@xli  has found an issue with the integration test written for multi agent txns: the script function used in that test did not have multiple signers and the validator failed to detect this difference in the number of signers. This was because in the last PR, we included secondary signers when the transaction payload is a `Script` but didn’t include secondary signers when the transaction payload is a `ScriptFunction`. This PR fixes that and updates the integration test. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes.

## Related PRs

#7427

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Review by tzakian — DISMISSED** [review]
Great catch! The changes look good to me, but it would be nice if you could add one more test to check the script-remapping case (see comment).

**Review by xli — APPROVED** [review]

**Review by xli — DISMISSED** [review]

**Pull request closed without merging**
