### PR TITLE
x: update nextest to fix performance regression

### PR DESCRIPTION
**Pull request by bmwill**

### CODE REVIEW

**Comment by libra-action** [comment]
## Dependency update review
### rayon-core updated: 1.9.0 --> 1.9.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>11</td></tr><tr><td>total rust files changed</td><td>8</td></tr><tr><td>total loc change</td><td>430</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` src/scope/mod.rs `
   * ` Cargo.toml `
   * ` src/scope/test.rs `
   * ` src/lib.rs `
   * ` src/util.rs `
   * ` src/registry.rs `
   * ` .cargo_vcs_info.json `
   * ` Cargo.toml.orig `
   * ` src/thread_pool/mod.rs `
   * ` src/thread_pool/test.rs `
   * ` src/latch.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/registry.rs `
   * ` src/scope/mod.rs `
   * ` src/thread_pool/mod.rs `
   * ` src/util.rs `
</details>
</details>

### rayon updated: 1.5.0 --> 1.5.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:x:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>26</td></tr><tr><td>total rust files changed</td><td>20</td></tr><tr><td>total loc change</td><td>880</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` src/array.rs `
   * ` build.rs `
   * ` src/iter/collect/mod.rs `
   * ` tests/clones.rs `
   * ` src/slice/test.rs `
   * ` tests/debug.rs `
   * ` .cargo_vcs_info.json `
   * ` src/iter/collect/consumer.rs `
   * ` Cargo.toml.orig `
   * ` RELEASES.md `
   * ` src/range_inclusive.rs `
   * ` FAQ.md `
   * ` src/slice/mergesort.rs `
   * ` src/slice/mod.rs `
   * ` Cargo.toml `
   * ` src/iter/collect/test.rs `
   * ` src/iter/mod.rs `
   * ` README.md `
   * ` src/iter/par_bridge.rs `
   * ` src/iter/unzip.rs `
   * ` src/lib.rs `
   * ` src/vec.rs `
   * ` src/range.rs `
   * ` src/slice/quicksort.rs `
   * ` tests/producer_split_at.rs `
   * ` tests/sort-panic-safe.rs `
</details><details>
	<summary>Click to show modified build scripts</summary><br>

   * ` build.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/array.rs `
   * ` src/iter/collect/consumer.rs `
   * ` src/iter/collect/mod.rs `
   * ` src/slice/mergesort.rs `
   * ` src/slice/quicksort.rs `
   * ` src/vec.rs `
</details>
</details>

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M rayon 1.5.1 (direct third-party, crates.io)
    * version upgraded from 1.5.0
    * (unchanged features: [none])
  M rayon-core 1.9.1 (transitive third-party, crates.io)
    * version upgraded from 1.9.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M rayon 1.5.1 (direct third-party, crates.io)
    * version upgraded from 1.5.0
    * (unchanged features: [none])
  M rayon-core 1.9.1 (transitive third-party, crates.io)
    * version upgraded from 1.9.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M rayon 1.5.1 (direct third-party, crates.io)
    * version upgraded from 1.5.0
    * (unchanged features: [none])
  M rayon-core 1.9.1 (transitive third-party, crates.io)
    * version upgraded from 1.9.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
## Dependency update review
### rayon-core updated: 1.9.0 --> 1.9.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>11</td></tr><tr><td>total rust files changed</td><td>8</td></tr><tr><td>total loc change</td><td>430</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` src/scope/mod.rs `
   * ` src/lib.rs `
   * ` src/thread_pool/mod.rs `
   * ` .cargo_vcs_info.json `
   * ` src/util.rs `
   * ` Cargo.toml `
   * ` src/latch.rs `
   * ` src/scope/test.rs `
   * ` Cargo.toml.orig `
   * ` src/registry.rs `
   * ` src/thread_pool/test.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/registry.rs `
   * ` src/scope/mod.rs `
   * ` src/thread_pool/mod.rs `
   * ` src/util.rs `
</details>
</details>

### rayon updated: 1.5.0 --> 1.5.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:x:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>26</td></tr><tr><td>total rust files changed</td><td>20</td></tr><tr><td>total loc change</td><td>880</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` Cargo.toml `
   * ` src/iter/collect/consumer.rs `
   * ` src/slice/test.rs `
   * ` .cargo_vcs_info.json `
   * ` tests/producer_split_at.rs `
   * ` tests/sort-panic-safe.rs `
   * ` src/iter/unzip.rs `
   * ` src/vec.rs `
   * ` src/range_inclusive.rs `
   * ` tests/clones.rs `
   * ` README.md `
   * ` src/slice/mergesort.rs `
   * ` tests/debug.rs `
   * ` src/lib.rs `
   * ` FAQ.md `
   * ` src/iter/par_bridge.rs `
   * ` build.rs `
   * ` src/iter/collect/mod.rs `
   * ` src/iter/collect/test.rs `
   * ` RELEASES.md `
   * ` src/iter/mod.rs `
   * ` src/range.rs `
   * ` Cargo.toml.orig `
   * ` src/slice/quicksort.rs `
   * ` src/slice/mod.rs `
   * ` src/array.rs `
</details><details>
	<summary>Click to show modified build scripts</summary><br>

   * ` build.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/array.rs `
   * ` src/iter/collect/consumer.rs `
   * ` src/iter/collect/mod.rs `
   * ` src/slice/mergesort.rs `
   * ` src/slice/quicksort.rs `
   * ` src/vec.rs `
</details>
</details>

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M rayon 1.5.1 (direct third-party, crates.io)
    * version upgraded from 1.5.0
    * (unchanged features: [none])
  M rayon-core 1.9.1 (transitive third-party, crates.io)
    * version upgraded from 1.9.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M rayon 1.5.1 (direct third-party, crates.io)
    * version upgraded from 1.5.0
    * (unchanged features: [none])
  M rayon-core 1.9.1 (transitive third-party, crates.io)
    * version upgraded from 1.9.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M rayon 1.5.1 (direct third-party, crates.io)
    * version upgraded from 1.5.0
    * (unchanged features: [none])
  M rayon-core 1.9.1 (transitive third-party, crates.io)
    * version upgraded from 1.9.0
    * (unchanged features: [none])
```

**Review by metajack — APPROVED** [review]

**Comment by libra-action** [comment]
## Dependency update review
### rayon updated: 1.5.0 --> 1.5.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:x:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>26</td></tr><tr><td>total rust files changed</td><td>20</td></tr><tr><td>total loc change</td><td>880</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` build.rs `
   * ` src/iter/collect/mod.rs `
   * ` src/iter/par_bridge.rs `
   * ` src/lib.rs `
   * ` src/iter/collect/consumer.rs `
   * ` src/range.rs `
   * ` src/slice/quicksort.rs `
   * ` src/vec.rs `
   * ` tests/sort-panic-safe.rs `
   * ` FAQ.md `
   * ` src/slice/mod.rs `
   * ` src/iter/unzip.rs `
   * ` tests/debug.rs `
   * ` Cargo.toml `
   * ` src/slice/mergesort.rs `
   * ` tests/producer_split_at.rs `
   * ` src/range_inclusive.rs `
   * ` src/slice/test.rs `
   * ` README.md `
   * ` src/iter/collect/test.rs `
   * ` src/iter/mod.rs `
   * ` RELEASES.md `
   * ` tests/clones.rs `
   * ` src/array.rs `
   * ` Cargo.toml.orig `
   * ` .cargo_vcs_info.json `
</details><details>
	<summary>Click to show modified build scripts</summary><br>

   * ` build.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/array.rs `
   * ` src/iter/collect/consumer.rs `
   * ` src/iter/collect/mod.rs `
   * ` src/slice/mergesort.rs `
   * ` src/slice/quicksort.rs `
   * ` src/vec.rs `
</details>
</details>

### rayon-core updated: 1.9.0 --> 1.9.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>11</td></tr><tr><td>total rust files changed</td><td>8</td></tr><tr><td>total loc change</td><td>430</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` src/scope/mod.rs `
   * ` src/registry.rs `
   * ` src/util.rs `
   * ` src/lib.rs `
   * ` .cargo_vcs_info.json `
   * ` Cargo.toml `
   * ` src/latch.rs `
   * ` src/scope/test.rs `
   * ` src/thread_pool/mod.rs `
   * ` Cargo.toml.orig `
   * ` src/thread_pool/test.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/registry.rs `
   * ` src/scope/mod.rs `
   * ` src/thread_pool/mod.rs `
   * ` src/util.rs `
</details>
</details>

**Pull request merged**
