### PR TITLE
[language] move transactional-test-generator and diem-transaction-benchmarks into diem/diem-move

### PR DESCRIPTION
**Pull request by vgao1996**
This moves the two mentioned crates into their new home.

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M transaction-builder-generator 0.1.0 (workspace, path 'diem-move/transaction-builder-generator')
    * source changed from path 'language/transaction-builder/generator'
    * (unchanged features: default)
```

**Review by modocache — APPROVED** [review]
Great! Thanks for catching all the references in the documentation as well 🙌

**Pull request closed without merging**
