### PR TITLE
[move-prover] executable spec (WIP)

### PR DESCRIPTION
**Pull request by mengxu-fb**
**STILL A WORK-IN-PROGRESS, NOT READY FOR REVIEW**

Directly interpreting the stackless bytecode is generally preferred over the effort in #8166, which convert spec languages into Move semantics. So, this PR tracks the progress on the stackless bytecode interpretation.

## Motivation

For CI and progress tracking. Will convert it to formal PR when in good shape.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

New test cases will be added, existing ones should not break.

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode-interpreter 0.1.0 (workspace, path 'language/move-prover/interpreter')
    * features: [none]
```

**Comment by bob-wilson** [comment]
@mengxu-fb Why did you close this? I assume it moved to a new PR. If so, can you mention that?

**Comment by mengxu-fb** [comment]
@bob-wilson My bad for not providing a description.

Yes, the PR is closed in favor of #8316 which has landed now.

This PR contains two major components
1. a type checker for the stackless bytecode (also used to guide my exploration on the semantics of each bytecode), and
2. a non-satisfactory interpreter for the bytecode

Both components are better re-written in #8316. The former is guarded by `cfg!(debug_assertions)` while the latter is much better engineered.

**Comment by bob-wilson** [comment]
Thanks! (I like to follow along on PRs and it's hard to keep track sometimes.)

**Pull request closed without merging**
