### PR TITLE
[move-prover] Reactivate CVC4 tests and document usage.

### PR DESCRIPTION
**Pull request by wrwg**
This reactivates a select set of cvc4 tests to be run locally (and after we add it, also nightly). This became possible after upgrading to the newest Boogie version which had the interaction issue with cvc4 fixed.

I have not really attempted to activate more tests for CVC4 in this PR, nor verified the existing ones, but only checked whether the previous fatal errors are gone.

This also adds a document at [doc/dev/cvcv4.md](https://github.com/wrwg/diem/blob/cvc4/language/move-prover/doc/dev/cvc4.md) which describes how to select cvc4 tests, extend them, and configure the prover to use different encodings and theories if cvc4 is active. There are some TODOs in this doc which we should fill out next. Specifically, we need to pass the unit tests before we can use the more interesting stuff in the Diem framework which provides rich data for benchmarks and is supported by the Move prover's benchmarking infra. This is all described in the doc.

## Motivation

CVC4 collaboration.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Reactivated older tests.

## Related PRs

NA

### CODE REVIEW

**Comment by wrwg** [comment]
@barrettcw

**Review by shazqadeer — APPROVED** [review]
Looks great.   Thanks for detailed documentation. It should be very helpful to the CVC4 team.

**Comment by shazqadeer** [comment]
@barrettcw :  

I fixed the CVC4 model parsing issues last weekend.  I must admit though I don't fully understand what is going on in the various code paths in Boogie for processing models returned by Z3 and CVC4.  It almost seemed like there are two separate model formats.   I believe you wrote some of that code a while ago.  Could you discuss sometime?

Also, it would be useful to run CVC4 on the entire Boogie test suite to get the lay of the land.  The Boogie test suite is a good representative for software verification benchmarks that use a good mix of theories and quantifiers.  I don't have the bandwidth to take this task on entirely by myself.  But I am happy to collaborate with somebody on the CVC4 side.

**Pull request merged**
