### PR TITLE
Cherry-pick PR #8910 into release-1.3: [deps] update hyper to fix two rustsecs

### PR DESCRIPTION
**Pull request by sausagee**
This is a cherry-pick of #8910. 

> 
> 
> ## Motivation
> 
> There are two new rustics in hyper 0.14.4: [RUSTSEC-2021-0079](https://rustsec.org/advisories/RUSTSEC-2021-0079), [RUSTSEC-2021-0078](https://rustsec.org/advisories/RUSTSEC-2021-0078).
> 
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
> 
> Yes
> 
> ## Test Plan
> 
> Existing tests

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M once_cell 1.8.0 (direct third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde 1.0.127 (direct third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default, derive, rc, serde_derive, std)
  M instant 0.1.10 (transitive third-party, crates.io)
    * version upgraded from 0.1.9
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * (unchanged features: default, std)
  M lock_api 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std)

host packages:
  M proc-macro2 1.0.28 (direct third-party, crates.io)
    * version upgraded from 1.0.27
    * (unchanged features: default, proc-macro)
  M syn 1.0.74 (direct third-party, crates.io)
    * version upgraded from 1.0.72
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
  M once_cell 1.8.0 (transitive third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde_derive 1.0.127 (transitive third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default)
  M unicode-xid 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M hyper 0.14.11 (direct third-party, crates.io)
    * version upgraded from 0.14.4
    * (unchanged features: client, default, full, h2, http1, http2, runtime, server, socket2, stream, tcp)
  M once_cell 1.8.0 (direct third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde 1.0.127 (direct third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default, derive, rc, serde_derive, std)
  M futures-channel 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-io 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: std)
  M futures-sink 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * removed features: once_cell
    * (unchanged features: alloc, std)
  M futures-util 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: alloc, async-await, async-await-macro, channel, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)
  M h2 0.3.3 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M hashbrown 0.11.2 (transitive third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: raw)
  M http 0.2.4 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M http-body 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M httparse 1.4.1 (transitive third-party, crates.io)
    * version upgraded from 1.3.5
    * (unchanged features: default, std)
  M httpdate 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.2
    * (unchanged features: [none])
  M indexmap 1.7.0 (transitive third-party, crates.io)
    * version upgraded from 1.6.2
    * (unchanged features: std)
  M instant 0.1.10 (transitive third-party, crates.io)
    * version upgraded from 0.1.9
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * removed features: align
    * (unchanged features: default, std)
  M lock_api 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std)
  M mio 0.7.13 (transitive third-party, crates.io)
    * version upgraded from 0.7.9
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M pin-project-lite 0.2.7 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M signal-hook-registry 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M slab 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * added features: default, std
    * (unchanged features: [none])
  M socket2 0.4.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.19
    * (unchanged features: [none])
  M tokio-util 0.6.7 (transitive third-party, crates.io)
    * version upgraded from 0.6.4
    * (unchanged features: codec, default)
  R pin-project 1.0.5 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  M proc-macro2 1.0.28 (direct third-party, crates.io)
    * version upgraded from 1.0.27
    * (unchanged features: default, proc-macro)
  M syn 1.0.74 (direct third-party, crates.io)
    * version upgraded from 1.0.72
    * removed features: visit-mut
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
  M futures-macro 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: [none])
  M once_cell 1.8.0 (transitive third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde_derive 1.0.127 (transitive third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default)
  M tokio-macros 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: [none])
  M unicode-xid 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: default)
  R pin-project-internal 1.0.5 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A hashbrown 0.11.2 (transitive third-party, crates.io)
    * features: raw
  M futures-util 0.3.16 (direct third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: alloc, async-await, async-await-macro, channel, default, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)
  M hyper 0.14.11 (direct third-party, crates.io)
    * version upgraded from 0.14.4
    * (unchanged features: client, default, full, h2, http1, http2, runtime, server, socket2, stream, tcp)
  M once_cell 1.8.0 (direct third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M pin-project 1.0.8 (direct third-party, crates.io)
    * version upgraded from 1.0.5
    * (unchanged features: [none])
  M serde 1.0.127 (direct third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M tokio-util 0.6.7 (direct third-party, crates.io)
    * version upgraded from 0.6.4
    * (unchanged features: codec, compat, default, futures-io, io)
  M futures-channel 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-io 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: default, std)
  M futures-sink 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * removed features: once_cell
    * (unchanged features: alloc, std)
  M h2 0.3.3 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M hashbrown 0.9.1 (transitive third-party, crates.io)
    * removed features: raw
    * (unchanged features: ahash, default, inline-more)
  M http 0.2.4 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M http-body 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M httparse 1.4.1 (transitive third-party, crates.io)
    * version upgraded from 1.3.5
    * (unchanged features: default, std)
  M httpdate 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.2
    * (unchanged features: [none])
  M indexmap 1.7.0 (transitive third-party, crates.io)
    * version upgraded from 1.6.2
    * (unchanged features: std)
  M instant 0.1.10 (transitive third-party, crates.io)
    * version upgraded from 0.1.9
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * removed features: align
    * (unchanged features: default, std)
  M lock_api 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std, use_std)
  M mio 0.7.13 (transitive third-party, crates.io)
    * version upgraded from 0.7.9
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M pin-project-lite 0.2.7 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M signal-hook-registry 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M slab 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * added features: default, std
    * (unchanged features: [none])
  M socket2 0.4.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.19
    * (unchanged features: [none])

host packages:
  M proc-macro2 1.0.28 (direct third-party, crates.io)
    * version upgraded from 1.0.27
    * (unchanged features: default, proc-macro)
  M syn 1.0.74 (direct third-party, crates.io)
    * version upgraded from 1.0.72
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M futures-macro 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * (unchanged features: default, std)
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std, use_std)
  M once_cell 1.8.0 (transitive third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M pin-project-internal 1.0.8 (transitive third-party, crates.io)
    * version upgraded from 1.0.5
    * (unchanged features: [none])
  M serde_derive 1.0.127 (transitive third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default)
  M tokio-macros 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: [none])
  M unicode-xid 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M once_cell 1.8.0 (direct third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde 1.0.127 (direct third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default, derive, rc, serde_derive, std)
  M instant 0.1.10 (transitive third-party, crates.io)
    * version upgraded from 0.1.9
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * (unchanged features: default, std)
  M lock_api 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std)

host packages:
  M proc-macro2 1.0.28 (direct third-party, crates.io)
    * version upgraded from 1.0.27
    * (unchanged features: default, proc-macro)
  M syn 1.0.74 (direct third-party, crates.io)
    * version upgraded from 1.0.72
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
  M once_cell 1.8.0 (transitive third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde_derive 1.0.127 (transitive third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default)
  M unicode-xid 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M hyper 0.14.11 (direct third-party, crates.io)
    * version upgraded from 0.14.4
    * (unchanged features: client, default, full, h2, http1, http2, runtime, server, socket2, stream, tcp)
  M once_cell 1.8.0 (direct third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde 1.0.127 (direct third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default, derive, rc, serde_derive, std)
  M futures-channel 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-io 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: std)
  M futures-sink 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * removed features: once_cell
    * (unchanged features: alloc, std)
  M futures-util 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: alloc, async-await, async-await-macro, channel, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)
  M h2 0.3.3 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M hashbrown 0.11.2 (transitive third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: raw)
  M http 0.2.4 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M http-body 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M httparse 1.4.1 (transitive third-party, crates.io)
    * version upgraded from 1.3.5
    * (unchanged features: default, std)
  M httpdate 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.2
    * (unchanged features: [none])
  M indexmap 1.7.0 (transitive third-party, crates.io)
    * version upgraded from 1.6.2
    * (unchanged features: std)
  M instant 0.1.10 (transitive third-party, crates.io)
    * version upgraded from 0.1.9
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * removed features: align
    * (unchanged features: default, std)
  M lock_api 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std)
  M mio 0.7.13 (transitive third-party, crates.io)
    * version upgraded from 0.7.9
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M pin-project-lite 0.2.7 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M signal-hook-registry 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M slab 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * added features: default, std
    * (unchanged features: [none])
  M socket2 0.4.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.19
    * (unchanged features: [none])
  M tokio-util 0.6.7 (transitive third-party, crates.io)
    * version upgraded from 0.6.4
    * (unchanged features: codec, default)
  R pin-project 1.0.5 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  M proc-macro2 1.0.28 (direct third-party, crates.io)
    * version upgraded from 1.0.27
    * (unchanged features: default, proc-macro)
  M syn 1.0.74 (direct third-party, crates.io)
    * version upgraded from 1.0.72
    * removed features: visit-mut
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
  M futures-macro 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: [none])
  M once_cell 1.8.0 (transitive third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M serde_derive 1.0.127 (transitive third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default)
  M tokio-macros 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: [none])
  M unicode-xid 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: default)
  R pin-project-internal 1.0.5 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A hashbrown 0.11.2 (transitive third-party, crates.io)
    * features: raw
  M futures-util 0.3.16 (direct third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: alloc, async-await, async-await-macro, channel, default, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)
  M hyper 0.14.11 (direct third-party, crates.io)
    * version upgraded from 0.14.4
    * (unchanged features: client, default, full, h2, http1, http2, runtime, server, socket2, stream, tcp)
  M once_cell 1.8.0 (direct third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M pin-project 1.0.8 (direct third-party, crates.io)
    * version upgraded from 1.0.5
    * (unchanged features: [none])
  M serde 1.0.127 (direct third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M tokio-util 0.6.7 (direct third-party, crates.io)
    * version upgraded from 0.6.4
    * (unchanged features: codec, compat, default, futures-io, io)
  M futures-channel 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-io 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: default, std)
  M futures-sink 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.13
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * removed features: once_cell
    * (unchanged features: alloc, std)
  M h2 0.3.3 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M hashbrown 0.9.1 (transitive third-party, crates.io)
    * removed features: raw
    * (unchanged features: ahash, default, inline-more)
  M http 0.2.4 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M http-body 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M httparse 1.4.1 (transitive third-party, crates.io)
    * version upgraded from 1.3.5
    * (unchanged features: default, std)
  M httpdate 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.2
    * (unchanged features: [none])
  M indexmap 1.7.0 (transitive third-party, crates.io)
    * version upgraded from 1.6.2
    * (unchanged features: std)
  M instant 0.1.10 (transitive third-party, crates.io)
    * version upgraded from 0.1.9
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * removed features: align
    * (unchanged features: default, std)
  M lock_api 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std, use_std)
  M mio 0.7.13 (transitive third-party, crates.io)
    * version upgraded from 0.7.9
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M pin-project-lite 0.2.7 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M signal-hook-registry 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M slab 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.2
    * added features: default, std
    * (unchanged features: [none])
  M socket2 0.4.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.19
    * (unchanged features: [none])

host packages:
  M proc-macro2 1.0.28 (direct third-party, crates.io)
    * version upgraded from 1.0.27
    * (unchanged features: default, proc-macro)
  M syn 1.0.74 (direct third-party, crates.io)
    * version upgraded from 1.0.72
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M futures-macro 0.3.16 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: [none])
  M libc 0.2.99 (transitive third-party, crates.io)
    * version upgraded from 0.2.89
    * (unchanged features: default, std)
  M memchr 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.4
    * (unchanged features: default, std, use_std)
  M once_cell 1.8.0 (transitive third-party, crates.io)
    * version upgraded from 1.7.2
    * (unchanged features: alloc, default, race, std)
  M pin-project-internal 1.0.8 (transitive third-party, crates.io)
    * version upgraded from 1.0.5
    * (unchanged features: [none])
  M serde_derive 1.0.127 (transitive third-party, crates.io)
    * version upgraded from 1.0.125
    * (unchanged features: default)
  M tokio-macros 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: [none])
  M unicode-xid 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: default)
```

**Review by wrwg — APPROVED** [review]

**Pull request merged**
