### PR TITLE
[language] move diem-framework to diem/diem-move

### PR DESCRIPTION
**Pull request by vgao1996**
This moves `diem-framework` and its sub-crates into `diem-move`.

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework 0.1.0 (workspace, path 'diem-move/diem-framework')
    * source changed from path 'language/diem-framework'
    * (unchanged features: default)
  M diem-framework-releases 0.1.0 (workspace, path 'diem-move/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/DPN/releases'
    * (unchanged features: [none])
  M framework-releases 0.1.0 (workspace, path 'diem-move/diem-framework/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M diem-framework 0.1.0 (workspace, path 'diem-move/diem-framework')
    * source changed from path 'language/diem-framework'
    * (unchanged features: default)
```

**Comment by vgao1996** [comment]
The failed non-rust-lint seems unrelated/flaky.

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M diem-framework 0.1.0 (workspace, path 'diem-move/diem-framework')
    * source changed from path 'language/diem-framework'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework 0.1.0 (workspace, path 'diem-move/diem-framework')
    * source changed from path 'language/diem-framework'
    * (unchanged features: default)
  M diem-framework-releases 0.1.0 (workspace, path 'diem-move/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/DPN/releases'
    * (unchanged features: [none])
  M framework-releases 0.1.0 (workspace, path 'diem-move/diem-framework/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Review by tnowacki — DISMISSED** [review]

**Comment by tzakian** [comment]
Just FYI, this conflicts with the changes in https://github.com/diem/diem/pull/9606 They're minor, but just wanted to give you a heads-up

**Review by tzakian — DISMISSED** [review]

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M diem-framework 0.1.0 (workspace, path 'diem-move/diem-framework')
    * source changed from path 'language/diem-framework'
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework 0.1.0 (workspace, path 'diem-move/diem-framework')
    * source changed from path 'language/diem-framework'
    * (unchanged features: default)
  M diem-framework-releases 0.1.0 (workspace, path 'diem-move/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/DPN/releases'
    * (unchanged features: [none])
  M framework-releases 0.1.0 (workspace, path 'diem-move/diem-framework/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Pull request closed without merging**
