### PR TITLE
[RUSTSEC-2021-0093][rel-1.4] crossbeam-deque 0.8.0 -> 0.8.1

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation
https://github.com/diem/diem/issues/9010
https://rustsec.org/advisories/RUSTSEC-2021-0093

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
y

## Test Plan

existing coverage

## Related PRs

(If this PR adds or changes functionality, please take some time to update or suggest changes to the docs at https://developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
dependency update

 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
existing tests

 * Why we must have it for V1 launch.
Vulnerability seems real.
 
 * What workarounds and alternative we have if we do not push the PR.
Wait for 1.5 roll.

### CODE REVIEW

**Comment by libra-action** [comment]
# :tada: This update fixes 1 known advisory

## Dependency update review
### crossbeam-deque updated: 0.8.0 --> 0.8.1
### :tada: This update fixes known advisories

   * [RUSTSEC-2021-0093](https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw)


<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>10</td></tr><tr><td>total rust files changed</td><td>5</td></tr><tr><td>total loc change</td><td>230</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` tests/lifo.rs `
   * ` .cargo_vcs_info.json `
   * ` Cargo.toml `
   * ` CHANGELOG.md `
   * ` src/lib.rs `
   * ` tests/injector.rs `
   * ` tests/fifo.rs `
   * ` README.md `
   * ` src/deque.rs `
   * ` Cargo.toml.orig `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/deque.rs `
</details>
</details>

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Review by sausagee — APPROVED** [review]
As discussed offline after reviewing the diff (P452304942), this pick is accepted.

**Comment by libra-action** [comment]
# :tada: This update fixes 1 known advisory

## Dependency update review
### crossbeam-deque updated: 0.8.0 --> 0.8.1
### :tada: This update fixes known advisories

   * [RUSTSEC-2021-0093](https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw)


<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>10</td></tr><tr><td>total rust files changed</td><td>5</td></tr><tr><td>total loc change</td><td>230</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` src/lib.rs `
   * ` CHANGELOG.md `
   * ` tests/fifo.rs `
   * ` tests/lifo.rs `
   * ` .cargo_vcs_info.json `
   * ` README.md `
   * ` src/deque.rs `
   * ` Cargo.toml `
   * ` tests/injector.rs `
   * ` Cargo.toml.orig `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/deque.rs `
</details>
</details>

**Pull request merged**
