### PR TITLE
[dep] bump generic-array to 0.12.4

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
This addresses RUSTSEC-2020-0146.

## Test Plan
cargo audit + CI

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M generic-array 0.12.4 (transitive third-party, crates.io) (other versions: 0.14.4)
    * version upgraded from 0.12.3
    * (unchanged features: [none])
```

**Review by rexhoffman — APPROVED** [review]

**Comment by rexhoffman** [comment]
It's probably time to land a 'cargo update' for all transitive deps.

**Pull request closed without merging**
