### PR TITLE
[diem-framework] Move DiemTransactionPublishingOption back to V1

### PR DESCRIPTION
**Pull request by tnowacki**
- Recompile DiemTransactionDiemTransactionPublishingOption to file format VERSION_1
- The current version of DiemTransactionPublishingOption was recompiled with the compiler. From commit 609c0b054eab1b04a3828f3d2e9de25cab121682 after #7493

## Motivation

- This allows more breaking changes to VERSION_2

## Test Plan

- Ran tests

### CODE REVIEW

**Review by mengxu-fb — APPROVED** [review]

**Comment by bob-wilson** [comment]
Wait a minute... I'm assuming this was intended to roll back #7556, right? Or at least the compiled .mv file? The only change I see here is to delete a .mv file. That's not what I would expect for a rollback.

**Comment by tnowacki** [comment]
I think github is just freaking out. Its not a roll back, its a recompilation of Sam's changes with an older compiler version.

When I do it locally, I get
```
tmn@tmn-mbp:diem/ (rebuild) $ git diff master         [17:17:19]
diff --git a/language/diem-framework/compiled/stdlib/028_DiemTransactionPublishingOption.mv b/language/diem-framework/compiled/stdlib/028_DiemTransactionPublishingOption.mv
index c0e0317e01..c9de5e8350 100644
Binary files a/language/diem-framework/compiled/stdlib/028_DiemTransactionPublishingOption.mv and b/language/diem-framework/compiled/stdlib/028_DiemTransactionPublishingOption.mv differ
```

Sometimes when I see it on GitHub it shows -8 bytes
Then sometimes it erroneously says I'm adding an empty file

**Comment by tnowacki** [comment]
Going to double check this before landing

**Comment by bob-wilson** [comment]
OK, I can imagine that GH may have issues showing diffs to binary files. Thanks for double checking, though

**Pull request merged**
