### PR TITLE
[sdk] use symbolic link for generated file

### PR DESCRIPTION
**Pull request by vgao1996**
This replaces stdlib.rs with a symbolic link pointing to the generated file in `diem-framework-releases`, allowing us to not have to update this manually after regeneration.

### CODE REVIEW

**Review by bmwill — APPROVED** [review]
/land

**Comment by davidiw** [comment]
This just came up for discussion. Would this make the SDK on main in compatible with our current released network. If not, how / why?

**Comment by vgao1996** [comment]
I'd phrased it this way: neither this nor #8028 (the PR that introduced diem-framework-releases) changes the SDK compatibility guarantee -- clients on main are compatible with our current released network if and only if there hasn't been incompatible changes to the diem-framework between main and the released branch. (And I don't believe we've made such incompatible changes.) cc @runtian-zhou

**Comment by davidiw** [comment]
@vgao1996 , I think what had happened before was the compiler had changed resulting in different compiled scripts that didn't match the allowlist on chain. So I think this was an unexpected, secondary issue.

**Comment by vgao1996** [comment]
@davidiw Not sure I'm following. Were you talking about a separate incident or the fact that this PR changes the content of the generated file? If it's the latter then it's because I changed one of the comments (Michael pointed this out in #8299). The actual code in the file remains unchanged.

**Pull request merged**
