### PR TITLE
[move] Lex source buffers in place

### PR DESCRIPTION
**Pull request by modocache**
As requested in #8850, this modifies the Move source language lexer in the same way as the IR lexer: rather than copy the source file into a string with its comments removed, skip over the comments and build comment maps while advancing the lexer.

### CODE REVIEW

**Review by tnowacki — COMMENTED** [review]
Any noticeable perf changes with this change?

**Review by bob-wilson — COMMENTED** [review]
This looks good to me, but I'll leave it to @tnowacki to approve.

**Comment by tnowacki** [comment]
Happy to land this, but would like to know the impact before doing so. Even something small like running `cargo x test` before and after and testing

**Comment by modocache** [comment]
Sorry I didn't get back to this sooner, I also like the idea of measuring. I built `cargo x build --bin move-build` with and without `--release`, then ran `rm -rf build && /usr/bin/time -v target/{debug,release}/move-build -a=Std=0x1 -a=DiemFramework=0x1 -a=DiemRoot=0xA550C18 -a=CurrencyInfo=0xA550C18 -a=TreasuryCompliance=0xB1E55ED -a=VMReserved=0x0 -- language/diem-framework/modules language/move-stdlib/modules`, on both the `main` branch and this one -- so that's 4 total configurations: main branch debug, main branch release, this branch debug, this branch release.

Here's the average of 10 runs in each of those 4 configurations:

```
# main branch debug
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.16
Maximum resident set size (kbytes): 42708

# this branch debug
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.10  => 4.6% improvement
Maximum resident set size (kbytes): 42388  => 0.75% improvement

# main branch release
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.11
Maximum resident set size (kbytes): 25592

# this branch release
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.105  => 5% improvement
Maximum resident set size (kbytes): 25456  => 0.53% improvement
```

So, a slight improvement in wall clock time and memory usage. I was expecting more of a memory win...? 🤷

**Comment by tnowacki** [comment]
I'm surprised the memory win isn't more, but good to see at a modest improvement overall! Thanks for the win!

**Review by tnowacki — DISMISSED** [review]

**Pull request closed without merging**
