### PR TITLE
[tf][aws] add aws terraform for validator

### PR DESCRIPTION
**Pull request by sherry-x**
## Motivation

Open source terraform files for deploy validator node in AWS

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Will try to validate through my local nodes

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Review by rustielin — DISMISSED** [review]
woohoo about time!! :shipit: 
Might be good to include the README as well, but LGTM

**Comment by sherry-x** [comment]
@rustielin Yeah, README will come later once I got the vault stuff out as well.

**Review by rustielin — DISMISSED** [review]

**Pull request merged**
