### PR TITLE
[move] Revert stdlib update for clients

### PR DESCRIPTION
**Pull request by tnowacki**
- Revert recompiling stdlib to unbreak clients working on master
- Partial revert of #7289
- Revert #7449

## Motivation

- Checking in the current compiled version shouldn't be necessary after fixing some tests
- We can recompile the stdlib without breaking clients after script-visibility changes

## Test Plan

- CI

### CODE REVIEW

**Comment by tnowacki** [comment]
Heres to hoping the tests were fixed fully @runtian-zhou :)

**Review by bob-wilson — APPROVED** [review]
This is good and will allow the clients to use the master branch with the current release. As long as the tests pass....

**Comment by tnowacki** [comment]
Over reverted one file. Need to unrevert language/tools/move-cli/tests/testsuite/print_stack_trace/args.exp

**Review by xli — APPROVED** [review]

**Pull request merged**
