### PR TITLE
[developers.diem.com] Do not manually copy READMEs to the developer site any longer

### PR DESCRIPTION
**Pull request by JoelMarcey**
## Motivation

With the new developer site, we do not need to copy GitHub READMEs any longer. Make associated fixes because of this removal.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

CI

## Related PRs

N/A

### CODE REVIEW

**Comment by JoelMarcey** [comment]
cc @oriooctopus

**Comment by JoelMarcey** [comment]
This is going to help #7087

**Review by rexhoffman — APPROVED** [review]
Seems fine.

**Pull request closed without merging**
