### PR TITLE
[safety rules] support retry on incorrect epoch

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

Previously we perform initialize on NotInitialized error in https://github.com/diem/diem/pull/5033
but there's edge case that IncorrectEpoch could result in the same pattern (unable to vote until next epoch).

This PR extends it to handle IncorrectEpoch as well (and has a small refactor to make code more readable).

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update or suggest changes to the docs at https://developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
seems good, but this is quirky -- how did SR /not/ get the update in the first place? These are synchronous, blocking exchanges?

**Comment by zekun000** [comment]
@davidiw checkout https://github.com/diem/partners/issues/936

**Comment by davidiw** [comment]
If initialize fails, it should have returned an error that likely would have resulted in either a retry from the node or it crashing gloriously. We should fix it that way, rather than this way, imo.

**Comment by zekun000** [comment]
```
        if let Err(error) = safety_rules.perform_initialize() {
            error!(
                epoch = epoch,
                error = error,
                "Unable to initialize safety rules.",
            );
        }
```
this is from `start_round_manager`, are you suggesting we change this to panic/retry here?

**Review by davidiw — DISMISSED** [review]
lgtm

the reason we don't crash is because we wanted to support two behaviors unrecoverable errors and recoverable errors or those that would allow the node to follow along via state sync in a potential consensus observer model. Distinguishing the two was a pain so we just figured the system would self-correct. Unfortunately -- this is a case that does not.

/land

**Comment by davidiw** [comment]
thanks Zekun and Josh for digging into this and Zekun for providing a resolution

**Review by aching — COMMENTED** [review]
Thanks so much @zekun000 for taking this on.  The code change looks pretty reasonable. 
 Should we add a test case to verify the new behavior for the IncorrectEpoch similar to the safety_rules_crash() that verifies this behavior?

**Comment by aching** [comment]
@davidiw, do you think it would be useful to panic on unrecoverable errors btw?  Should we put a follow up task for that?

**Comment by davidiw** [comment]
/land

@aching I think I would bundle this into byzantine / selective attacks on nodes, but if we don't have an issue, we should.

**Pull request merged**
