### PR TITLE
[ci] run unit-test job on PR open and land

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
Update the unit-test trigger so it runs when PR is open and when it lands.

## Test Plan
CI itiself

### CODE REVIEW

**Review by metajack — APPROVED** [review]

**Comment by rexhoffman** [comment]
Wow, missed this in https://github.com/diem/diem/commit/5294c3d09f58410a56d02ca882dcc84b970d1a32 -- let's see what the fallout looks like.

**Review by rexhoffman — APPROVED** [review]
yikes.   second time in a year I've done something like this.    makes me think "prepare" isn't so hot an option.    Or that we should at least keep all the decision making in the prepare job rather than distributing it like this.

**Comment by bmwill** [comment]
What's the rationale for this change? Don't we have 2 `unit-test` jobs, this one and then one uses sccache `unit-test-sccache`? I was under the impression that `unit-test` ran on PRs and `unit-test-sccache` ran on land and that these two jobs did the same thing (except the land job benefitted from sccache). Although i'm looking at the workflow file and unable to find the second job so maybe i'm misremembering or it was removed recently?

**Comment by sausagee** [comment]
Both jobs benefit from sccache.  The diff is that `unit-test-sccahe` updates the cache for future jobs.  

`unit-test-sccache` was originally part of the `ci-test` workflow when a PR lands.  Recently it was moved to the `ci-post-land` workflow after a PR lands (https://github.com/diem/diem/blob/a6a4d317cc57989b8e1e78768515803abc6d9486/.github/workflows/ci-post-land.yml#L57)

**Comment by sausagee** [comment]
#8965 also fixes the issue mentioned here and has landed.  

After we resolve the comments and discussion here, i will close this PR.

**Comment by rexhoffman** [comment]
@bmwill removed the unit-test-sccache because that's the only way that @metajack and I thought that the coverage job/tests could have been breaking in that 24 hr window before the last rust update landed on main, and fixed itself 3 days after with no apparent code change that could have effected the health of the CI system/build system.   At least none that Jack or I could find.   Given: https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#incremental-compilation-is-re-enabled-by-default, and that they had outstanding bugs, figured it was prudent to not let "auto" upgrade the sccache contents, and only let main/release branches do that.    This could have negative consequences for prs on older rust trying to use new rust code/sccache crates -- but should prevent most issues.   Boils down to not trusting rust's internal caching decisions at this point and limiting it's blast radius to just open PRs, not jobs in main/auto.

**Comment by sausagee** [comment]
comments resolved. closing this PR.

**Pull request closed without merging**
