### PR TITLE
[transactional-tests] More migrated tests

### PR DESCRIPTION
**Pull request by tnowacki**
- Migrated linker_tests/, method_decorators/, module_member_types/, modules/, mutate_tests/, and mutation/
- Most tests were bytecode verifier tests, with a few VM tests

## Motivation

- Nearly done migrating bytecode verifier/VM related IR tests to transactional tests! 

## Test Plan

- ran em

### CODE REVIEW

**Review by tzakian — APPROVED** [review]
Looks good to me!

**Review by modocache — DISMISSED** [review]
Restamp!

**Review by tzakian — DISMISSED** [review]

**Pull request closed without merging**
