### PR TITLE
[RFC][move stdlib] BCSSet module

### PR DESCRIPTION
**Pull request by sblackshear**
- Moved logic from nursery/Compare.move to the BCS stdlib module, and migrated comparison tests as well
- Introduced BCSSet module that leverages the comparison-by-BCS-serialization functionality to implement binary search.
- Added some basic tests for the Set module, though more tests + specs will be needed

This introduces an approach to sets in Move, an often-requested feature. This approach is slow (because any insertion or lookup requires serialization) and has some other drawbacks as well (e.g., ordering of `address` values may not be as expected), but it's a start.

A large open question with this approach is whether it's suitable for the prover. Nicely supported automated reasoning about sets is one of the major motivations for having explicit sets instead of sets-as-vectors, but the indirection of using BCS serialization for ordering is likely to raise challenges, particularly for types where serialization does not preserve the natural order.

An alternative (or additional) approach could be to introduce an `ord` ability that all Move ground types with a natural order (i.e., `bool`, `u8`, `u64`, `u128`, `address`, `vector<u8>`, perhaps more generally `vector<T: ord>`) have and no other types do. We could introduce a `compare` bytecode for these types and then restrict sets to values that implement `ord` (this may also be useful for restricting keys in the upcoming table feature). This would be less expressive than `BCSSet`, but it would be more efficient and easier to reason about.

### CODE REVIEW

**Comment by wrwg** [comment]
Can you please hold back with this until we had a chance to discuss in person. FWIW, I have a pending change for sets as well, but figured they make little sense until we have contains (predicate based)/filter/map (henceforth the macro/combinators proposal).

Also, anything based on BCS is not only poison for the prover, but also any other form of symbolic analysis.

Moreover, if we introduce sets or maps, we should not put the way how they are implemented into the name of the data structure. Move is not C++ or Rust. We already support universal equality on any, even generic values, which none of those languages do. We can have `Set` and `Map` based semantically on equality. Whether the implementation uses BCS or whatever is an implementation detail. I'm worried if we put `BCS` in the name we soon will expose functionality which only works if the impl is actually also based on `BCS`, which is an unnecessary detail, killing the ability for symbolic reasoning without any practical need. For the record, Solidity also has just "maps" and not "hash_map" or similar.

**Comment by sblackshear** [comment]
> Can you please hold back with this until we had a chance to discuss 

No worries, this is an RFC (and thank you for the C's, good start to the discussion!) But I thought it was important to get a concrete proposal out (even if flawed) since this feature has been requested/discussed many times without progress.

> FWIW, I have a pending change for sets as well

Looking forward to seeing it!

> predicate based)/filter/map (henceforth the macro/combinators proposal).

Supporting predicates for all of our collections seems essential. Since we have ideas on how to support these predicates for vectors and this set is backed by a vector, I don't see any barriers to supporting these operations for sets using the vector ones.

> Also, anything based on BCS is not only poison for the prover, but also any other form of symbolic analysis.

This is a challenge, as noted in the PR summary. FWIW, I think analyses (including the prover) could fairly easily be extended to reason about sets of types with a natural order (e.g., `u64`) or wrappers of those types, but reasoning about the BCS of arbitrary types seems harder-than-needed.

> Moreover, if we introduce sets or maps, we should not put the way how they are implemented into the name of the data structure... Whether the implementation uses BCS or whatever is an implementation detail.

The `BCS` in the name is intended to make programmers think about the ordering they are going to get if they iterate over the set. Because iteration is supported, the fact that it uses BCS is not an implementation detail.

> We can have Set and Map based semantically on equality

This is also a valid approach with its own pros and cons. My main concern with this is expressivity of iteration. If you want to put things in a set or map and iterate over them in order, you can't do that with the equality-based approach--the only iteration strategy you can support is iteration order. 

It probably makes sense to have both kinds of collections and ban iteration for equality-based collections (or be very careful to emphasize that you get insertion order rather than anything semantic).

There's also some interesting questions about efficiency--equality-based collections are likely much more efficient for smaller collection sizes, but once they get big enough the binary search of the BCS-based approach will buy you something. Worth nothing that all collections in Move code I've seen today are very small.


Also curious to hear your thoughts on the `ord`-based strategy mentioned in the PR summary vs equality-based collections.

**Comment by tnowacki** [comment]
> This is also a valid approach with its own pros and cons. My main concern with this is expressivity of iteration. If you want to put things in a set or map and iterate over them in order, you can't do that with the equality-based approach--the only iteration strategy you can support is iteration order.

Since we already have equality in the language, and don't have general ordering, I think it might be a bit easier to add insertion-ordered sets/maps as the first type for sets/maps.

I'm a bit skeptical around things like `ord` as it a gets a bit funky as you cannot define your own ordering. That somehow bothers me less than byte-based equality.

**Comment by wrwg** [comment]
> > This is also a valid approach with its own pros and cons. My main concern with this is expressivity of iteration. If you want to put things in a set or map and iterate over them in order, you can't do that with the equality-based approach--the only iteration strategy you can support is iteration order.
> 
> Since we already have equality in the language, and don't have general ordering, I think it might be a bit easier to add insertion-ordered sets/maps as the first type for sets/maps.
> 
> I'm a bit skeptical around things like `ord` as it a gets a bit funky as you cannot define your own ordering. That somehow bothers me less than byte-based equality.

Totally a fan of insertion order for this problem.

**Comment by wrwg** [comment]
> > > This is also a valid approach with its own pros and cons. My main concern with this is expressivity of iteration. If you want to put things in a set or map and iterate over them in order, you can't do that with the equality-based approach--the only iteration strategy you can support is iteration order.
> > 
> > 
> > Since we already have equality in the language, and don't have general ordering, I think it might be a bit easier to add insertion-ordered sets/maps as the first type for sets/maps.
> > I'm a bit skeptical around things like `ord` as it a gets a bit funky as you cannot define your own ordering. That somehow bothers me less than byte-based equality.
> 
> Totally a fan of insertion order for this problem.

To follow up on this, BCS based keying is for symbolic reasoning the end of the world. Ord is just a bit better, in that the world goes on but turns into an endless nightmare ;-) 

We already spent a lot of time into getting equality somehow working, as it is not natively supported for aggregate types in SMT solvers. With Ord the same set of problems we had with equality returns  scaled up by one order of magnitude. Because we need to reason about order of iteration, both BCS and Ord will disallow us to deal with the problem by using uninterpreted functions with axiomatized properties, as we do today with BCS and Hash. We would need to precisely model BCS/ord as it is done in the language.

Insertion order is the best way to go from symbolic reasoning (prover) perspective. I understand that it may cause some overhead, but Java's LinkedHashMap implementation e.g. shows that it can still be done efficiently (probably natively) using hashing for lookup and update.

In general I think we should consider sets/maps etc. to be relative small (tables are the large things) so the overhead should be OK.

**Pull request closed without merging**
