### PR TITLE
[datatest-stable] use version from crates.io

### PR DESCRIPTION
**Pull request by sunshowers**
datatest-stable is now at https://github.com/diem/diem-devtools and is
available on crates.io: https://crates.io/crates/datatest-stable

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M walkdir 2.3.2 (direct third-party, crates.io)
    * version upgraded from 2.3.1
    * (unchanged features: [none])
```

**Review by sausagee — COMMENTED** [review]
Can we leave out the walkdir version bump?  LGTM otherwise.

**Review by bmwill — APPROVED** [review]
/land

**Pull request merged**
