### PR TITLE
remove git test from Rust

### PR DESCRIPTION
**Pull request by davidiw**
* This should be part of the CI/CD
* This makes it (nearly) impossible to run an entire testsuite locally
  without unnecessary effort

### CODE REVIEW

**Comment by rexhoffman** [comment]
Running the full test suite locally?   If we have something in place to stop people from failing to check in Cargo.lock, or similar files then removing this seem completely appropriate to me.   Want to see that check fail a build before this gets merged in.

**Comment by davidiw** [comment]
> Running the full test suite locally? If we have something in place to stop people from failing to check in Cargo.lock, or similar files then removing this seem completely appropriate to me. Want to see that check fail a build before this gets merged in.

Glad we agree that this is unnecessary. Could you elaborate on what you had in mind for a specific test and how that relates to this?

**Comment by davidiw** [comment]
@rexhoffman testing with a Cargo.toml update to anyhow -- this should ideally be caught by our infra.

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M anyhow 1.0.37 (direct third-party, crates.io)
    * version upgraded from 1.0.36
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M anyhow 1.0.37 (direct third-party, crates.io)
    * version upgraded from 1.0.36
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M anyhow 1.0.37 (direct third-party, crates.io)
    * version upgraded from 1.0.36
    * (unchanged features: default, std)

host packages:
  M anyhow 1.0.37 (transitive third-party, crates.io)
    * version upgraded from 1.0.36
    * (unchanged features: default, std)
```

**Comment by davidiw** [comment]
Yes, this is a duplicate of this: https://github.com/diem/diem/blob/master/scripts/changed-files.sh
let's delete it :D

**Comment by davidiw** [comment]
https://app.circleci.com/pipelines/github/diem/diem/36769/workflows/c7c16933-fd86-4f7c-b2a2-c82df4fb3fb1/jobs/274160

**Review by rexhoffman — APPROVED** [review]

**Pull request closed without merging**
