### PR TITLE
[dev-setup.sh] work around for arch testing.

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Get dev-setup.sh tested again on arch

### Have you read the [Contributing Guidelines on pull requests]

Y

## Test Plan

CI

## Related PRs

None

### CODE REVIEW

**Review by sausagee — COMMENTED** [review]
The change looks fine. 

I have a question on what platform(s) we should be supporting besides the default debian.  Do we know if anyone depends on arch?

**Comment by rexhoffman** [comment]
I didn't add the arch support to the script, I simply put a test around.   Happy to kill it off if we decide we don't want to support development on arch, if we do, we should test the install though.

**Comment by rexhoffman** [comment]
Looks like the pacman support was added by Chunqi Li, but DavidIW let me know he uses arch.  Shrug.

**Review by sausagee — APPROVED** [review]

**Pull request closed without merging**
