### PR TITLE
Remove unnecessary abilities from Move stdlib and Diem framework 

### PR DESCRIPTION
**Pull request by tnowacki**
Recreating #7949 due to bugs in cluster tests

- Relaxed translation from AbilitySets to type parameter constraints in the move-model. The translation is still lossy
- Removed abilities from Option helpers
- Removed copy from Events
- Removed unnecessary abilities from various structs in the Diem framework

## Motivation

- Cleanup after #7854, which provided a very mechanical translation. Nothing in the framework really utilizes them as of yet, but they are at least trimmed down
- The prover still needs to utilize them, but the translation (while still lossy) shouldn't panic anymore

## Test Plan

- cargo test

### CODE REVIEW

**Review by tzakian — APPROVED** [review]
Hopefully this one will be able to land! 🤞

**Comment by zihaoccc** [comment]
```
Test runner setup time spent 546 secs
Compatibility test results for land_07a3b409 ==> land_cc84a38e (PR)
1. All instances running land_07a3b409, generating some traffic on network
2. First full node land_07a3b409 ==> land_cc84a38e, to validate new full node to old validator node traffic
3. First Validator node land_07a3b409 ==> land_cc84a38e, to validate storage compatibility
4. First batch validators (14) land_07a3b409 ==> land_cc84a38e, to test consensus and traffic between old full nodes and new validator node
5. First batch full nodes (14) land_07a3b409 ==> land_cc84a38e
6. Second batch validators (15) land_07a3b409 ==> land_cc84a38e, to upgrade rest of the validators
7. Second batch of full nodes (15) land_07a3b409 ==> land_cc84a38e, to finish the network upgrade, time spent 685 secs
all up : 917 TPS, 4954 ms latency, 5650 ms p99 latency, no expired txns, time spent 250 secs
```

**Pull request closed without merging**
