### PR TITLE
project url update

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

https://github.com/libra/libra -> https://github.com/diem/diem

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

CI

## Related PRs

None

### CODE REVIEW

**Review by sausagee — APPROVED** [review]

**Comment by JoelMarcey** [comment]
I am drafting a PR to update everything in `developers.libra.org`, if you want to leave those changes to me. This will include adding the updated website infra, etc. Basically a complete overhaul of that directory.

**Review by metajack — APPROVED** [review]

**Comment by rexhoffman** [comment]
/land removed all developers.libra.org changes, leaving for @JoelMarcey

**Pull request closed without merging**
