### PR TITLE
Bump .NET SDK from 5.0 to 6.0

### PR DESCRIPTION
**Pull request by modocache**
.NET 6.0 includes distribution binaries for macOS arm64, which would allow us to run the `dev_setup.sh` script on M1 macOS machines, in order for them to install Move's prover dependencies.

### CODE REVIEW

**Review by wrwg — APPROVED** [review]

**Comment by wrwg** [comment]
Just a note: changes in devsetup seem not to trigger the prover tests right now in CI. To manually test whether our .Net dependency boogie works, can you verify that (a) devsetup.sh -y works (b) cd language/move-prover; MVP_TEST_FEATURE=default cargo test.

**Comment by wrwg** [comment]
No idea why my comment closed this PR...

**Comment by modocache** [comment]
Thanks for the review! 👍 

> Just a note: changes in devsetup seem not to trigger the prover tests right now in CI. To manually test whether our .Net dependency boogie works, can you verify that (a) devsetup.sh -y works (b) cd language/move-prover; MVP_TEST_FEATURE=default cargo test.

Yeah, this surprised me! But before "publishing" this PR as open for review, I included a dummy commit that modified a comment in a .rs file in the move-prover crate. That ran all of the tests and they appeared to have passed.

That being said, I'll also run the tests locally now as per your suggestion. Also, I believe AWS is having some difficulties right now that are impacting our CI, so I may not land this until later.

**Comment by modocache** [comment]
I'm not certain, but the `curl` error looks unrelated to my change...? And it also seems like it could be due to some lingering AWS issue, so, I will give it another try.

**Pull request closed without merging**
