### PR TITLE
remove unused diem-trace crate

### PR DESCRIPTION
**Pull request by bmwill**
The diem-trace crate and its functionality doesn't seem to be used by anyone so lets remove ii

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R diem-trace 0.1.0 (workspace, path 'common/trace')
    * (old features: [none])
  R reqwest 0.11.2 (direct third-party, crates.io)
    * (old features: blocking, json, serde_json)
  R structopt 0.3.21 (direct third-party, crates.io)
    * (old features: default)
  R ansi_term 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R atty 0.2.14 (transitive third-party, crates.io)
    * (old features: [none])
  R clap 2.33.3 (transitive third-party, crates.io)
    * (old features: ansi_term, atty, color, default, strsim, suggestions, vec_map)
  R encoding_rs 0.8.28 (transitive third-party, crates.io)
    * (old features: [none])
  R mime 0.3.16 (transitive third-party, crates.io)
    * (old features: [none])
  R serde_urlencoded 0.7.0 (transitive third-party, crates.io)
    * (old features: [none])
  R strsim 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])
  R textwrap 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-width 0.1.8 (transitive third-party, crates.io)
    * (old features: default)
  R vec_map 0.8.2 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  R heck 0.3.2 (transitive third-party, crates.io)
    * (old features: [none])
  R proc-macro-error 1.0.4 (transitive third-party, crates.io)
    * (old features: default, syn, syn-error)
  R proc-macro-error-attr 1.0.4 (transitive third-party, crates.io)
    * (old features: [none])
  R structopt-derive 0.4.14 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-segmentation 1.7.1 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R diem-trace 0.1.0 (workspace, path 'common/trace')
    * (old features: [none])
```

**Comment by zihaoccc** [comment]
we do not use trace anymore? I remembered Andrey demoed once with trace stuff in CT

**Comment by bmwill** [comment]
@zihaoccc I haven't seen it used since that demo, roughly a year ago. At this point its just bitrotting

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R diem-trace 0.1.0 (workspace, path 'common/trace')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R diem-trace 0.1.0 (workspace, path 'common/trace')
    * (old features: [none])
  R reqwest 0.11.2 (direct third-party, crates.io)
    * (old features: blocking, json, serde_json)
  R structopt 0.3.21 (direct third-party, crates.io)
    * (old features: default)
  R ansi_term 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R atty 0.2.14 (transitive third-party, crates.io)
    * (old features: [none])
  R clap 2.33.3 (transitive third-party, crates.io)
    * (old features: ansi_term, atty, color, default, strsim, suggestions, vec_map)
  R encoding_rs 0.8.28 (transitive third-party, crates.io)
    * (old features: [none])
  R mime 0.3.16 (transitive third-party, crates.io)
    * (old features: [none])
  R serde_urlencoded 0.7.0 (transitive third-party, crates.io)
    * (old features: [none])
  R strsim 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])
  R textwrap 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-width 0.1.8 (transitive third-party, crates.io)
    * (old features: default)
  R vec_map 0.8.2 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  R heck 0.3.2 (transitive third-party, crates.io)
    * (old features: [none])
  R proc-macro-error 1.0.4 (transitive third-party, crates.io)
    * (old features: default, syn, syn-error)
  R proc-macro-error-attr 1.0.4 (transitive third-party, crates.io)
    * (old features: [none])
  R structopt-derive 0.4.14 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-segmentation 1.7.1 (transitive third-party, crates.io)
    * (old features: [none])
```

**Review by xli — APPROVED** [review]

**Pull request merged**
