### PR TITLE
[RFC][experiment] try splitting df modules into two folders

### PR DESCRIPTION
**Pull request by emmazzz**
This PR experiments with splitting Diem Framework modules into two folders. One of the folders is empty right now. Also, a new folder `experimental` is added under `language` to store experimental modules we write.

Folder structure before:
```
language
    └── diem-framework
       └── modules
          └── DiemAccount.move
          └── DiemSystem.move
          ...
```
Folder structure after:
```
language
    └── diem-framework
       └── modules
          └──common_modules
               └── DiemAccount.move
               └── DiemSystem.move
               ...
          └──DPN-modules (empty)
    └── experimental
       └── modules
          └──Resource.move
```

**UPDATE 9/16**:

Now the folder looks like this:
```
language
    └── diem-framework
       └── modules
          └──common-modules
               └── DiemAccount.move
               └── DiemSystem.move
               ...
          └──DPN-modules (empty)
          └──experimental-modules (empty)
```
**UPDATE 9/21**:
```
language
    └── diem-framework
       └── core
          └── modules (contains all DF modules now)
       └── DPN
          └── modules (empty for now)
          └── releases
       └── experimental (contains NFT modules)
          └── modules
          └── releases
       └── src
          └── main.rs
          └── lib.rs
```

### CODE REVIEW

**Comment by dmitri-perelman** [comment]
Are you planning to call the specific modules directories "DPN" and "experimental"?
Looks great, but I don't know what dependencies you have on the existing directory structure, so I don't know whether it breaks anything :)

**Comment by emmazzz** [comment]
> Are you planning to call the specific modules directories "DPN" and "experimental"?

Right. The specific modules in `diem-framework` are DPN-specific so it should be called `DPN`. `experimental` should live somewhere else outside of diem-framework folder right? I'm assuming `experimental` contains new experimental modules we will write.

> Looks great, but I don't know what dependencies you have on the existing directory structure, so I don't know whether it breaks anything :)

This shouldn't break anything but I could be wrong. We'll see from the CI test results :)

**Comment by sherry-x** [comment]
If eventually `diem-framework` folder will be the basic/common modules (is it?), and `DPN` folder contains DPN specific modules, I wonder why DPN is under the `diem-framework` folder, not a separate folder under language like `experimental`? like:

```
language
    └── diem-framework
       └── modules
           └── DiemAccount.move
           └── DiemSystem.move
               ...
    └── experimental
       └── modules
          └──Resource.move
    └── DPN (empty)
```
I realize this means nothing would change so I'm probably getting something wrong lol

**Comment by emmazzz** [comment]
> If eventually `diem-framework` folder will be the basic/common modules (is it?), and `DPN` folder contains DPN specific modules, I wonder why DPN is under the `diem-framework` folder, not a separate folder under language like `experimental`? like:
> 
> ```
> language
>     └── diem-framework
>        └── modules
>            └── DiemAccount.move
>            └── DiemSystem.move
>                ...
>     └── experimental
>        └── modules
>           └──Resource.move
>     └── DPN (empty)
> ```
> 
> I realize this means nothing would change so I'm probably getting something wrong lol

What you have described is actually the slightly harder approach. It's slightly harder because with DPN folder outside of diem-framework folder, we'll have to add the path to DPN folder to a few different places so the compilation/auto-generation also take in modules in DPN folder. But yes I agree this is the correct(er) approach. Will work on it.

**Comment by sherry-x** [comment]
> It's slightly harder because with DPN folder outside of diem-framework folder, we'll have to add the path to DPN folder to a few different places so the compilation/auto-generation also take in modules in DPN folder.

we'd have to solve same problem for the experimental module folder anyway, right? if experimental need to use the common modules (I assume there would be some overlap modules), we need a way to add the path to both folder so that compilation would take in both. so I guess when we make this available to DPN, it needs to be configurable so that people can choose which path to include.

**Comment by bob-wilson** [comment]
> What you have described is actually the slightly harder approach. It's slightly harder because with DPN folder outside of diem-framework folder, we'll have to add the path to DPN folder to a few different places so the compilation/auto-generation also take in modules in DPN folder. But yes I agree this is the correct(er) approach. Will work on it.

I'm not convinced that is a better approach. There's a lot of other stuff underneath the "language" directory, so I think it's valuable to group all the framework Move modules into a single directory. I would probably just keep the current "diem-framework" name for that top-level framework directory, but I suppose we could also rename it to just "framework" to emphasize that it includes things that are not specific to DPN.

My feedback is to suggest putting a new "experimental-modules" directory as a peer of "common-modules" and "DPN-modules" (and also be consistent about either hyphens or underscores as a separator before "modules"). Or do you expect the new "experimental" directory to contain other things besides Move modules?

**Comment by emmazzz** [comment]
> My feedback is to suggest putting a new "experimental-modules" directory as a peer of "common-modules" and "DPN-modules" (and also be consistent about either hyphens or underscores as a separator before "modules"). Or do you expect the new "experimental" directory to contain other things besides Move modules?

We don't expect to have anything besides Move modules in experimental folder. I have updated the PR and now `experimenta-modules` is a peer of "common-modules" and "DPN-modules" .

**Comment by sherry-x** [comment]
Do we need to update the path here? https://github.com/diem/diem/tree/main/language/diem-framework/releases/artifacts/current/modules

**Comment by emmazzz** [comment]
> Do we need to update the path here? https://github.com/diem/diem/tree/main/language/diem-framework/releases/artifacts/current/modules

You have brought up a good point. Currently `diem-framework/releases/` contains releases of DPN framework. And running `cargo run` inside `diem-framework` compiles all the DPN modules. Maybe we should have peer folders for other frameworks too. What do you think of something like this:
```
language
    └── frameworks
       └── modules
          └──common-modules
          └──DPN-modules
          └──experimental-modules
       └── DPN-releases
          └──artifacts
       └── experimental-releases 
          └──artifacts
```

**Comment by sherry-x** [comment]
The proposal of the release folder structure looks good to me!

**Comment by vgao1996** [comment]
@tnowacki @tzakian I think we should have a further discussion on the crate structure, especially how that'll work with the Move package system. It worries me a little bit that we're trying to convert the original "diem-framework" package into some sort of "super package" that spans across multiple networks. I wonder if it would be a better idea to split them into different crates/Move packages.

**Comment by vgao1996** [comment]
> I wonder if it would be a better idea to split them into different crates/Move packages.

By this I mean something like the following:
```
language
    └── diem-framework
        └── releases
    └── diem-framework-experimental
        └── releases
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN-releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by emmazzz** [comment]
> > I wonder if it would be a better idea to split them into different crates/Move packages.
> 
> By this I mean something like the following:
> 
> ```
> language
>     └── diem-framework
>         └── releases
>     └── diem-framework-experimental
>         └── releases
>     └── diem-framework-some-optional-feature-extensions
>         └── releases
> ```
> 
> Hmm.. wait, it seems like this is exactly what you proposed originally?

I have updated the PR and now the folder structure looks like this:

```
language
    └── diem-framework
       └── modules
          └── common-modules
          └── DPN-modules
          └── experimental-modules
       └── DPN-releases
          └── artifacts
       └── experimental-releases 
          └── artifacts
       └── src
          └── main.rs
          └── lib.rs
```
This is slightly different from what you have laid out @vgao1996. In your folder structure diagram, all the frameworks are peer folders under language folder. I actually think it's a cleaner approach. On the other hand though, @bob-wilson brought up the valid point that all the framework Move modules should stay together. Maybe we should have a discussion about this.

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN-releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN-releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN-releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Comment by dmitri-perelman** [comment]
> It would be great if we can add an example move module for experimental so that we can compile something in the experimental release artifact, but this can be in another PR too since this one is already so big :D

This PR already includes NFT and GUID modules for experimental! :)
What are the next steps? Are we good to land it now?

**Comment by dmitri-perelman** [comment]
> It would be great if we can add an example move module for experimental so that we can compile something in the experimental release artifact, but this can be in another PR too since this one is already so big :D

This PR already includes NFT and GUID modules for experimental! :)
What are the next steps? Are we good to land it now?

**Comment by emmazzz** [comment]
> > It would be great if we can add an example move module for experimental so that we can compile something in the experimental release artifact, but this can be in another PR too since this one is already so big :D
> 
> This PR already includes NFT and GUID modules for experimental! :)
> What are the next steps? Are we good to land it now?

We'll be good to land it today. I'm in the middle of landing another PR right now, which will create some conflicts for this one.

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/DPN/releases')
    * source changed from path 'language/diem-framework/releases'
    * (unchanged features: [none])
```

**Review by sherry-x — DISMISSED** [review]
Amazing!

**Pull request merged**
