### PR TITLE
[move-symbol-pool] Minor improvements

### PR DESCRIPTION
**Pull request by tnowacki**
- Added str deref
- Added Cow optimization for owned strings
- Fixed ser/de

## Motivation

- deref improves the usability of symbols, with things like `sym.starts_with('_')` now being possible without an explicit `as_str()`
- `Cow` removes a useless clone in the `String`/`owned` case 
- ser/de was incorrect 

## Test Plan

- Ran tests

### CODE REVIEW

**Comment by modocache** [comment]
Nice -- quick drive-by comment but I have these serde changes plus a small test in #8853, in case you hadn't seen that!

**Comment by tnowacki** [comment]
> Nice -- quick drive-by comment but I have these serde changes plus a small test in #8853, in case you hadn't seen that!

Haha, yup just saw that. Went to land #8853 if you don't mind :)

**Review by modocache — DISMISSED** [review]
Awesome! Thanks for listing out what each change improves in the motivation section, too, that helped me understand this 👍

**Review by tzakian — APPROVED** [review]

**Pull request merged**
