### PR TITLE
Externalize CLI, nits

### PR DESCRIPTION
**Pull request by oriooctopus**
## Motivation

-Updates Social Share image
-Externalizes CLI
-nits

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
```

**Comment by JoelMarcey** [comment]
I want to rerun the failing checks first to see if we can get them to pass before approving and landing.

**Comment by JoelMarcey** [comment]
@ericnakagawa @bmwill -- are you able to add me as a reviewer to this PR? @xli was unable to. Do either of you know why?

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by JoelMarcey** [comment]
It looks like if I removed the other reviewers, I was able to add myself as a reviewer.

**Review by JoelMarcey — APPROVED** [review]

**Comment by JoelMarcey** [comment]
I am going to try to land this, but I am not sure it will pass if the checks don't.

**Comment by JoelMarcey** [comment]
@oriooctopus Looks like you may need to rebase this.

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A proxy 0.1.0 (workspace, path 'common/proxy')
    * features: [none]
  A ipnet 2.3.0 (direct third-party, crates.io)
    * features: [none]
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M anyhow 1.0.37 (direct third-party, crates.io)
    * version upgraded from 1.0.34
    * (unchanged features: default, std)
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M erased-serde 0.3.13 (direct third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: default, std)
  M itertools 0.10.0 (direct third-party, crates.io)
    * version upgraded from 0.9.0
    * added features: use_alloc
    * (unchanged features: default, use_std)
  M native-tls 0.2.7 (direct third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M ref-cast 1.0.6 (direct third-party, crates.io)
    * version upgraded from 1.0.3
    * (unchanged features: [none])
  M serde_json 1.0.61 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: default, std)
  M serde_yaml 0.8.15 (direct third-party, crates.io)
    * version upgraded from 0.8.14
    * (unchanged features: [none])
  M thiserror 1.0.23 (direct third-party, crates.io)
    * version upgraded from 1.0.22
    * (unchanged features: [none])
  M toml 0.5.8 (direct third-party, crates.io)
    * version upgraded from 0.5.7
    * (unchanged features: default)
  M addr2line 0.14.1 (transitive third-party, crates.io)
    * version upgraded from 0.14.0
    * (unchanged features: [none])
  M dtoa 0.4.7 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])
  M ghash 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M itoa 0.4.7 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])
  M openssl 0.10.32 (transitive third-party, crates.io)
    * version upgraded from 0.10.30
    * (unchanged features: [none])
  M openssl-sys 0.9.60 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M parking_lot_core 0.8.2 (transitive third-party, crates.io)
    * version upgraded from 0.8.1
    * (unchanged features: [none])
  M polyval 0.4.5 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * added features: mulx
    * (unchanged features: [none])
  M smallvec 1.6.0 (transitive third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: [none])
  M subtle 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.0
    * (unchanged features: std)
  M yaml-rust 0.4.5 (transitive third-party, crates.io)
    * version upgraded from 0.4.4
    * (unchanged features: [none])
  M zeroize 1.2.0 (transitive third-party, crates.io)
    * version upgraded from 1.1.1
    * (unchanged features: alloc, zeroize_derive)

host packages:
  M enum_dispatch 0.3.5 (direct third-party, crates.io)
    * version upgraded from 0.3.4
    * (unchanged features: [none])
  M quote 1.0.8 (direct third-party, crates.io)
    * version upgraded from 1.0.7
    * (unchanged features: default, proc-macro)
  M syn 1.0.57 (direct third-party, crates.io)
    * version upgraded from 1.0.53
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
  M ref-cast-impl 1.0.6 (transitive third-party, crates.io)
    * version upgraded from 1.0.3
    * (unchanged features: [none])
  M thiserror-impl 1.0.23 (transitive third-party, crates.io)
    * version upgraded from 1.0.22
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A proxy 0.1.0 (workspace, path 'common/proxy')
    * features: [none]
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M anyhow 1.0.37 (direct third-party, crates.io)
    * version upgraded from 1.0.34
    * (unchanged features: default, std)
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M erased-serde 0.3.13 (direct third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: default, std)
  M ipnet 2.3.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M itertools 0.10.0 (direct third-party, crates.io)
    * version upgraded from 0.9.0
    * added features: use_alloc
    * (unchanged features: default, use_std)
  M native-tls 0.2.7 (direct third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M ref-cast 1.0.6 (direct third-party, crates.io)
    * version upgraded from 1.0.3
    * (unchanged features: [none])
  M reqwest 0.10.10 (direct third-party, crates.io)
    * version upgraded from 0.10.9
    * (unchanged features: blocking, json, serde_json)
  M serde_json 1.0.61 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: default, std)
  M serde_yaml 0.8.15 (direct third-party, crates.io)
    * version upgraded from 0.8.14
    * (unchanged features: [none])
  M thiserror 1.0.23 (direct third-party, crates.io)
    * version upgraded from 1.0.22
    * (unchanged features: [none])
  M tokio 0.2.24 (direct third-party, crates.io)
    * version upgraded from 0.2.22
    * (unchanged features: blocking, default, dns, fnv, fs, full, futures-core, io-driver, io-std, io-util, iovec, lazy_static, libc, macros, memchr, mio, mio-named-pipes, mio-uds, net, num_cpus, process, rt-core, rt-threaded, rt-util, signal, signal-hook-registry, slab, stream, sync, tcp, time, tokio-macros, udp, uds, winapi)
  M addr2line 0.14.1 (transitive third-party, crates.io)
    * version upgraded from 0.14.0
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M dtoa 0.4.7 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])
  M ghash 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M http 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: [none])
  M indexmap 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M itoa 0.4.7 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: default, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl 0.10.32 (transitive third-party, crates.io)
    * version upgraded from 0.10.30
    * (unchanged features: [none])
  M openssl-sys 0.9.60 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M parking_lot_core 0.8.2 (transitive third-party, crates.io)
    * version upgraded from 0.8.1
    * (unchanged features: [none])
  M pin-project 1.0.3 (transitive third-party, crates.io) (other versions: 0.4.27)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M polyval 0.4.5 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * added features: mulx
    * (unchanged features: [none])
  M signal-hook-registry 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.2.2
    * (unchanged features: [none])
  M smallvec 1.6.0 (transitive third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: [none])
  M socket2 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
  M subtle 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.0
    * (unchanged features: std)
  M yaml-rust 0.4.5 (transitive third-party, crates.io)
    * version upgraded from 0.4.4
    * (unchanged features: [none])
  M zeroize 1.2.0 (transitive third-party, crates.io)
    * version upgraded from 1.1.1
    * (unchanged features: alloc, zeroize_derive)

host packages:
  M enum_dispatch 0.3.5 (direct third-party, crates.io)
    * version upgraded from 0.3.4
    * (unchanged features: [none])
  M quote 1.0.8 (direct third-party, crates.io)
    * version upgraded from 1.0.7
    * (unchanged features: default, proc-macro)
  M syn 1.0.57 (direct third-party, crates.io)
    * version upgraded from 1.0.53
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M heck 0.3.2 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M pin-project-internal 1.0.3 (transitive third-party, crates.io) (other versions: 0.4.27)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M ref-cast-impl 1.0.6 (transitive third-party, crates.io)
    * version upgraded from 1.0.3
    * (unchanged features: [none])
  M thiserror-impl 1.0.23 (transitive third-party, crates.io)
    * version upgraded from 1.0.22
    * (unchanged features: [none])
  M tokio-macros 0.2.6 (transitive third-party, crates.io)
    * version upgraded from 0.2.5
    * (unchanged features: [none])
  M unicode-segmentation 1.7.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-model 0.1.0 (workspace, path 'language/move-model')
    * features: [none]
  A proxy 0.1.0 (workspace, path 'common/proxy')
    * features: [none]
  A textwrap 0.13.2 (direct third-party, crates.io) (other versions: 0.11.0)
    * features: default, smawk, unicode-width
  A bytes 1.0.0 (transitive third-party, crates.io) (other versions: 0.5.6)
    * features: [none]
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  A smawk 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  M anyhow 1.0.37 (direct third-party, crates.io)
    * version upgraded from 1.0.34
    * (unchanged features: default, std)
  M arc-swap 1.2.0 (direct third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M erased-serde 0.3.13 (direct third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: default, std)
  M handlebars 3.5.2 (direct third-party, crates.io)
    * version upgraded from 3.5.1
    * (unchanged features: default)
  M heck 0.3.2 (direct third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M ipnet 2.3.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M itertools 0.10.0 (direct third-party, crates.io)
    * version upgraded from 0.9.0
    * added features: use_alloc
    * (unchanged features: default, use_std)
  M native-tls 0.2.7 (direct third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M pin-project 1.0.3 (direct third-party, crates.io) (other versions: 0.4.27)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M prost 0.7.0 (direct third-party, crates.io)
    * version upgraded from 0.6.1
    * added features: std
    * (unchanged features: default, prost-derive)
  M ref-cast 1.0.6 (direct third-party, crates.io)
    * version upgraded from 1.0.3
    * (unchanged features: [none])
  M reqwest 0.10.10 (direct third-party, crates.io)
    * version upgraded from 0.10.9
    * (unchanged features: blocking, json, serde_json, stream)
  M serde_json 1.0.61 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: default, std)
  M serde_yaml 0.8.15 (direct third-party, crates.io)
    * version upgraded from 0.8.14
    * (unchanged features: [none])
  M simplelog 0.9.0 (direct third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: default, termcolor)
  M thiserror 1.0.23 (direct third-party, crates.io)
    * version upgraded from 1.0.22
    * (unchanged features: [none])
  M tokio 0.2.24 (direct third-party, crates.io)
    * version upgraded from 0.2.22
    * (unchanged features: blocking, default, dns, fnv, fs, full, futures-core, io-driver, io-std, io-util, iovec, lazy_static, libc, macros, memchr, mio, mio-named-pipes, mio-uds, net, num_cpus, process, rt-core, rt-threaded, rt-util, signal, signal-hook-registry, slab, stream, sync, tcp, time, tokio-macros, udp, uds, winapi)
  M toml 0.5.8 (direct third-party, crates.io)
    * version upgraded from 0.5.7
    * (unchanged features: default)
  M addr2line 0.14.1 (transitive third-party, crates.io)
    * version upgraded from 0.14.0
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M dtoa 0.4.7 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: [none])
  M ghash 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M http 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.1
    * (unchanged features: [none])
  M indexmap 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M itoa 0.4.7 (transitive third-party, crates.io)
    * version upgraded from 0.4.6
    * (unchanged features: default, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl 0.10.32 (transitive third-party, crates.io)
    * version upgraded from 0.10.30
    * (unchanged features: [none])
  M openssl-sys 0.9.60 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M parking_lot_core 0.8.2 (transitive third-party, crates.io)
    * version upgraded from 0.8.1
    * (unchanged features: [none])
  M polyval 0.4.5 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * added features: mulx
    * (unchanged features: [none])
  M signal-hook-registry 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.2.2
    * (unchanged features: [none])
  M smallvec 1.6.0 (transitive third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: [none])
  M socket2 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
  M subtle 2.4.0 (transitive third-party, crates.io)
    * version upgraded from 2.3.0
    * (unchanged features: std)
  M textwrap 0.12.1 (transitive third-party, crates.io) (other versions: 0.11.0)
    * status changed from direct third-party
    * (unchanged features: [none])
  M unicode-segmentation 1.7.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M yaml-rust 0.4.5 (transitive third-party, crates.io)
    * version upgraded from 0.4.4
    * (unchanged features: [none])
  M zeroize 1.2.0 (transitive third-party, crates.io)
    * version upgraded from 1.1.1
    * (unchanged features: alloc, zeroize_derive)
  R spec-lang 0.1.0 (workspace, path 'language/move-prover/spec-lang')
    * (old features: [none])

host packages:
  A thiserror 1.0.23 (transitive third-party, crates.io)
    * features: [none]
  A which 4.0.2 (transitive third-party, crates.io) (other versions: 3.1.1)
    * features: [none]
  M enum_dispatch 0.3.5 (direct third-party, crates.io)
    * version upgraded from 0.3.4
    * (unchanged features: [none])
  M prost-build 0.7.0 (direct third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: [none])
  M quote 1.0.8 (direct third-party, crates.io)
    * version upgraded from 1.0.7
    * (unchanged features: default, proc-macro)
  M syn 1.0.57 (direct third-party, crates.io)
    * version upgraded from 1.0.53
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M anyhow 1.0.37 (transitive third-party, crates.io)
    * version upgraded from 1.0.34
    * (unchanged features: default, std)
  M bytes 1.0.0 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * removed features: default, std
    * (unchanged features: [none])
  M heck 0.3.2 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M indexmap 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M itertools 0.9.0 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: default, use_std)
  M pin-project-internal 1.0.3 (transitive third-party, crates.io) (other versions: 0.4.27)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M prost 0.7.0 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * removed features: default
    * (unchanged features: prost-derive)
  M prost-derive 0.7.0 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: [none])
  M prost-types 0.7.0 (transitive third-party, crates.io)
    * version upgraded from 0.6.1
    * (unchanged features: [none])
  M ref-cast-impl 1.0.6 (transitive third-party, crates.io)
    * version upgraded from 1.0.3
    * (unchanged features: [none])
  M thiserror-impl 1.0.23 (transitive third-party, crates.io)
    * version upgraded from 1.0.22
    * (unchanged features: [none])
  M tokio-macros 0.2.6 (transitive third-party, crates.io)
    * version upgraded from 0.2.5
    * (unchanged features: [none])
  M unicode-segmentation 1.7.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
```

**Review by JoelMarcey — APPROVED** [review]

**Review by JoelMarcey — APPROVED** [review]

**Pull request closed without merging**
