### PR TITLE
Updating this branch with latest changes in main

### PR DESCRIPTION
**Pull request by nimishamw**
Updating docs branch with latest changes in main to allow for future doc updates

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A rayon 1.5.0 (direct third-party, crates.io)
    * features: [none]
  A crossbeam-channel 0.5.1 (transitive third-party, crates.io)
    * features: crossbeam-utils, default, std
  A crossbeam-deque 0.8.0 (transitive third-party, crates.io)
    * features: crossbeam-epoch, crossbeam-utils, default, std
  A crossbeam-epoch 0.9.3 (transitive third-party, crates.io)
    * features: alloc, lazy_static, std
  A crossbeam-utils 0.8.3 (transitive third-party, crates.io)
    * features: default, lazy_static, std
  A memoffset 0.6.1 (transitive third-party, crates.io)
    * features: default
  A num_cpus 1.13.0 (transitive third-party, crates.io)
    * features: [none]
  A rayon-core 1.9.0 (transitive third-party, crates.io)
    * features: [none]
  M scratchpad 0.1.0 (workspace, path 'storage/scratchpad')
    * removed features: default
    * (unchanged features: [none])
  M anyhow 1.0.40 (direct third-party, crates.io)
    * version upgraded from 1.0.39
    * (unchanged features: default, std)
  M serde 1.0.125 (direct third-party, crates.io)
    * version upgraded from 1.0.124
    * (unchanged features: default, derive, rc, serde_derive, std)

host packages:
  M serde_derive 1.0.125 (transitive third-party, crates.io)
    * version upgraded from 1.0.124
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A disassembler 0.1.0 (workspace, path 'language/tools/disassembler')
    * features: default
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  A move-coverage 0.1.0 (workspace, path 'language/tools/move-coverage')
    * features: default
  A colored 2.0.0 (direct third-party, crates.io)
    * features: [none]
  A tera 1.7.1 (direct third-party, crates.io)
    * features: builtins, chrono, chrono-tz, default, humansize, percent-encoding, rand, slug, unic-segment
  A bstr 0.2.15 (transitive third-party, crates.io)
    * features: std
  A chrono-tz 0.5.3 (transitive third-party, crates.io)
    * features: default, std
  A deunicode 0.4.3 (transitive third-party, crates.io)
    * features: [none]
  A globset 0.4.6 (transitive third-party, crates.io)
    * features: [none]
  A globwalk 0.8.1 (transitive third-party, crates.io)
    * features: [none]
  A humansize 1.1.0 (transitive third-party, crates.io)
    * features: [none]
  A ignore 0.4.17 (transitive third-party, crates.io)
    * features: [none]
  A slug 0.1.4 (transitive third-party, crates.io)
    * features: [none]
  A unic-char-property 0.9.0 (transitive third-party, crates.io)
    * features: [none]
  A unic-char-range 0.9.0 (transitive third-party, crates.io)
    * features: default
  A unic-common 0.9.0 (transitive third-party, crates.io)
    * features: default
  A unic-segment 0.9.0 (transitive third-party, crates.io)
    * features: [none]
  A unic-ucd-segment 0.9.0 (transitive third-party, crates.io)
    * features: [none]
  A unic-ucd-version 0.9.0 (transitive third-party, crates.io)
    * features: [none]
  M diem-transaction-builder 0.0.1 (workspace, path 'sdk/transaction-builder')
    * source changed from path 'client/transaction-builder'
    * (unchanged features: default)
  M scratchpad 0.1.0 (workspace, path 'storage/scratchpad')
    * removed features: default
    * (unchanged features: [none])
  M anyhow 1.0.40 (direct third-party, crates.io)
    * version upgraded from 1.0.39
    * (unchanged features: default, std)
  M codespan-reporting 0.8.0 (direct third-party, crates.io)
    * added features: serde, serialization
    * (unchanged features: [none])
  M serde 1.0.125 (direct third-party, crates.io)
    * version upgraded from 1.0.124
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M crossbeam-channel 0.5.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.0
    * (unchanged features: crossbeam-utils, default, std)
  R boogie-backend-v2 0.1.0 (workspace, path 'language/move-prover/boogie-backend-v2')
    * (old features: [none])
  R compiled-stdlib 0.1.0 (workspace, path 'language/diem-framework/compiled')
    * (old features: default)
  R diem-trace 0.1.0 (workspace, path 'common/trace')
    * (old features: [none])
  R transaction-builder 0.1.0 (workspace, path 'language/transaction-builder')
    * (old features: default)
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
  R handlebars 3.5.3 (direct third-party, crates.io)
    * (old features: default)
  R quick-error 2.0.0 (transitive third-party, crates.io) (other versions: 1.2.3)
    * (old features: [none])

host packages:
  A parse-zoneinfo 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  M anyhow 1.0.40 (transitive third-party, crates.io)
    * version upgraded from 1.0.39
    * (unchanged features: default, std)
  M serde_derive 1.0.125 (transitive third-party, crates.io)
    * version upgraded from 1.0.124
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-binary-format 0.1.0 (workspace, path 'language/move-binary-format')
    * features: default
  M scratchpad 0.1.0 (workspace, path 'storage/scratchpad')
    * removed features: default
    * (unchanged features: [none])
  M anyhow 1.0.40 (direct third-party, crates.io)
    * version upgraded from 1.0.39
    * (unchanged features: default, std)
  M serde 1.0.125 (direct third-party, crates.io)
    * version upgraded from 1.0.124
    * (unchanged features: default, derive, rc, serde_derive, std)
  M crossbeam-channel 0.5.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.0
    * (unchanged features: crossbeam-utils, default, std)
  R diem-trace 0.1.0 (workspace, path 'common/trace')
    * (old features: [none])
  R vm 0.1.0 (workspace, path 'language/vm')
    * (old features: default)
  R reqwest 0.11.2 (direct third-party, crates.io)
    * (old features: blocking, json, serde_json)
  R structopt 0.3.21 (direct third-party, crates.io)
    * (old features: default)
  R ansi_term 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R atty 0.2.14 (transitive third-party, crates.io)
    * (old features: [none])
  R clap 2.33.3 (transitive third-party, crates.io)
    * (old features: ansi_term, atty, color, default, strsim, suggestions, vec_map)
  R encoding_rs 0.8.28 (transitive third-party, crates.io)
    * (old features: [none])
  R mime 0.3.16 (transitive third-party, crates.io)
    * (old features: [none])
  R serde_urlencoded 0.7.0 (transitive third-party, crates.io)
    * (old features: [none])
  R strsim 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])
  R textwrap 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-width 0.1.8 (transitive third-party, crates.io)
    * (old features: default)
  R vec_map 0.8.2 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  M serde_derive 1.0.125 (transitive third-party, crates.io)
    * version upgraded from 1.0.124
    * (unchanged features: default)
  R heck 0.3.2 (transitive third-party, crates.io)
    * (old features: [none])
  R proc-macro-error 1.0.4 (transitive third-party, crates.io)
    * (old features: default, syn, syn-error)
  R proc-macro-error-attr 1.0.4 (transitive third-party, crates.io)
    * (old features: [none])
  R structopt-derive 0.4.14 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-segmentation 1.7.1 (transitive third-party, crates.io)
    * (old features: [none])
```

**Review by xli — APPROVED** [review]

**Comment by davidiw** [comment]
Old PR, feel free to re-open.

**Pull request closed without merging**
