### PR TITLE
update crossbeam-deque to v0.8.1 to fix RUSTSEC-2021-0093

### PR DESCRIPTION
**Pull request by bmwill**
Fixes: #8996

### CODE REVIEW

**Comment by libra-action** [comment]
# :tada: This update fixes 1 known advisory

## Dependency update review
### crossbeam-deque updated: 0.8.0 --> 0.8.1
### :tada: This update fixes known advisories

   * [RUSTSEC-2021-0093](https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw)


<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>10</td></tr><tr><td>total rust files changed</td><td>5</td></tr><tr><td>total loc change</td><td>230</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` Cargo.toml.orig `
   * ` Cargo.toml `
   * ` tests/fifo.rs `
   * ` .cargo_vcs_info.json `
   * ` tests/lifo.rs `
   * ` CHANGELOG.md `
   * ` src/deque.rs `
   * ` tests/injector.rs `
   * ` README.md `
   * ` src/lib.rs `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/deque.rs `
</details>
</details>

**Review by zekun000 — APPROVED** [review]

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
# :tada: This update fixes 1 known advisory

## Dependency update review
### crossbeam-deque updated: 0.8.0 --> 0.8.1
### :tada: This update fixes known advisories

   * [RUSTSEC-2021-0093](https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw)


<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:x:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>10</td></tr><tr><td>total rust files changed</td><td>5</td></tr><tr><td>total loc change</td><td>230</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` tests/fifo.rs `
   * ` tests/injector.rs `
   * ` Cargo.toml.orig `
   * ` tests/lifo.rs `
   * ` CHANGELOG.md `
   * ` src/deque.rs `
   * ` .cargo_vcs_info.json `
   * ` src/lib.rs `
   * ` Cargo.toml `
   * ` README.md `
</details><details>
	<summary>Click to show changed files with unsafe code</summary><br>

   * ` src/deque.rs `
</details>
</details>

**Pull request merged**
