### PR TITLE
[ci] update test report job dependency

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
Update the test report job's dependency to include the `prepare` job so that it vars are set.

## Test Plan
CI itself

### CODE REVIEW

**Review by rexhoffman — APPROVED** [review]
This should only run on main, but no harm from the change to line 97

**Review by rexhoffman — CHANGES_REQUESTED** [review]
Actually it doesn't use prepare.   It need an environment: sccache set.

**Comment by sausagee** [comment]
> Actually it doesn't use prepare. It need an environment: sccache set.

Good catch on the sccache env.  

On the prepare step dep, IMO we need it. see the if condition in line 95 `${{ needs.prepare.output.changes-target-branch == 'main' }}`

**Comment by sausagee** [comment]
Rex will open a proper fix. Closing this one.

**Pull request closed without merging**
