### PR TITLE
[RFC][vm] take slice instead of vec in vm API arguments

### PR DESCRIPTION
**Pull request by mengxu-fb**
## Motivation

All changes rooted from VM's API change on `execute_function` and `execute_script`, and back propagated to related callsites.

```diff
    pub fn execute_function(
        &mut self,
        module: &ModuleId,
        function_name: &IdentStr,
-        ty_args: Vec<TypeTag>,
+        ty_args: &[TypeTag],
        args: Vec<Value>,
        _sender: AccountAddress,
        cost_strategy: &mut CostStrategy,
        log_context: &impl LogContext,
    ) -> VMResult<()>
```

```diff
    pub fn execute_script(
        &mut self,
-        script: Vec<u8>,
-        ty_args: Vec<TypeTag>,
+        script: &[u8],
+        ty_args: &[TypeTag],
        args: Vec<Value>,
-        senders: Vec<AccountAddress>,
+        senders: &[AccountAddress],
        cost_strategy: &mut CostStrategy,
        log_context: &impl LogContext,
    ) -> VMResult<()>
```

These changes are supposed to boost performance, but need a way to test it reliably.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

`cargo xtest`

[TODO] performance numbers

## Related PRs

[George's original PR](https://github.com/gdanezis/libra/pull/1)

### CODE REVIEW

**Review by sblackshear — APPROVED** [review]
I think this is ok to land even without measuring perf results. I believe we should always measure if we're implementing an optimization that increases the complexity of the code, but this is a very straightforward change (just vec for slice everywhere).

**Comment by davidiw** [comment]
Old PR, feel free to re-open.

**Comment by bob-wilson** [comment]
@mengxu-fb What happened to this?

**Comment by mengxu-fb** [comment]
This PR never went past the Draft mode partly because we did not have a benchmark to confirm the performance gain. But as Sam pointed out, maybe a benchmark is not strictly necessary for this.

Subsequent changes in the codebase has made the PR a bit complicated to rebase. But if changing the Vec to Slice is still preferred, I can work on that. Double checking with @runtian-zhou as well to see whether this is still needed.

**Comment by mengxu-fb** [comment]
The code has changed a lot since the PR and the affected APIs will likely be refactored in the process of implementing an efficient parallel execution VM. Closing the stale PR for now.

**Pull request closed without merging**
