### PR TITLE
types: move diem-network-address into diem-types

### PR DESCRIPTION
**Pull request by phlip9**

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Review by bmwill — APPROVED** [review]
Thanks! you just might need to run 
`cargo x generate-workspace-hack` for some reason to get past CI :/

**Comment by sunshowers** [comment]
> Thanks! you just might need to run
cargo x generate-workspace-hack for some reason to get past CI :/

Thanks for flagging this btw, looks like there's a subtle bug in what I think is the way we build guppy's feature graph. Will fix upstream ^_^

**Comment by sunshowers** [comment]
For now please run the command @bmwill suggested.

**Comment by sunshowers** [comment]
Circling back here, this is actually legit and not a bug in guppy. It happens because https://github.com/diem/diem/blob/master/language/move-core/types/Cargo.toml#L18 sets `default-features = false`.

Changing that to `true` makes this problem go away.

**Comment by phlip9** [comment]
I must admit, I'm not sure why `default-features` would make a difference, true or not, and yet setting `default-features = false` to `true` for proptest in `types/Cargo.toml` seems to make it work : d

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by sunshowers** [comment]
> I must admit, I'm not sure why default-features would make a difference, true or not, and yet setting default-features = false to true for proptest in types/Cargo.toml seems to make it work : d

Sure, let me try and explain.

So [the goal of workspace-hack](https://docs.rs/hakari/*/hakari/#what-are-workspace-hack-packages) is to ensure that third-party packages are always built with one and only one feature set. We've recently put automation in place which ensures that this is always kept up-to-date.

What your change did is turn the number of different feature sets `proptest` is built with from 1 to 2. This is what got flagged by the automation and is why the lint says it needs an extra `proptest` line.

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R diem-network-address 0.1.0 (workspace, path 'network/network-address')
    * (old features: default)
```

**Comment by phlip9** [comment]
> > I must admit, I'm not sure why default-features would make a difference, true or not, and yet setting default-features = false to true for proptest in types/Cargo.toml seems to make it work : d
> 
> Sure, let me try and explain.
> 
> So [the goal of workspace-hack](https://docs.rs/hakari/*/hakari/#what-are-workspace-hack-packages) is to ensure that third-party packages are always built with one and only one feature set. We've recently put automation in place which ensures that this is always true for all third-party packages.
> 
> What your change did is turn the number of different feature sets `proptest` is built with from 1 to 2 (because some packages build with default-features = false and others with true). This is what got flagged by the automation and is why the lint says it needs an extra `proptest` line.
> 
> This can be hard to predict -- feature unification is a bit weird -- but so far it's worked.

Thanks for the explanation! I'm still a bit confused, since I would assume that `{ proptest features = [] } U { proptest features = default }` would just be `{ proptest features = default }`. Though, my mental model for feature unification / workspace hacks is admittedly pretty sparse haha 😅. On a similar note, is there any particular reason we're specifying non-default features for proptest?

**Comment by bmwill** [comment]
> On a similar note, is there any particular reason we're specifying non-default features for proptest?

A while back i think someone went on a kick and just added `default-features = false` for most third-party code, even when it wasn't needed. So i don't think there's any particular reason

**Comment by sunshowers** [comment]
> Thanks for the explanation! I'm still a bit confused, since I would assume that { proptest features = [] } U { proptest features = default } would just be { proptest features = default }. Though, my mental model for feature unification / workspace hacks is admittedly pretty sparse haha sweat_smile. On a similar note, is there any particular reason we're specifying non-default features for proptest?

Right, your mental model is almost there. The only other thing to consider is what happens if you just run `cargo build -p move-core-types` -- in that case there's no crate that has `default-features = true`, so `proptest` would get built with no features enabled. (Feature unification happens per build.)

**Pull request closed without merging**
