### PR TITLE
[move-prover] Activate and validate most unit tests for cvc4

### PR DESCRIPTION
**Pull request by wrwg**
This switches the test inclusion mode for the `cvc4` test group to "implict", indicating that all sources are included unless explicitly excluded with a tag in the source. It also makes cvc4 and z3 tests by default share the same baseline file, which makes it much easier to compare the results. It still restricts cvc4 tests to the `move-prover/tests` directory, so no Diem code.

It turns out that most tests pass and z3 and cvc4 agree on the generated baselines. In some cases cvc4 produces false positives. Those tests are marked to have their own baseline via the tag `separate_baseline: cvc4` in the source. One can easily find them using:

```
tests/sources/functional # fgrep "TODO(cvc4)" *.move
choice.move:// TODO(cvc4): this test requires a separate baseline because cvc4 produces false positives for some of choices
emits.move:// TODO(cvc4): cvc4 currently produces false positives for most of the verification problems here.
hash_model.move:// TODO(cvc4): cvc4 produces false negatives.
invariants_resources.move:// TODO(cvc4): cvc4 generates a false positive.
invariants_with_quant.move:// TODO(cvc4): this leads to non-termination with cvc4.
mono.move:// TODO(cvc4): cvc4 produces false positives caused by emit specs (like the basic test `emits.move`)
serialize_model.move:// TODO(cvc4): cvc4 produces a false positive
simple_vector_client.move:// TODO(cvc4): cvc4 produces multiple false positives for this file.
verify_vector.move:// TODO(cvc4): cvc4 produces multiple false positives for this source.
```

## Motivation

CVC4 integration

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

More tests

## Related PRs

NA

### CODE REVIEW

**Comment by wrwg** [comment]
@barrettcw

**Review by shazqadeer — APPROVED** [review]

**Pull request merged**
