### PR TITLE
add redirects for easier navigation on category indexes

### PR DESCRIPTION
**Pull request by oriooctopus**
Please do not auto merge this PR after approval

When at a url like https://developers.diem.com/docs/core/diem-protocol, a user may be tempted to navigate via url. If I was that user I would remove the last part of the url so that the new url would be  https://developers.diem.com/docs/core/, hoping to reach the category index... The issue is that right now the user would get a 404 error. This PR would redirect https://developers.diem.com/docs/core/ to https://developers.diem.com/docs/core/overview/

### CODE REVIEW

**Comment by oriooctopus** [comment]
@JoelMarcey  could you review this?

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M bytes 1.0.0 (direct third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default, std)
  M smallvec 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A boogie-backend 0.1.0 (workspace, path 'language/move-prover/boogie-backend')
    * features: [none]
  A tokio-stream 0.1.1 (direct third-party, crates.io)
    * features: default, time
  M bytes 1.0.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * added features: default, serde, std
    * (unchanged features: [none])
  M hyper 0.14.2 (direct third-party, crates.io)
    * version upgraded from 0.13.9
    * added features: client, full, h2, http1, http2, server
    * (unchanged features: default, runtime, socket2, stream, tcp)
  M reqwest 0.11.0 (direct third-party, crates.io)
    * version upgraded from 0.10.10
    * (unchanged features: blocking, json, serde_json, stream)
  M tokio 1.0.2 (direct third-party, crates.io)
    * version upgraded from 0.2.24
    * added features: bytes, once_cell, parking_lot, rt, rt-multi-thread
    * removed features: blocking, dns, fnv, futures-core, io-driver, iovec, lazy_static, mio-named-pipes, mio-uds, rt-core, rt-threaded, rt-util, slab, stream, tcp, udp, uds
    * (unchanged features: default, fs, full, io-std, io-util, libc, macros, memchr, mio, net, num_cpus, process, signal, signal-hook-registry, sync, time, tokio-macros, winapi)
  M tokio-util 0.6.1 (direct third-party, crates.io)
    * version upgraded from 0.3.1
    * added features: io
    * (unchanged features: codec, compat, default, futures-io)
  M warp 0.3.0 (direct third-party, crates.io)
    * version upgraded from 0.2.5
    * (unchanged features: default, multipart, tokio-tungstenite, websocket)
  M bytes 0.5.6 (transitive third-party, crates.io)
    * status changed from direct third-party
    * removed features: serde
    * (unchanged features: default, std)
  M h2 0.3.0 (transitive third-party, crates.io)
    * version upgraded from 0.2.7
    * (unchanged features: [none])
  M http-body 0.4.0 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M input_buffer 0.4.0 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M mio 0.7.7 (transitive third-party, crates.io)
    * version upgraded from 0.6.23
    * added features: net, os-ext, os-poll, os-util, tcp, udp, uds
    * removed features: with-deprecated
    * (unchanged features: default)
  M smallvec 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M tokio-tungstenite 0.13.0 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: [none])
  M tungstenite 0.12.0 (transitive third-party, crates.io)
    * version upgraded from 0.11.1
    * (unchanged features: [none])
  R iovec 0.1.4 (transitive third-party, crates.io)
    * (old features: [none])
  R mio-uds 0.6.8 (transitive third-party, crates.io)
    * (old features: [none])
  R net2 0.2.37 (transitive third-party, crates.io)
    * (old features: default, duration)
  R pin-project-lite 0.1.11 (transitive third-party, crates.io) (other versions: 0.2.4)
    * (old features: [none])
  R serde_urlencoded 0.6.1 (transitive third-party, crates.io) (other versions: 0.7.0)
    * (old features: [none])
  R urlencoding 1.1.1 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  M tokio-macros 1.0.0 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A bytes 1.0.0 (direct third-party, crates.io)
    * features: default, std
  A tokio-stream 0.1.1 (transitive third-party, crates.io)
    * features: default, time
  M hyper 0.14.2 (direct third-party, crates.io)
    * version upgraded from 0.13.9
    * added features: client, full, h2, http1, http2, server
    * (unchanged features: default, runtime, socket2, stream, tcp)
  M reqwest 0.11.0 (direct third-party, crates.io)
    * version upgraded from 0.10.10
    * (unchanged features: blocking, json, serde_json)
  M tokio 1.0.2 (direct third-party, crates.io)
    * version upgraded from 0.2.24
    * added features: bytes, once_cell, parking_lot, rt, rt-multi-thread
    * removed features: blocking, dns, fnv, futures-core, io-driver, iovec, lazy_static, mio-named-pipes, mio-uds, rt-core, rt-threaded, rt-util, slab, stream, tcp, udp, uds
    * (unchanged features: default, fs, full, io-std, io-util, libc, macros, memchr, mio, net, num_cpus, process, signal, signal-hook-registry, sync, time, tokio-macros, winapi)
  M bytes 0.5.6 (transitive third-party, crates.io)
    * status changed from direct third-party
    * (unchanged features: default, std)
  M h2 0.3.0 (transitive third-party, crates.io)
    * version upgraded from 0.2.7
    * (unchanged features: [none])
  M http-body 0.4.0 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: [none])
  M mio 0.7.7 (transitive third-party, crates.io)
    * version upgraded from 0.6.23
    * added features: net, os-ext, os-poll, os-util, tcp, udp, uds
    * removed features: with-deprecated
    * (unchanged features: default)
  M smallvec 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M tokio-util 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: codec, default)
  M tracing 0.1.22 (transitive third-party, crates.io)
    * removed features: log
    * (unchanged features: std)
  R iovec 0.1.4 (transitive third-party, crates.io)
    * (old features: [none])
  R mime_guess 2.0.3 (transitive third-party, crates.io)
    * (old features: default, rev-mappings)
  R mio-uds 0.6.8 (transitive third-party, crates.io)
    * (old features: [none])
  R net2 0.2.37 (transitive third-party, crates.io)
    * (old features: default, duration)
  R pin-project-lite 0.1.11 (transitive third-party, crates.io) (other versions: 0.2.4)
    * (old features: [none])
  R unicase 2.6.0 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  M tokio-macros 1.0.0 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  R unicase 2.6.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by JoelMarcey** [comment]
@bmwill 

What's the best way to handle this error from `git-check`?

```
Run ./scripts/git-checks.sh
Merge commit 710627c8c6365246fda59cd51427f2e198716167 found
Please fix your branch/PR to not include merges
Error: Process completed with exit code 1.
```

I assume `bors-squash` doesn't help in this case.

**Review by JoelMarcey — APPROVED** [review]

**Comment by bmwill** [comment]
> I assume `bors-squash` doesn't help in this case.

So we don't allow for merge commits in this repo although I can't remember if bors would properly handle this case...lets see

/land squash+

**Comment by bmwill** [comment]
@oriooctopus Yeah looks like you're going to need to rebase your PR on top of the most recent tip of master and remove the merge commit from the PR before we're able to land this

**Pull request closed without merging**
