### PR TITLE
[move prover] compile all sources in prep for new invariant approach

### PR DESCRIPTION
**Pull request by emmazzz**
## Motivation

This PR is the first of a series of PRs to address the cross-module invariants problem in the Move Prover. This PR
- Compiles all Move code in the provided folder into the environment
- Adds placeholder analysis phase for later analyzing the functions/modules to be translated/verified
- Writes out TODOs for work items in the subsequent PRs 
- Moves the warning of unused schema to the end of spec checker so only one warning will be generated for each unused schema

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### CODE REVIEW

**Review by wrwg — APPROVED** [review]
Nice.

**Comment by metajack** [comment]
re-landing due to bors failure

/land

**Pull request closed without merging**
