### PR TITLE
[cluster-test] Add tx generator for load test mempool

### PR DESCRIPTION
**Pull request by snakech**
## Motivation

Add tx generator for mempool load test.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan
./scripts/cti -W zihao --pr 6646 --run load_test -- --mempool --state-sync --emit-txn --duration 300
```
2020-11-05T00:54:19.297719Z [main] INFO testsuite/cluster-test/src/experiments/load_test.rs:209 Total tx emitter stats: submitted: 292440, committed: 292440, expired: 0, bytes: 100891800
2020-11-05T00:54:19.297737Z [main] INFO testsuite/cluster-test/src/experiments/load_test.rs:209 Average rate: submitted: 974 txn/s, committed: 974 txn/s, expired: 0 txn/s, latency: 4604 ms, p99 latency: 5250 ms, 336306 bytes/s
2020-11-05T00:54:19.297740Z [main] INFO testsuite/cluster-test/src/experiments/load_test.rs:209 Total mempool stats: submitted 2868500 txs, exchanged 28685 messages, 1274015590 bytes
2020-11-05T00:54:19.297743Z [main] INFO testsuite/cluster-test/src/experiments/load_test.rs:209 Average rate: submitted 9561 txs/s, exchanged 95 messages/s, 4246718 bytes/s
2020-11-05T00:54:19.297744Z [main] INFO testsuite/cluster-test/src/experiments/load_test.rs:209 Total state sync stats: received 17767750 txs, exchanged 71073 messages, 2487555 bytes, 
2020-11-05T00:54:19.297746Z [main] INFO testsuite/cluster-test/src/experiments/load_test.rs:209 Average rate: received 59225 txs/s, exchanged 236 msg/s, 8291 bytes/s, 
2020-11-05T00:54:19.297763Z [main] INFO testsuite/cluster-test/src/main.rs:685 Experiment finished, waiting until all affected validators recover
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)

### CODE REVIEW

**Review by zekun000 — COMMENTED** [review]
the number seems higher than expected, also it seems they're probably all rejected. cc: @christinacelee

**Comment by snakech** [comment]
> the number seems higher than expected, also it seems they're probably all rejected. cc: @christinacelee

There is no signs showed any rejections of mempool?

**Comment by christinacelee** [comment]
the way things are set up in the PR rn, we may be submitting the same txns to the FN (via mempool load test) and the V (via emit-tx), since the accounts for mempool load test and JSON RPC are the same.. the simplest way to avoid this is to just have completely separate accounts for mempool and JSON RPC load test

(for future reference, you can check whether transactions submitted to mempool are rejected in the grafana mempool dashboard, or check this counter out: https://github.com/libra/libra/blob/master/mempool/src/counters.rs#L217-L228)

also in this setup, we're submitting to FN's mempool and V's JSON-RPC only. is there a reason we're only submitting to V's JSON-RPC? in later load tests we may want to try submitting to FN's mempool _and_ JSON-RPC simultaneously

**Comment by snakech** [comment]
> the way things are set up in the PR rn, we may be submitting the same txns to the FN (via mempool load test) and the V (via emit-tx), since the accounts for mempool load test and JSON RPC are the same.. the simplest way to avoid this is to just have completely separate accounts for mempool and JSON RPC load test
> 
> (for future reference, you can check whether transactions submitted to mempool are rejected in the grafana mempool dashboard, or check this counter out: https://github.com/libra/libra/blob/master/mempool/src/counters.rs#L217-L228)
> 
> also in this setup, we're submitting to FN's mempool and V's JSON-RPC only. is there a reason we're only submitting to V's JSON-RPC? in later load tests we may want to try submitting to FN's mempool _and_ JSON-RPC simultaneously

I think txs submit to mempool and emit-tx are different. Basically, for all txs, we do randomly picking up 2 peers(addresses) and generate one p2p tx. But yes, we do use the same batch of accounts for both components.

CT default to submit tx to V, but it can switch to FN, I can make this change

**Comment by davidiw** [comment]
Is this outdated? feel free to re-open.

**Pull request closed without merging**
