### PR TITLE
[language-e2e-tests] Update tests that compile IR to not use multiple versions of the Diem Framework

### PR DESCRIPTION
**Pull request by tzakian**
This PR fixes an issue uncovered in #8739 where we compile scripts and link them against the current Diem Framework, but then try and run them on older versions.

This PR removes testing with different versions for tests that do this.

### CODE REVIEW

**Review by tnowacki — APPROVED** [review]
Thanks for the quick fix! Can you verify that this fixes @nilehmann's issue?

**Comment by tzakian** [comment]
Verified against that PR and wound up catching two places that slipped through from the testing utils, and it works (although @nilehmann will need to regenerate the golden file(s) for add_child_currencies)

**Review by tnowacki — DISMISSED** [review]

**Comment by nilehmann** [comment]
I tested my changes on top of this and I'm not getting the error now 👌🏽

**Pull request merged**
