### PR TITLE
[language] rename move-lang to move-compiler

### PR DESCRIPTION
**Pull request by vgao1996**
This renames the `move-lang` crate to `move-compiler`, which we previously agreed upon.

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-compiler 0.0.1 (workspace, path 'language/move-compiler')
    * features: [none]
  R move-lang 0.0.1 (workspace, path 'language/move-lang')
    * (old features: [none])
```

**Review by tnowacki — DISMISSED** [review]
We might want to rename the `compiler` mod since `move_compiler::compiler` feels a bit silly :P But for another PR!

**Pull request merged**
