### PR TITLE
Merge Trove hackathon

### PR DESCRIPTION
**Pull request by hariria**
## Motivation

The goal is to merge the modules created during the trove-hackathon into main. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

N/A

### CODE REVIEW

**Review by zekun000 — CHANGES_REQUESTED** [review]
we need to hand picked the changes we want to merge and resolve conflicts manually

**Comment by bmwill** [comment]
Given the large number of commits (some of which are poor formed) I'd probably recommend squashing all of these down into a single commit to land on main

**Comment by bmwill** [comment]
+ what @zekun000 said :)

**Comment by zekun000** [comment]
also those commits in the hackathon branch didn't go through code reviews, so I'd expect the owners of those change to send PR to main branch and request proper reviews

**Comment by dimroc** [comment]
Just a heads up that all the [shuffle] commits and a few others were pulled into `main` in separate PRs that were code reviewed. A rebase should remove a lot of these commits.

**Comment by gregnazario** [comment]
Let's close this in favor of a new commit from your fork

**Pull request closed without merging**
