### PR TITLE
clean up dependencies for diem-types and diem-json-rpc-types

### PR DESCRIPTION
**Pull request by bmwill**
Continuing on the path to cleaning up a subset of our dependencies for publishing to crates.io this PR removes some unneeded dependencies from diem-types and dime-json-rpc-types

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Review by xli — APPROVED** [review]

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R fallible 0.1.0 (workspace, path 'common/fallible')
    * (old features: [none])
```

**Pull request merged**
