### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by nimishamw**
This PR contains changes to the following docs:

- Life of a Transaction: Includes content updates for clarity, image updates to match with revised content
- Diem Protocol: Image update to match life of a txn images
- Updates from Coin1 to XUS: Currency code updates to wallet integration guide, merchant integration, Diem CLI

### CODE REVIEW

**Review by JoelMarcey — CHANGES_REQUESTED** [review]
@nimishamw Lint is failing because it wants newlines at the end of all the .svg files. Can you open them all and add an empty newline at the end of the files with a `return` key press?

**Review by JoelMarcey — CHANGES_REQUESTED** [review]
We need to get rid of the merge commit so that the Diem checker is happy.

@bmwill Is there a `bors` tag that can take care of this? Or is this something that needs to be done on the PR side through some git magic?

**Comment by bmwill** [comment]
The author is going to need to remove the merge commit on their side.

**Review by JoelMarcey — APPROVED** [review]

**Pull request merged**
