### PR TITLE
[cluster-test] Improving node cleanup of CT teardown

### PR DESCRIPTION
**Pull request by snakech**
This PR added an abstracted fn - ```delete<T>```, which can allow current 3 steps of deleting resource procedure of delete_all for cleanup: delete_pod, delete_service, delete_job running concurrently instead of sequential

test command:
```./scripts/cti --pr 7106 --run bench -- --duration 120```
with timeframe breakdown clock counter in millisecs.

Before change:
```
start of steup
    swarm kube end 1036
    grafana end 16
    cluster builder start
        **end cleanup - cluster builder 28** <-----------
	end spawn nodes - cluster builder 186759
    cluster builder end 245356
end of setup 247428
end of health check 19426
end of after experiment health check 5057
start of tear down
    **end of tear down- cleanup 173645** <-----------
    get_workspace - cleanup 3
    set_asg_size - cleanup 630
end of tear down 174279
```

After change:
```
start of steup
    swarm kube end 1039
    grafana end 17
    cluster builder start
        **end cleanup - cluster builder 20** <--------------
	end spawn nodes - cluster builder 195927
    cluster builder end 267183
end of setup 269261
end of health check 20053
end of after experiment health check 5044
start of tear down
    **end of tear down- cleanup 106286** <-------------
    get_workspace - cleanup 3
    set_asg_size - cleanup 1106
end of tear down 107396
```

We can found around 40% time reduce for cleanup work of delete pod, delete service and delete job
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/developers.libra.org, and link to your PR here.)

### CODE REVIEW

**Comment by andll** [comment]
Can you add details to the PR on what are we changing and why does it improve speed?

**Comment by snakech** [comment]
> Can you add details to the PR on what are we changing and why does it improve speed?

details added~

**Review by andll — APPROVED** [review]

**Pull request closed without merging**
