### PR TITLE
[workspace-hack] add a few dependencies + update feature sets

### PR DESCRIPTION
**Pull request by sunshowers**
I've been doing some exploration with guppy to try and minimize the
number of different feature sets that get built. Here's a first pass,
though this is a one-shot process and we still need to figure out how
to ensure this crate stays up-to-date.

### CODE REVIEW

**Comment by sunshowers** [comment]
This is the exploratory code I wrote: https://github.com/sunshowers/libra/commit/2c9b60706f5e10d3117a6f6cbf6b5c6b3baa35a6

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A diem-operational-tool 0.1.0 (initial, path 'config/management/operational')
    * features: [none]
  M execution-correctness 0.1.0 (initial, path 'execution/execution-correctness')
    * status changed from workspace
    * (unchanged features: [none])
```

**Review by bmwill — APPROVED** [review]

**Pull request closed without merging**
