### PR TITLE
Improving documentation

### PR DESCRIPTION
**Pull request by villesundell**
## Motivation
Improving the documentation by:

- Updating CLI Reference documentation, and fixed style issues (inconsistent style).

- Documenting previously undocumented libra-node feature.

- Fixing a xclippy reference.

Each one of these changes are documented in their respective commits.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Built the documentation using `./scripts/build_docs.sh -b`, and checked the resulting HTML using Firefox.

## Related PRs

No related PRs.

### CODE REVIEW

**Comment by davidiw** [comment]
Thanks for contributing this, when I caught wind of it, we were going through the name change and a docs refresh. Now that that is over, please feel free to rebase I will gladly get these in :D.

**Comment by villesundell** [comment]
That's understandable @davidiw :slightly_smiling_face: Should I include my version of chain persistance (personally I think it's clearer than the current wording :wink:  ):

> You can later restore the chain state by running `diem-node` with the previously used configuration path, like: `cargo run -p diem-node -- --test --config /tmp/efd6dc5656ee8edf92569c330b8de8bb/`.

**Comment by davidiw** [comment]
> That's understandable @davidiw 🙂 Should I include my version of chain persistance (personally I think it's clearer than the current wording 😉 ):
> 
> > You can later restore the chain state by running `diem-node` with the previously used configuration path, like: `cargo run -p diem-node -- --test --config /tmp/efd6dc5656ee8edf92569c330b8de8bb/`.

In contrast to
> The local test validator network ledger state can be persisted by copying /distinct/tmp/path/ to a persistent directory and running the process:

> cargo run -p diem-node -- --test --config /persistent/path

?

Its worth noting that "ledger state" is a bit more common: https://developers.diem.com/docs/core/diem-protocol

Maybe merging the two?

You can later restore the ledger state by running `diem-node` with a previously used configuration path:

cargo run -p diem-node -- --test --config /previous/path

(or maybe the explicit tmp, mind you they differ by platform, but maybe an explicit path akin to the example above is more accessible)...

**Comment by villesundell** [comment]
@davidiw Done :slightly_smiling_face: I also added contributors from the previous directory to the "CONTRIBUTORS" file (more information in the commit message)

**Review by davidiw — APPROVED** [review]
thanks a lot!

/land

**Comment by davidiw** [comment]
> @davidiw Done 🙂 I also added contributors from the previous directory to the "CONTRIBUTORS" file (more information in the commit message)

Fair enough :), I'll flag the contributors doc to the doc maintainers (a different set of folks that don't really monitor the code base "manage" that)

**Pull request closed without merging**
