### PR TITLE
[changelog] release-1.5

### PR DESCRIPTION
**Pull request by sausagee**
release-1.5 changelog.  Review and edit in https://hackmd.io/XV_1k2YpStKJ7kYAepjirg

### CODE REVIEW

**Comment by sausagee** [comment]
> General question: Going long term, are we planning on decoupling `diem-framework/` from validator/FN binary releases?

I cannot speak for the Diem Maintainers, but we are discussing this. 

My personal POV is that we should decouple them as in, move-lang vs diem-core vs any-framework.

**Review by bob-wilson — APPROVED** [review]
The new Diem Framework entries look good, so I'll reapprove this. It's still missing a bunch of earlier PRs so I'm assuming there will be a follow-up for those.

**Pull request closed without merging**
