### PR TITLE
disable compatibility tests

### PR DESCRIPTION
**Pull request by bmwill**

### CODE REVIEW

**Review by JoshLind — APPROVED** [review]
🥳

**Comment by zihaoccc** [comment]
Do we want to disable compat tests entirely AKA: LBT or we still want to run perf test? 
Because those two flags only indicate which test suite will run: compat test or perf test

**Comment by zihaoccc** [comment]
could you please modify the line of command to run perf test: https://github.com/diem/diem/blob/1ed0119f636f2c8fb79d9a082207c94e1bfa086a/.github/workflows/ci-test.yml#L1158 to
 
```
cmd="./scripts/fgi/run --tag ${{ needs.build-images.outputs.head-tag }} --suite land_blocking --report forge_report.json"
```
with flag `--report forge_report.json` to indicate the output to save test result?

**Review by zihaoccc — APPROVED** [review]

**Comment by bmwill** [comment]
we still want to run the perf tests, we're only shutting off the compat tests

**Pull request merged**
