### PR TITLE
[decoupled-execution] add linked list for the buffer manager.

### PR DESCRIPTION
**Pull request by yuxiamit**
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Review by zekun000 — COMMENTED** [review]
can we make it more explicit which parts are copy-pasted, which parts are modified?

**Review by zekun000 — COMMENTED** [review]
from what I understand, only the utils functions are added?

**Comment by yuxiamit** [comment]
> from what I understand, only the utils functions are added?

Mostly yes. Besides the utils functions, I also made the following changes:

1. fix the way they use `RefCell`, e.g. `old_head.borrow_mut().prev = Some(new_head.clone());` should be `(*old_head).borrow_mut().prev = Some(new_head.clone());`. I guess newer version compiler will call `borrow_mut()` of `Rc` instead of `RefCell`. We need to manually deref the Rc.

2. expose `Link` as the cursor type.

**Review by zekun000 — DISMISSED** [review]

**Pull request merged**
