### PR TITLE
[move-core] Refactored MoveResource trait

### PR DESCRIPTION
**Pull request by runtian-zhou**
## Motivation

Refactored `MoveResource` trait to better work our new Move type system:

1. `MoveStructType` to represent a rust struct that correspond to a Move struct
2. `MoveResource` to represent a rust struct that correspond to a top level Move Resource.

I intended to use `MoveResource` as a marker trait to distinguish between event payload and top level resources.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
`cargo check`

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Comment by sblackshear** [comment]
@tnowacki @metajack where did we land on the canonical term for "a value stored at the top level of Move global storage"? I know we went with `has key` for abilities, but not sure what that implies for `MoveResource` here (`MoveKey`)?

**Review by xli — APPROVED** [review]

**Comment by metajack** [comment]
@sblackshear I don't remember if we landed on one. Maybe "key resource" would be the right nomenclature? Is this type for `has key`? I think "resources" can't be copied or dropped, and only resources can be keys, but it's not clear to me whether the being a resource or being a key is the important part here.

**Pull request closed without merging**
