### PR TITLE
[move-lang] Don't stop at first parser error

### PR DESCRIPTION
**Pull request by tnowacki**
- First step in slowly brining the parser more in line with other passes
- The parser can now register warnings/non blocking errors
- Despite being labeled nonblocking, token errors still stop parsing of that file

## Motivation

Might help a bit in the user experience of #9138

## Test Plan

- Updated tests

### CODE REVIEW

**Review by modocache — DISMISSED** [review]
Phenomenal! 🙌

**Review by bob-wilson — DISMISSED** [review]
I love it. There's more to do in this area, but this is a great start.

**Pull request merged**
