### PR TITLE
[Website] Adding warnings about using JSON-RPC

### PR DESCRIPTION
**Pull request by AnomalRoil**
and running some markdown linter on the modified files

## Motivation

Currently we recognize that relying on a JSON-RPC endpoint provided by a public fullnode might not be the best solution from a security point of view, since the JSON-RPC API isn't exposing crypto proofs for its data.

The best way to do it securely is to run our own fullnode, and then rely on its JSON-RPC API. (Which needs not be public then), but this was previously undocumented.

This PR attempts to add the proper warnings and information for people to know what they are exposing themselves to when relying on a public JSON-RPC endpoint.

### CODE REVIEW

**Comment by AnomalRoil** [comment]
@nimishamw @JoelMarcey  Where does this live now? 
We need to add these warnings from a security POV.

**Comment by JoelMarcey** [comment]
@AnomalRoil developers.diem.com content is hosted elsewhere, as you may have heard. Will get back to you on the best way to get these changes merged there.

**Comment by davidiw** [comment]
Old PR, feel free to re-open.

**Comment by mickayz** [comment]
@AnomalRoil is no longer working on the project. @JoelMarcey did you need any more information for us to land these changes?

**Comment by JoelMarcey** [comment]
@mickayz Can you use the edit button on developers.diem.com to make these suggested edits and then they can be merged in? 

cc @nimishamw

**Pull request closed without merging**
