### PR TITLE
[smt] Parallelize smt batch update with rayon::join

### PR DESCRIPTION
**Pull request by lightmark**
## Motivation

further parallelize batch_update api in smt with another 4x speedup.

### Have you read the [Contributing Guidelines on pull requests]
Y

## Test Plan

current coverage.

### CODE REVIEW

**Review by msmouse — APPROVED** [review]

**Review by wqfish — APPROVED** [review]

**Review by zekun000 — APPROVED** [review]

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A rayon 1.5.0 (direct third-party, crates.io)
    * features: [none]
  A crossbeam-channel 0.5.0 (transitive third-party, crates.io)
    * features: crossbeam-utils, default, std
  A crossbeam-deque 0.8.0 (transitive third-party, crates.io)
    * features: crossbeam-epoch, crossbeam-utils, default, std
  A crossbeam-epoch 0.9.3 (transitive third-party, crates.io)
    * features: alloc, lazy_static, std
  A crossbeam-utils 0.8.3 (transitive third-party, crates.io)
    * features: default, lazy_static, std
  A memoffset 0.6.1 (transitive third-party, crates.io)
    * features: default
  A num_cpus 1.13.0 (transitive third-party, crates.io)
    * features: [none]
  A rayon-core 1.9.0 (transitive third-party, crates.io)
    * features: [none]
```

**Pull request merged**
