### PR TITLE
[mempool] Remove flaky test

### PR DESCRIPTION
**Pull request by gregnazario**
### Overview

The flaky failover test in the mempool scenario didn't have enough
context, and was too low level to do a full test of a failover
situation.  There is already a test_vfn_failover test covering this
scenario in smoke test.

This is the test that covers the scenario: [test_vfn_failover](https://github.com/diem/diem/blob/main/testsuite/smoke-test/src/full_nodes.rs#L180-L181).

### Related issues

https://github.com/diem/diem/issues/8671

### CODE REVIEW

**Review by bmwill — APPROVED** [review]

**Review by rexhoffman — DISMISSED** [review]
👍

**Review by bmwill — DISMISSED** [review]
/land

**Pull request closed without merging**
