### PR TITLE
Diem CLI fixes

### PR DESCRIPTION
**Pull request by yanivmo**
This PR upgrades the Diem CLI component of the developers website. The upgraded version contains numerous improvements and bug fixes.

This PR builds upon diem/diem#7071 by @oriooctopus. If it looks like this PR has a lot of changes, it is only because diem/diem#7071 was not merged yet.

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A cpuid-bool 0.2.0 (transitive third-party, crates.io) (other versions: 0.1.2)
    * features: [none]
  M bcs 0.1.2 (direct third-party, crates.io)
    * version upgraded from 0.1.1
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.9.0
    * (unchanged features: alloc, lazy_static, std)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M memoffset 0.6.1 (transitive third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M polyval 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
```

**Comment by JoelMarcey** [comment]
Now that #7071 has landed, @yanivmo can you rebase this and then we can approve and land it?

**Comment by yanivmo** [comment]
> Now that #7071 has landed, @yanivmo can you rebase this and then we can approve and land it?

Rebased.

**Review by JoelMarcey — APPROVED** [review]

**Comment by JoelMarcey** [comment]
We may need one more reviewer, but I will try landing it.

**Pull request closed without merging**
