### PR TITLE
Remove json-rpc streaming service

### PR DESCRIPTION
**Pull request by bmwill**
The Streaming service isn't being used, the tests for the service are flaky and we're phasing out the jsonrpc interface so lets remove it to eliminate the maintenance burden.

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Changing JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Review by xli — APPROVED** [review]
/land

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R tokio-tungstenite 0.14.0 (direct third-party, crates.io) (other versions: 0.13.0)
    * (old features: connect, default, stream)
  R tungstenite 0.13.0 (transitive third-party, crates.io) (other versions: 0.12.0)
    * (old features: [none])
```

**Review by xli — DISMISSED** [review]
/land

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R tokio-tungstenite 0.14.0 (direct third-party, crates.io) (other versions: 0.13.0)
    * (old features: connect, default, stream)
  R tungstenite 0.13.0 (transitive third-party, crates.io) (other versions: 0.12.0)
    * (old features: [none])
```

**Review by xli — APPROVED** [review]
/land

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R tokio-tungstenite 0.14.0 (direct third-party, crates.io) (other versions: 0.13.0)
    * (old features: connect, default, stream)
  R tungstenite 0.13.0 (transitive third-party, crates.io) (other versions: 0.12.0)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R tokio-tungstenite 0.14.0 (direct third-party, crates.io) (other versions: 0.13.0)
    * (old features: connect, default, stream)
  R tungstenite 0.13.0 (transitive third-party, crates.io) (other versions: 0.12.0)
    * (old features: [none])
```

**Review by xli — APPROVED** [review]
/land

**Pull request merged**
