### PR TITLE
[vm-genesis] Implement a option to generate genesis with parallel exe…

### PR DESCRIPTION
**Pull request by runtian-zhou**
…cution activated.

## Motivation
Implement an option to generate genesis that enables parallel transaction execution at boot up time.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan
Added test to make sure the config can be loaded correctly.

### CODE REVIEW

**Review by zekun000 — APPROVED** [review]

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A read-write-set 0.1.0 (workspace, path 'language/tools/read-write-set')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A read-write-set 0.1.0 (workspace, path 'language/tools/read-write-set')
    * features: [none]
```

**Review by zekun000 — DISMISSED** [review]

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A read-write-set 0.1.0 (workspace, path 'language/tools/read-write-set')
    * features: [none]
```

**Review by tzakian — APPROVED** [review]

**Pull request merged**
