### PR TITLE
Add support for Iff Operator

### LINKED ISSUE #4977: [Feature Request] Add an explicit "iff" operator (<==>) to the specification language
# 🚀 Feature Request

An new operator <==> for equality on Booleans only.  It should have similar precedence as ==>.
Since people probably don't have clear expectations for the relative precedence of ==> and <==>,
we should forbid consecutive uses of <==> and ==> (require explicit parenthesization).

== should continue to work on Booleans so that code with generic types can use ==.

## Motivation
I thought we didn't need an "iff" operator for Boolean expressions because it's the same as equality (==).

Unfortunately, we want different == than for <==>.  For example:
x == P && Q  parses as (x == P) && Q, which is what we want of x and P are numbers.
If P and Q are predicates and the user is trying to get "iff", because user are used to 
&& binding more tightly than ==> or <==>, i.e. x == (P && Q) 

x <==> P && Q would be expected to parse as x <==> (P && Q).

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by Checkmate50**
## Motivation

Introduces the Iff operator and closes #4977.  The goal of this introduction is to add a minor feature as well as to help me work through the codebase and PR system.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

My tests are fairly minimal, just updating the existing arithm file with two instances of the iff operator.  I argue this is sufficient for a simple operator due to the relative lack of complexity of changes made; additionally, I minimize adding additional test cases to avoid excessive testing for a simple feature.  It is worth noting that I manually tested the operator with negative testing to ensure that it works with exactly booleans, which seems to be the case; I'm not sure if such negative tests should also be included.

### CODE REVIEW

**Comment by bob-wilson** [comment]
I didn't review the code but I can give some quick feedback on the PR itself.

- You can delete the "If targeting a release branch, please fill the below out as well" section of the PR template (and edit it out of this one) if your PR is targeting the main branch. That extra info is only needed if you're applying a fix to a specific release branch.
- You can usually omit the "Related PRs" section as well. If you have documentation updates, it would be best to include them in the same PR instead of putting them into a separate "related" PR. With regard to spec docs, check out `language/move-prover/doc/user/spec-lang.md`. There's a brief mention of the `==>` operator there.

**Comment by bob-wilson** [comment]
It would also be helpful to tag specific reviewers so that they see the PR. I would suggest @wrwg, @mengxu-fb and @DavidLDill for this one. (You should add them.)

**Comment by mengxu-fb** [comment]
The code LGTM but the commits needs to be better organized. There are two issues that needs to be addressed:
- Each commit should pass the CI to enable [bisect-able history](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#bisect-able-history)
- There should be no "merge" commits, a better way is to "rebase", the rationale is [here](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#responding-to-reviewer-feedback)

**Comment by Checkmate50** [comment]
Thanks for the feedback!  Would you recommend that I rebase my local repository or create a new PR?

**Comment by mengxu-fb** [comment]
I would recommend a rebase on your local repository and update this PR.

**Review by wrwg — APPROVED** [review]
Nice work

**Pull request closed without merging**
