### PR TITLE
[move-lang][functional-tests] add test cases for friend visibility

### PR DESCRIPTION
**Pull request by mengxu-fb**
- call a public(friend) function from friend/non-friend modules
- various cyclic dependencies that may be introduced from friend decls

## Motivation

Who does not want more tests?

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

cargo xtest

### CODE REVIEW

**Review by bob-wilson — APPROVED** [review]
Did this get forgotten? The tests here look good to me, anyway.

**Comment by mengxu-fb** [comment]
I guess so, the tests are lost in the limbo... I'll revive it and do a rebase.

**Comment by mengxu-fb** [comment]
PR revived, rebased to latest main. /land

**Pull request closed without merging**
