### PR TITLE
[x] update to guppy 0.6.2

### PR DESCRIPTION
**Pull request by sunshowers**
Fixes a bug in detection of default features.

### CODE REVIEW

**Review by metajack — APPROVED** [review]

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M serde 1.0.118 (direct third-party, crates.io)
    * version upgraded from 1.0.117
    * (unchanged features: default, derive, rc, serde_derive, std)

host packages:
  M serde_derive 1.0.118 (transitive third-party, crates.io)
    * version upgraded from 1.0.117
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M serde 1.0.118 (direct third-party, crates.io)
    * version upgraded from 1.0.117
    * (unchanged features: default, derive, rc, serde_derive, std)

host packages:
  M serde_derive 1.0.118 (transitive third-party, crates.io)
    * version upgraded from 1.0.117
    * (unchanged features: default)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M serde 1.0.118 (direct third-party, crates.io)
    * version upgraded from 1.0.117
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)

host packages:
  M serde_derive 1.0.118 (transitive third-party, crates.io)
    * version upgraded from 1.0.117
    * (unchanged features: default)
```

**Pull request closed without merging**
