### PR TITLE
begin consolidating common crates in the 'crates' directory

### PR DESCRIPTION
**Pull request by bmwill**

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M diem-crypto 0.0.3 (workspace, path 'crates/diem-crypto')
    * source changed from path 'crypto/crypto'
    * (unchanged features: default, fiat)

host packages:
  M diem-crypto-derive 0.0.3 (workspace, path 'crates/diem-crypto-derive')
    * source changed from path 'crypto/crypto-derive'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-crypto 0.0.3 (workspace, path 'crates/diem-crypto')
    * source changed from path 'crypto/crypto'
    * (unchanged features: default, fiat)

host packages:
  M diem-crypto-derive 0.0.3 (workspace, path 'crates/diem-crypto-derive')
    * source changed from path 'crypto/crypto-derive'
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M diem-crypto 0.0.3 (workspace, path 'crates/diem-crypto')
    * source changed from path 'crypto/crypto'
    * (unchanged features: default, fiat)

host packages:
  M diem-crypto-derive 0.0.3 (workspace, path 'crates/diem-crypto-derive')
    * source changed from path 'crypto/crypto-derive'
    * (unchanged features: [none])
```

**Review by zihaoccc — DISMISSED** [review]

**Pull request merged**
