### PR TITLE
[RUSTSEC] upgrade tokio->1.8.1, prost->0.8.0

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation

Upgrading dependency versions due to #8716 

To make prost 0.8.0 across the board, prost-build and prost-types were bumped as well. As a result, some itertools versions bumped to 0.10.0 which was something we've already been using.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Y
## Test Plan
existing coverage

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M tokio 1.8.1 (direct third-party, crates.io)
    * version upgraded from 1.6.1
    * (unchanged features: bytes, default, fs, full, io-std, io-util, libc, macros, memchr, mio, net, num_cpus, once_cell, parking_lot, process, rt, rt-multi-thread, signal, signal-hook-registry, sync, time, tokio-macros, winapi)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M tokio 1.8.1 (direct third-party, crates.io)
    * version upgraded from 1.6.1
    * (unchanged features: bytes, default, fs, full, io-std, io-util, libc, macros, memchr, mio, net, num_cpus, once_cell, parking_lot, process, rt, rt-multi-thread, signal, signal-hook-registry, sync, time, tokio-macros, winapi)
```

**Review by bmwill — APPROVED** [review]
/land

**Pull request closed without merging**
