### PR TITLE
[diem-framework] Add additional auth checks

### PR DESCRIPTION
**Pull request by tzakian**
Adds additional checks to account creation and currency-related functions to make the authentication requirements clearer. 

Adds an additional check to make sure that balances cannot be added to an address unless an account exists at that address. This required some changes to the order of account creation in each of the `create_YYY_account` functions in `DiemAccount`.

### CODE REVIEW

**Review by mickayz — DISMISSED** [review]
LGTM

**Review by junkil-park — COMMENTED** [review]
Now, can we verify an invariant like:

invariant forall token: type: forall addr: address where exists<Balance<token>>(addr): exists_at(addr);

?

**Review by sblackshear — DISMISSED** [review]

**Comment by tzakian** [comment]
> invariant forall token: type: forall addr: address where exists<Balance>(addr): exists_at(addr);

We should be able to I believe. I'll see if I can add it to the DiemAccount module

**Review by sblackshear — APPROVED** [review]

**Pull request merged**
