### PR TITLE
[move][evm] Experiments for EVM Move Programming Model

### PR DESCRIPTION
**Pull request by wrwg**
This PR contains some rough experiments for a possible programming model for EVM in Move. Check the README.md for details.

This assumes some basic knowledge of EVM and Solidity (see e.g. the [Ethereum book](https://github.com/ethereumbook/ethereumbook)).

## Motivation

Move-on-EVM

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

NA

## Related PRs

NA

### CODE REVIEW

**Comment by sblackshear** [comment]
Like this approach--very clean for how generic it is!

Couple of high-level questions:
- Is the idea here to compile from Move source code to EVM bytecode, Move bytecode to EVM bytecode, or Move source to Solidity? I assume the first one because of the annotations, but wanted to make sure I understand (and could also see value in the other two approaches).
- If I compile the Move code examples here to Move bytecode and run them on the Move VM, then compile/run the same code on the EVM, what are the guarantees you are trying to provide (if any) about behavioral equivalence between the Move execution trace and the EVM execution trace? I can guess the answer includes something about the equivalence of changes to the Move and EVM global states, but the story on errors/gas in each trace is less clear to me.

**Comment by wrwg** [comment]
> Like this approach--very clean for how generic it is!
> 
> Couple of high-level questions:
> 
> * Is the idea here to compile from Move source code to EVM bytecode, Move bytecode to EVM bytecode, or Move source to Solidity? I assume the first one because of the annotations, but wanted to make sure I understand (and could also see value in the other two approaches).

In the first prototype, I plan to generate Solidity from the prover's stackless bytecode. Eventually, this should be a bytecode-to-bytecode transformation. We would need to access the attributes somehow for this.

> * If I compile the Move code examples here to Move bytecode and run them on the Move VM, then compile/run the same code on the EVM, what are the guarantees you are trying to provide (if any) about behavioral equivalence between the Move execution trace and the EVM execution trace? I can guess the answer includes something about the equivalence of changes to the Move and EVM global states, but the story on errors/gas in each trace is less clear to me.

Good questions. Since a "contract", which can consist of many modules, has its own private Move address space, the execution semantics would be different, but it could/should be made as compatible as possible. For gas, we would need to adopt to EVM. For error treatment (e.g. arithmetics) we should preserve the Move semantics by generating according code. In general, it would be crucial that we preserve as much as we can the "safety" aspects of Move, otherwise why would one want to use Move on EVM? How that looks like in detail has to be figured out.

**Comment by sblackshear** [comment]
Thanks, that helps a lot!

Variant of the second question: would you expect users to write tests in Move or in Solidity, and would the test runner execute Move or EVM bytecode?

**Comment by wrwg** [comment]
> Thanks, that helps a lot!
> 
> Variant of the second question: would you expect users to write tests in Move or in Solidity, and would the test runner execute Move or EVM bytecode?

Very good question. Executing Move within one EVM contract, and without cross-contract calls, should have the same semantics as the Move VM. So yes, Move unit tests should be applicable for the majority of the Move code,

If it comes to cross-contract calls, all bets are open.

**Review by DavidLDill — APPROVED** [review]

**Pull request merged**
