### PR TITLE
[test fix] yaml ends with new lines (now)

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Serde yaml now ends data to text with new lines, updates serde-yaml and a broken hardcoded test.

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

CI

## Related PRs

https://github.com/diem/diem/pull/7460

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M serde_yaml 0.8.16 (direct third-party, crates.io)
    * version upgraded from 0.8.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M serde_yaml 0.8.16 (direct third-party, crates.io)
    * version upgraded from 0.8.15
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M serde_yaml 0.8.16 (direct third-party, crates.io)
    * version upgraded from 0.8.15
    * (unchanged features: [none])
```

**Comment by sausagee** [comment]
It looks like the diff in version bump covers much more than the newline commit: https://github.com/dtolnay/serde-yaml/compare/0.8.15...0.8.16

**Comment by rexhoffman** [comment]
@sausagee the serde-yaml update necessitates the test fix, this is a fix of our code to adapt to a dependabot pr.

**Review by bmwill — APPROVED** [review]

**Pull request closed without merging**
