### PR TITLE
Add video embed component and update docs guide

### PR DESCRIPTION
**Pull request by oriooctopus**
This adds a helper component for video embeds, updates the v2-docs-guide with instructions, and also temporarily removes the multi step snippet from the v2 docs guide. The reason that is removed is because it currently has some buggy styling, and I don't think it's worth fixing until it's needed. It's the most complex component on the site, and so if I fixed it now, I wouldn't be surprised if I had to tweak it again 6 months from now when we did actually need it, so I think the most efficient thing to do is to wait until it's actually used. @JoelMarcey let me know if you disagree with this line of thinking

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@oriooctopus - Would this be something that should be added to the Docusaurus core instead?

**Comment by oriooctopus** [comment]
@JoelMarcey my gut says no, I think because my impression of the components in theme classic is that they are less a component library like material UI and more a way to provide a component basis for the default layout of docusaurus with things like a nav, sidebar, etc. There are some small components in there, such as tabs or arrows, but those are used by those other larger components anyways

But, if my understanding of their philosophy is wrong and they do imagine it container helper components, then I could definitely see a VideoEmbed component in there (with maybe a little bit more beefing up to handle more use cases)

**Comment by JoelMarcey** [comment]
@ericnakagawa What do you think about removing the multi-step code snippet guide here: https://developers.diem.com/docs/v2-docs-guide/#multi-step-code-snippet

**Comment by oriooctopus** [comment]
Spoke with Josh. We should hold off on fixing it until we actually have a use for the component.. I created a ticket here  https://app.asana.com/0/1194894027764377/1199690392291375/f

**Comment by JoelMarcey** [comment]
Should we close this then and then re-open when we are ready, in order to get it out of the open queue.

**Comment by oriooctopus** [comment]
@JoelMarcey this PR is still relevant since it has to do with embedding videos, it only minorly touches the multi step snippet, and just removes the code from the docs guide to avoid confusion

**Comment by JoelMarcey** [comment]
@oriooctopus So you still want me to review this PR as-is and approve?

**Review by jjwill — APPROVED** [review]
Small nit, LGTM after addressed

**Comment by JoelMarcey** [comment]
@oriooctopus -- AIUI, you may have land access on these PRs. Do you want to try landing this with the `[slash]land` option?

**Comment by davidiw** [comment]
hmm... while we're not technically leverage that doc stuff any more, it might be good to keep track of this....

Old PR, feel free to re-open.

**Pull request closed without merging**
