### PR TITLE
[move-model] executable spec

### PR DESCRIPTION
**Pull request by mengxu-fb**
**Exploration code, not ready for landing yet**

To test it: `mvp --spec-instrument <path-to-file>.move`

## Motivation

Part of the exploration on instrumenting specs into Move language

Also to check how CI reacts to the commits.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

CI

### CODE REVIEW

**Comment by sblackshear** [comment]
What does "instrumenting" mean here?

**Comment by mengxu-fb** [comment]
It means compiling (at least part of) spec blocks as executable Move bytecode, together with other normal Move code.

Right now the `spec {}` blocks are ignored in compilation, I am exploring whether I can instrument part of statements in the `spec {}` block as Move code. A typical example can be: `spec { assert x >= 10; }` ==> `if (x < 10) { abort 42; }`.

But of course, this is still in early exploration and it is unlikely that all statements allowed in the spec language can be converted easily. But at least it might be good to have a boundary.

The larger context why we are doing this is counterexample to unit-test conversion. Upon verification of a function, the Move prover might return a counterexample as well as the properties that are violated (e.g., some `assert` or `invariant`). We are exploring whether we could turn that counterexample as a unit test case for that function.

**Comment by sblackshear** [comment]
Executable counter-example generation would be very cool indeed!

**Comment by mengxu-fb** [comment]
Stale branch, closing

**Pull request closed without merging**
