### PR TITLE
Make it so that crates with the workspace-hack can be published to crates.io

### PR DESCRIPTION
**Pull request by sunshowers**
## Motivation

This patchset uses a trick to allow publishing crates depending on the workspace-hack to crates.io:
* locally, crates will continue to use the workspace-hack present in this repo
* when published to crates.io, they will instead depend on [the stub package present there](https://crates.io/crates/diem-workspace-hack).

Also move the workspace-hack dependency out of `[dev-dependencies]` (it works better that way), and add a lint check for it.

See the [cargo-hakari publishing docs](https://docs.rs/cargo-hakari/latest/cargo_hakari/publishing/index.html) for more information.

### CODE REVIEW

**Comment by sunshowers** [comment]
I had to keep the `diem-workspace-hack` name because duplicate package names apparently cause all sorts of fun issues in cargo, ugh :/

**Review by bmwill — APPROVED** [review]

**Review by vgao1996 — DISMISSED** [review]

**Comment by sunshowers** [comment]
Changes:
* Disable the workspace-hack for the powerpc build
* Revert changes to `scripts/weekly-dep-report.sh` so that it excludes `diem-workspace-hack` again

**Comment by bmwill** [comment]
Something doesn't look right, all the changes you made seem to be missing in this iteration?

**Comment by sunshowers** [comment]
> Something doesn't look right, all the changes you made seem to be missing in this iteration?

Yeah sorry, I pushed just an earlier commit by accident. I've fixed it up -- hope it passes tests this time :)

**Review by bmwill — APPROVED** [review]
/land

**Pull request closed without merging**
