### PR TITLE
[move-lang] Bug fixes associated with incorrect error gating

### PR DESCRIPTION
**Pull request by tnowacki**
- Fixed move_check tests to do code generation even with warnings
- Fixed so code generation does not happen if there are any errors
- Fixed some bugs resulting from this change

## Motivation

#9987
#9907 

## Test Plan

- Fixed tests 
- Added tests

### CODE REVIEW

**Review by tzakian — DISMISSED** [review]
LGTM!

**Review by modocache — APPROVED** [review]
Excellent, LGTM!

**Review by tzakian — DISMISSED** [review]

**Review by modocache — APPROVED** [review]

**Pull request merged**
