### PR TITLE
[sdk] clean up and consolidate verifying client logic

### PR DESCRIPTION
**Pull request by phlip9**
+ move into its own directory, since one file was starting to get a bit unwieldy
+ extract much of the IO-free logic into VerifyingBatch in preparation for BlockingVerifyingClient
+ clean up some other assorted things, like unnecessary error checks

Note: the  +/- numbers look scary, but the first few commits kind of inflate the numbers even though they're just moving code around.

### CODE REVIEW

**Review by bmwill — APPROVED** [review]
Cleanup looks good, thanks for providing good comments on some of the more tricky parts

**Comment by phlip9** [comment]
rebased

**Review by bmwill — APPROVED** [review]
/land

**Pull request closed without merging**
