### PR TITLE
[language] switch tests to exp mode -- move-lang/move/borrow

### PR DESCRIPTION
**Pull request by vgao1996**
Suspicious tests:
- `borrow_local_bad`: name doesn't seem to match test. I don't see why it's "bad".
- `borrow_parens`, `borrow_move_ok`: identical tests.

### CODE REVIEW

**Comment by tnowacki** [comment]
You can probably kill the identical tests (if you haven't already)

Borrow_local_bad.mvir is hilariously old. We could check the old pre-github commits, but my guess for why it used to be "bad"
A) You used to not be able to borrow immutable from a mutable reference (had to freeze first)
B) The test was invalid because of some rule in the old dynamic reference system (that I have now long forgotten about or how it works)
I would kill it and the equivalent .move version

**Review by sblackshear — APPROVED** [review]

**Comment by davidiw** [comment]
Old PR, feel free to re-open.

**Comment by bob-wilson** [comment]
@vgao1996 What happened with this?

**Comment by vgao1996** [comment]
@bob-wilson This one actually looks good, just need to make the changes Todd suggested and land it.

**Comment by vgao1996** [comment]
Closing since we decided to work on the new testing framework and then migrate the tests over there.

**Pull request closed without merging**
