### PR TITLE
[move-prover] Flag for running experimental pipeline

### PR DESCRIPTION
**Pull request by JakeSilverman**
## Motivation

Added a flag to run an experimental verification pipeline. This allows for easier benchmarking of experimental pipelines.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Review by shazqadeer — COMMENTED** [review]
Looks good to me.  If it simplifies the code in lib.rs, you could make the experimental flag work only for v2.  The non-v2 path will disappear eventually anyway.

**Review by shazqadeer — APPROVED** [review]
I will approve so you can land soon. Up to you whether you want to make  the change I suggested.

**Comment by JakeSilverman** [comment]
> Looks good to me. If it simplifies the code in lib.rs, you could make the experimental flag work only for v2. The non-v2 path will disappear eventually anyway.

I'll keep it as it is for now. Just one extra if statement at the time, easy to remove when non-v2 is taken out.

**Pull request closed without merging**
