### PR TITLE
Docs minor changes

### PR DESCRIPTION
**Pull request by nimishamw**
Minor updates to pages based on feedback and updating the dev docs README with the latest doc titles, links

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)

host packages:
  A paste 1.0.5 (direct third-party, crates.io)
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A consensus-notifications 0.1.0 (workspace, path 'state-sync/inter-component/consensus-notifications')
    * features: [none]
  A mempool-notifications 0.1.0 (workspace, path 'state-sync/inter-component/mempool-notifications')
    * features: [none]
  A state-sync-v1 0.1.0 (workspace, path 'state-sync/state-sync-v1')
    * features: default
  M rocksdb 0.17.0 (direct third-party, crates.io)
    * version upgraded from 0.15.0
    * (unchanged features: lz4)
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
  M librocksdb-sys 6.20.3 (transitive third-party, crates.io)
    * version upgraded from 6.11.4
    * (unchanged features: default, lz4, static)
  R state-sync 0.1.0 (workspace, path 'state-sync')
    * (old features: default)

host packages:
  A paste 1.0.5 (direct third-party, crates.io)
    * features: [none]
  A bitvec 0.19.5 (transitive third-party, crates.io)
    * features: alloc, std
  A funty 1.1.0 (transitive third-party, crates.io)
    * features: [none]
  A radium 0.5.3 (transitive third-party, crates.io)
    * features: [none]
  A tap 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  A wyz 0.2.0 (transitive third-party, crates.io)
    * features: alloc
  M bindgen 0.59.1 (transitive third-party, crates.io)
    * version upgraded from 0.54.0
    * removed features: clap, default, env_logger, log, logging, which, which-rustfmt
    * (unchanged features: runtime)
  M cexpr 0.5.0 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M clang-sys 1.2.1 (transitive third-party, crates.io)
    * version upgraded from 0.29.3
    * added features: clang_3_5, clang_3_6, clang_3_7, clang_3_8, clang_3_9, clang_4_0, clang_5_0
    * removed features: gte_clang_3_6, gte_clang_3_7, gte_clang_3_8, gte_clang_3_9, gte_clang_4_0, gte_clang_5_0, gte_clang_6_0
    * (unchanged features: clang_6_0, libloading, runtime)
  M libloading 0.7.0 (transitive third-party, crates.io)
    * version upgraded from 0.5.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * removed features: default
    * (unchanged features: std, use_std)
  M nom 6.1.2 (transitive third-party, crates.io)
    * version upgraded from 5.1.2
    * added features: bitvec, funty
    * (unchanged features: alloc, std)
  M regex 1.4.3 (transitive third-party, crates.io)
    * removed features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, thread_local
    * (unchanged features: std, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M regex-syntax 0.6.23 (transitive third-party, crates.io)
    * removed features: default
    * (unchanged features: unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M shlex 1.1.0 (transitive third-party, crates.io)
    * version upgraded from 0.1.1
    * added features: default, std
    * (unchanged features: [none])
  R aho-corasick 0.7.15 (transitive third-party, crates.io)
    * (old features: default, std)
  R ansi_term 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R atty 0.2.14 (transitive third-party, crates.io)
    * (old features: [none])
  R cfg-if 0.1.10 (transitive third-party, crates.io) (other versions: 1.0.0)
    * (old features: [none])
  R clap 2.33.3 (transitive third-party, crates.io)
    * (old features: ansi_term, atty, color, default, strsim, suggestions, vec_map)
  R env_logger 0.7.1 (transitive third-party, crates.io)
    * (old features: atty, default, humantime, regex, termcolor)
  R humantime 1.3.0 (transitive third-party, crates.io)
    * (old features: [none])
  R log 0.4.14 (transitive third-party, crates.io)
    * (old features: std)
  R quick-error 1.2.3 (transitive third-party, crates.io)
    * (old features: [none])
  R strsim 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])
  R termcolor 1.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R textwrap 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R thread_local 1.1.3 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-width 0.1.8 (transitive third-party, crates.io)
    * (old features: default)
  R vec_map 0.8.2 (transitive third-party, crates.io)
    * (old features: [none])
  R which 3.1.1 (transitive third-party, crates.io)
    * (old features: [none])
```

**Review by dahliamalkhi — DISMISSED** [review]
LGTM

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M thiserror 1.0.26 (direct third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)

host packages:
  M thiserror-impl 1.0.26 (transitive third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M thiserror 1.0.26 (direct third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
  M walkdir 2.3.2 (direct third-party, crates.io)
    * version upgraded from 2.3.1
    * (unchanged features: [none])
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)

host packages:
  A paste 1.0.5 (direct third-party, crates.io)
    * features: [none]
  M thiserror-impl 1.0.26 (transitive third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A consensus-notifications 0.1.0 (workspace, path 'state-sync/inter-component/consensus-notifications')
    * features: [none]
  A mempool-notifications 0.1.0 (workspace, path 'state-sync/inter-component/mempool-notifications')
    * features: [none]
  A state-sync-v1 0.1.0 (workspace, path 'state-sync/state-sync-v1')
    * features: default
  M rocksdb 0.17.0 (direct third-party, crates.io)
    * version upgraded from 0.15.0
    * (unchanged features: lz4)
  M thiserror 1.0.26 (direct third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
  M walkdir 2.3.2 (direct third-party, crates.io)
    * version upgraded from 2.3.1
    * (unchanged features: [none])
  M crossbeam-deque 0.8.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: crossbeam-epoch, crossbeam-utils, default, std)
  M librocksdb-sys 6.20.3 (transitive third-party, crates.io)
    * version upgraded from 6.11.4
    * (unchanged features: default, lz4, static)
  R state-sync 0.1.0 (workspace, path 'state-sync')
    * (old features: default)

host packages:
  A paste 1.0.5 (direct third-party, crates.io)
    * features: [none]
  A bitvec 0.19.5 (transitive third-party, crates.io)
    * features: alloc, std
  A funty 1.1.0 (transitive third-party, crates.io)
    * features: [none]
  A radium 0.5.3 (transitive third-party, crates.io)
    * features: [none]
  A tap 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  A wyz 0.2.0 (transitive third-party, crates.io)
    * features: alloc
  M bindgen 0.59.1 (transitive third-party, crates.io)
    * version upgraded from 0.54.0
    * removed features: clap, default, env_logger, log, logging, which, which-rustfmt
    * (unchanged features: runtime)
  M cexpr 0.5.0 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M clang-sys 1.2.1 (transitive third-party, crates.io)
    * version upgraded from 0.29.3
    * added features: clang_3_5, clang_3_6, clang_3_7, clang_3_8, clang_3_9, clang_4_0, clang_5_0
    * removed features: gte_clang_3_6, gte_clang_3_7, gte_clang_3_8, gte_clang_3_9, gte_clang_4_0, gte_clang_5_0, gte_clang_6_0
    * (unchanged features: clang_6_0, libloading, runtime)
  M libloading 0.7.0 (transitive third-party, crates.io)
    * version upgraded from 0.5.2
    * (unchanged features: [none])
  M memchr 2.4.0 (transitive third-party, crates.io)
    * removed features: default
    * (unchanged features: std, use_std)
  M nom 6.1.2 (transitive third-party, crates.io)
    * version upgraded from 5.1.2
    * added features: bitvec, funty
    * (unchanged features: alloc, std)
  M regex 1.4.3 (transitive third-party, crates.io)
    * removed features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, thread_local
    * (unchanged features: std, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M regex-syntax 0.6.23 (transitive third-party, crates.io)
    * removed features: default
    * (unchanged features: unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M shlex 1.1.0 (transitive third-party, crates.io)
    * version upgraded from 0.1.1
    * added features: default, std
    * (unchanged features: [none])
  M thiserror-impl 1.0.26 (transitive third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
  R aho-corasick 0.7.15 (transitive third-party, crates.io)
    * (old features: default, std)
  R ansi_term 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R atty 0.2.14 (transitive third-party, crates.io)
    * (old features: [none])
  R cfg-if 0.1.10 (transitive third-party, crates.io) (other versions: 1.0.0)
    * (old features: [none])
  R clap 2.33.3 (transitive third-party, crates.io)
    * (old features: ansi_term, atty, color, default, strsim, suggestions, vec_map)
  R env_logger 0.7.1 (transitive third-party, crates.io)
    * (old features: atty, default, humantime, regex, termcolor)
  R humantime 1.3.0 (transitive third-party, crates.io)
    * (old features: [none])
  R log 0.4.14 (transitive third-party, crates.io)
    * (old features: std)
  R quick-error 1.2.3 (transitive third-party, crates.io)
    * (old features: [none])
  R strsim 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])
  R termcolor 1.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R textwrap 0.11.0 (transitive third-party, crates.io)
    * (old features: [none])
  R thread_local 1.1.3 (transitive third-party, crates.io)
    * (old features: [none])
  R unicode-width 0.1.8 (transitive third-party, crates.io)
    * (old features: default)
  R vec_map 0.8.2 (transitive third-party, crates.io)
    * (old features: [none])
  R which 3.1.1 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M thiserror 1.0.26 (direct third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])

host packages:
  M thiserror-impl 1.0.26 (transitive third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M thiserror 1.0.26 (direct third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
  M walkdir 2.3.2 (direct third-party, crates.io)
    * version upgraded from 2.3.1
    * (unchanged features: [none])

host packages:
  M thiserror-impl 1.0.26 (transitive third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M thiserror 1.0.26 (direct third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
  M walkdir 2.3.2 (direct third-party, crates.io)
    * version upgraded from 2.3.1
    * (unchanged features: [none])

host packages:
  M thiserror-impl 1.0.26 (transitive third-party, crates.io)
    * version upgraded from 1.0.24
    * (unchanged features: [none])
```

**Review by CapCap — APPROVED** [review]
/land

**Pull request merged**
