### PR TITLE
[deps] update transitive deps

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Update transitive deps, not handled by dependabot.

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

CI

## Related PRs

None

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M adler 1.0.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M chunked_transfer 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M form_urlencoded 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  M idna 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M libc 0.2.88 (transitive third-party, crates.io)
    * version upgraded from 0.2.87
    * (unchanged features: default, std)
  M linked-hash-map 0.5.4 (transitive third-party, crates.io)
    * version upgraded from 0.5.3
    * (unchanged features: [none])
  M miniz_oxide 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.3
    * (unchanged features: [none])
  M parking_lot_core 0.8.3 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: [none])
  M thread_local 1.1.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: [none])
  M tinyvec 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, default, tinyvec_macros)
  M unicode-normalization 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: default, std)

host packages:
  M syn 1.0.61 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M adler 1.0.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M chunked_transfer 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.3 (transitive third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: alloc, lazy_static, std)
  M encoding_rs 0.8.28 (transitive third-party, crates.io)
    * version upgraded from 0.8.26
    * (unchanged features: [none])
  M form_urlencoded 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  M getrandom 0.1.16 (transitive third-party, crates.io) (other versions: 0.2.2)
    * version upgraded from 0.1.15
    * (unchanged features: std)
  M h2 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M http 0.2.3 (transitive third-party, crates.io)
    * version upgraded from 0.2.2
    * (unchanged features: [none])
  M httparse 1.3.5 (transitive third-party, crates.io)
    * version upgraded from 1.3.4
    * (unchanged features: default, std)
  M idna 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M indexmap 1.6.1 (transitive third-party, crates.io)
    * added features: std
    * (unchanged features: [none])
  M libc 0.2.88 (transitive third-party, crates.io)
    * version upgraded from 0.2.87
    * (unchanged features: align, default, std)
  M linked-hash-map 0.5.4 (transitive third-party, crates.io)
    * version upgraded from 0.5.3
    * (unchanged features: [none])
  M miniz_oxide 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.3
    * (unchanged features: [none])
  M mio 0.7.9 (transitive third-party, crates.io)
    * version upgraded from 0.7.7
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M parking_lot_core 0.8.3 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: [none])
  M pin-project-lite 0.2.6 (transitive third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: [none])
  M proc-macro-nested 0.1.7 (transitive third-party, crates.io)
    * version upgraded from 0.1.6
    * (unchanged features: [none])
  M thread_local 1.1.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: [none])
  M tinyvec 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, default, tinyvec_macros)
  M tower-service 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M unicode-normalization 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: default, std)
  R bytes 0.5.6 (transitive third-party, crates.io) (other versions: 1.0.1)
    * (old features: default, std)
  R cfg-if 0.1.10 (transitive third-party, crates.io) (other versions: 1.0.0)
    * (old features: [none])
  R pin-project 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
  R tracing-futures 0.2.4 (transitive third-party, crates.io)
    * (old features: pin-project, std-future)

host packages:
  M syn 1.0.61 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  R const_fn 0.4.5 (transitive third-party, crates.io)
    * (old features: [none])
  R pin-project-internal 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M adler 1.0.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M chunked_transfer 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.3 (transitive third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: alloc, lazy_static, std)
  M encoding_rs 0.8.28 (transitive third-party, crates.io)
    * version upgraded from 0.8.26
    * (unchanged features: [none])
  M form_urlencoded 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  M futures 0.1.31 (transitive third-party, crates.io) (other versions: 0.3.12)
    * version upgraded from 0.1.30
    * (unchanged features: default, use_std, with-deprecated)
  M getrandom 0.1.16 (transitive third-party, crates.io) (other versions: 0.2.2)
    * version upgraded from 0.1.15
    * (unchanged features: std)
  M h2 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M headers 0.3.4 (transitive third-party, crates.io)
    * version upgraded from 0.3.2
    * (unchanged features: [none])
  M http 0.2.3 (transitive third-party, crates.io)
    * version upgraded from 0.2.2
    * (unchanged features: [none])
  M httparse 1.3.5 (transitive third-party, crates.io)
    * version upgraded from 1.3.4
    * (unchanged features: default, std)
  M idna 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M indexmap 1.6.1 (transitive third-party, crates.io)
    * added features: std
    * (unchanged features: [none])
  M libc 0.2.88 (transitive third-party, crates.io)
    * version upgraded from 0.2.87
    * (unchanged features: align, default, std)
  M linked-hash-map 0.5.4 (transitive third-party, crates.io)
    * version upgraded from 0.5.3
    * (unchanged features: [none])
  M miniz_oxide 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.3
    * (unchanged features: [none])
  M mio 0.7.9 (transitive third-party, crates.io)
    * version upgraded from 0.7.7
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M multipart 0.17.1 (transitive third-party, crates.io)
    * version upgraded from 0.17.0
    * (unchanged features: buf_redux, httparse, quick-error, safemem, server, twoway)
  M num-bigint 0.3.2 (transitive third-party, crates.io)
    * version upgraded from 0.3.1
    * (unchanged features: std)
  M parking_lot_core 0.8.3 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: [none])
  M pin-project-lite 0.2.6 (transitive third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: [none])
  M proc-macro-nested 0.1.7 (transitive third-party, crates.io)
    * version upgraded from 0.1.6
    * (unchanged features: [none])
  M ring 0.16.20 (transitive third-party, crates.io)
    * version upgraded from 0.16.19
    * (unchanged features: alloc, default, dev_urandom_fallback, once_cell)
  M smawk 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M thread_local 1.1.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: [none])
  M tinyvec 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, default, tinyvec_macros)
  M tower-service 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M tracing-futures 0.2.5 (transitive third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: pin-project, std-future)
  M unicode-normalization 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: default, std)
  R base64 0.12.3 (transitive third-party, crates.io) (other versions: 0.13.0)
    * (old features: default, std)
  R block-buffer 0.7.3 (transitive third-party, crates.io) (other versions: 0.9.0)
    * (old features: [none])
  R block-padding 0.1.5 (transitive third-party, crates.io)
    * (old features: [none])
  R byte-tools 0.3.1 (transitive third-party, crates.io)
    * (old features: [none])
  R bytes 0.5.6 (transitive third-party, crates.io) (other versions: 1.0.1)
    * (old features: default, std)
  R digest 0.8.1 (transitive third-party, crates.io) (other versions: 0.9.0)
    * (old features: std)
  R fake-simd 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R generic-array 0.12.4 (transitive third-party, crates.io) (other versions: 0.14.4)
    * (old features: [none])
  R opaque-debug 0.2.3 (transitive third-party, crates.io) (other versions: 0.3.0)
    * (old features: [none])
  R pin-project 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
  R rand 0.6.5 (transitive third-party, crates.io) (other versions: 0.4.6, 0.7.3, 0.8.3)
    * (old features: alloc, default, rand_os, std)
  R rand_chacha 0.1.1 (transitive third-party, crates.io) (other versions: 0.2.2, 0.3.0)
    * (old features: [none])
  R rand_core 0.3.1 (transitive third-party, crates.io) (other versions: 0.5.1, 0.6.2)
    * (old features: [none])
  R rand_core 0.4.2 (transitive third-party, crates.io) (other versions: 0.5.1, 0.6.2)
    * (old features: alloc, std)
  R rand_hc 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_isaac 0.1.1 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_jitter 0.1.4 (transitive third-party, crates.io)
    * (old features: std)
  R rand_os 0.1.3 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_pcg 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_xorshift 0.1.1 (transitive third-party, crates.io)
    * (old features: [none])
  R sha-1 0.8.2 (transitive third-party, crates.io) (other versions: 0.9.4)
    * (old features: default, std)

host packages:
  M async-trait 0.1.45 (direct third-party, crates.io)
    * version upgraded from 0.1.42
    * (unchanged features: [none])
  M syn 1.0.61 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: clone-impls, default, derive, extra-traits, fold, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M libc 0.2.88 (transitive third-party, crates.io)
    * version upgraded from 0.2.87
    * (unchanged features: default, std)
  M thread_local 1.1.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: [none])
  R autocfg 0.1.7 (transitive third-party, crates.io) (other versions: 1.0.1)
    * (old features: [none])
  R const_fn 0.4.5 (transitive third-party, crates.io)
    * (old features: [none])
  R pin-project-internal 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
```

**Review by bmwill — APPROVED** [review]
Seems like you just need to update the workspace hack crate then this will be good to go.

**Comment by rexhoffman** [comment]
Indeed, wish I'd landed this before the other prs this morning.   sigh.   taking a weekend makes me forget about prs apparently.

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M prometheus 0.12.0 (direct third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: [none])
  M adler 1.0.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M chunked_transfer 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.3 (transitive third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: alloc, lazy_static, std)
  M encoding_rs 0.8.28 (transitive third-party, crates.io)
    * version upgraded from 0.8.26
    * (unchanged features: [none])
  M form_urlencoded 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  M getrandom 0.1.16 (transitive third-party, crates.io) (other versions: 0.2.2)
    * version upgraded from 0.1.15
    * (unchanged features: std)
  M h2 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M http 0.2.3 (transitive third-party, crates.io)
    * version upgraded from 0.2.2
    * (unchanged features: [none])
  M httparse 1.3.5 (transitive third-party, crates.io)
    * version upgraded from 1.3.4
    * (unchanged features: default, std)
  M idna 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M indexmap 1.6.2 (transitive third-party, crates.io)
    * added features: std
    * (unchanged features: [none])
  M linked-hash-map 0.5.4 (transitive third-party, crates.io)
    * version upgraded from 0.5.3
    * (unchanged features: [none])
  M memchr 2.3.4 (transitive third-party, crates.io)
    * removed features: use_std
    * (unchanged features: default, std)
  M miniz_oxide 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.3
    * (unchanged features: [none])
  M mio 0.7.9 (transitive third-party, crates.io)
    * version upgraded from 0.7.7
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M parking_lot_core 0.8.3 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: [none])
  M pin-project-lite 0.2.6 (transitive third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: [none])
  M proc-macro-nested 0.1.7 (transitive third-party, crates.io)
    * version upgraded from 0.1.6
    * (unchanged features: [none])
  M tinyvec 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, default, tinyvec_macros)
  M tower-service 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M unicode-normalization 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: default, std)
  R aho-corasick 0.7.15 (transitive third-party, crates.io)
    * (old features: default, std)
  R bytes 0.5.6 (transitive third-party, crates.io) (other versions: 1.0.1)
    * (old features: default, std)
  R cfg-if 0.1.10 (transitive third-party, crates.io) (other versions: 1.0.0)
    * (old features: [none])
  R pin-project 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
  R regex 1.4.3 (transitive third-party, crates.io)
    * (old features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, std, thread_local, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  R regex-syntax 0.6.22 (transitive third-party, crates.io)
    * (old features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  R thread_local 1.0.1 (transitive third-party, crates.io)
    * (old features: [none])
  R tracing-futures 0.2.4 (transitive third-party, crates.io)
    * (old features: pin-project, std-future)

host packages:
  M syn 1.0.62 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  R const_fn 0.4.5 (transitive third-party, crates.io)
    * (old features: [none])
  R pin-project-internal 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M prometheus 0.12.0 (direct third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: [none])
  M adler 1.0.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M chunked_transfer 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.3 (transitive third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: alloc, lazy_static, std)
  M encoding_rs 0.8.28 (transitive third-party, crates.io)
    * version upgraded from 0.8.26
    * (unchanged features: [none])
  M form_urlencoded 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  M getrandom 0.1.16 (transitive third-party, crates.io) (other versions: 0.2.2)
    * version upgraded from 0.1.15
    * (unchanged features: std)
  M h2 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M headers 0.3.4 (transitive third-party, crates.io)
    * version upgraded from 0.3.2
    * (unchanged features: [none])
  M http 0.2.3 (transitive third-party, crates.io)
    * version upgraded from 0.2.2
    * (unchanged features: [none])
  M httparse 1.3.5 (transitive third-party, crates.io)
    * version upgraded from 1.3.4
    * (unchanged features: default, std)
  M idna 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M indexmap 1.6.2 (transitive third-party, crates.io)
    * added features: std
    * (unchanged features: [none])
  M linked-hash-map 0.5.4 (transitive third-party, crates.io)
    * version upgraded from 0.5.3
    * (unchanged features: [none])
  M miniz_oxide 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.3
    * (unchanged features: [none])
  M mio 0.7.9 (transitive third-party, crates.io)
    * version upgraded from 0.7.7
    * (unchanged features: default, net, os-ext, os-poll, os-util, tcp, udp, uds)
  M multipart 0.17.1 (transitive third-party, crates.io)
    * version upgraded from 0.17.0
    * (unchanged features: buf_redux, httparse, quick-error, safemem, server, twoway)
  M parking_lot_core 0.8.3 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: [none])
  M pin-project-lite 0.2.6 (transitive third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: [none])
  M proc-macro-nested 0.1.7 (transitive third-party, crates.io)
    * version upgraded from 0.1.6
    * (unchanged features: [none])
  M ring 0.16.20 (transitive third-party, crates.io)
    * version upgraded from 0.16.19
    * (unchanged features: alloc, default, dev_urandom_fallback, once_cell)
  M smawk 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M thread_local 1.1.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: [none])
  M tinyvec 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, default, tinyvec_macros)
  M tower-service 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: [none])
  M tracing-futures 0.2.5 (transitive third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: pin-project, std-future)
  M unicode-normalization 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: default, std)
  R base64 0.12.3 (transitive third-party, crates.io) (other versions: 0.13.0)
    * (old features: default, std)
  R block-buffer 0.7.3 (transitive third-party, crates.io) (other versions: 0.9.0)
    * (old features: [none])
  R block-padding 0.1.5 (transitive third-party, crates.io)
    * (old features: [none])
  R byte-tools 0.3.1 (transitive third-party, crates.io)
    * (old features: [none])
  R bytes 0.5.6 (transitive third-party, crates.io) (other versions: 1.0.1)
    * (old features: default, std)
  R cfg-if 0.1.10 (transitive third-party, crates.io) (other versions: 1.0.0)
    * (old features: [none])
  R digest 0.8.1 (transitive third-party, crates.io) (other versions: 0.9.0)
    * (old features: std)
  R fake-simd 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R generic-array 0.12.4 (transitive third-party, crates.io) (other versions: 0.14.4)
    * (old features: [none])
  R opaque-debug 0.2.3 (transitive third-party, crates.io) (other versions: 0.3.0)
    * (old features: [none])
  R pin-project 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
  R rand 0.6.5 (transitive third-party, crates.io) (other versions: 0.7.3, 0.8.3)
    * (old features: alloc, default, rand_os, std)
  R rand_chacha 0.1.1 (transitive third-party, crates.io) (other versions: 0.2.2, 0.3.0)
    * (old features: [none])
  R rand_core 0.3.1 (transitive third-party, crates.io) (other versions: 0.5.1, 0.6.2)
    * (old features: [none])
  R rand_core 0.4.2 (transitive third-party, crates.io) (other versions: 0.5.1, 0.6.2)
    * (old features: alloc, std)
  R rand_hc 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_isaac 0.1.1 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_jitter 0.1.4 (transitive third-party, crates.io)
    * (old features: std)
  R rand_os 0.1.3 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_pcg 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R rand_xorshift 0.1.1 (transitive third-party, crates.io)
    * (old features: [none])
  R sha-1 0.8.2 (transitive third-party, crates.io) (other versions: 0.9.4)
    * (old features: default, std)

host packages:
  M async-trait 0.1.48 (direct third-party, crates.io)
    * version upgraded from 0.1.42
    * (unchanged features: [none])
  M syn 1.0.62 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: clone-impls, default, derive, extra-traits, fold, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M thread_local 1.1.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: [none])
  R autocfg 0.1.7 (transitive third-party, crates.io) (other versions: 1.0.1)
    * (old features: [none])
  R const_fn 0.4.5 (transitive third-party, crates.io)
    * (old features: [none])
  R pin-project-internal 0.4.27 (transitive third-party, crates.io) (other versions: 1.0.5)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M prometheus 0.12.0 (direct third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: [none])
  M adler 1.0.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.3
    * (unchanged features: [none])
  M chunked_transfer 1.4.0 (transitive third-party, crates.io)
    * version upgraded from 1.3.0
    * (unchanged features: [none])
  M form_urlencoded 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  M idna 0.2.2 (transitive third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M linked-hash-map 0.5.4 (transitive third-party, crates.io)
    * version upgraded from 0.5.3
    * (unchanged features: [none])
  M memchr 2.3.4 (transitive third-party, crates.io)
    * removed features: use_std
    * (unchanged features: default, std)
  M miniz_oxide 0.4.4 (transitive third-party, crates.io)
    * version upgraded from 0.4.3
    * (unchanged features: [none])
  M parking_lot_core 0.8.3 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: [none])
  M tinyvec 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, default, tinyvec_macros)
  M unicode-normalization 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: default, std)
  R aho-corasick 0.7.15 (transitive third-party, crates.io)
    * (old features: default, std)
  R regex 1.4.3 (transitive third-party, crates.io)
    * (old features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, std, thread_local, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  R regex-syntax 0.6.22 (transitive third-party, crates.io)
    * (old features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  R thread_local 1.0.1 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  M syn 1.0.62 (direct third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
```

**Comment by rexhoffman** [comment]
/cancel incase bmwill's pr doesn't land.  pretty sure these will conflict.

**Pull request merged**
