### PR TITLE
Diem Framework releases from packages

### PR DESCRIPTION
**Pull request by tzakian**
This PR adds support for generating multiple different releases of the different Diem frameworks (DPN, core, and experimental). In particular, this PR:
* Makes the compilation and generation of releases to be based on the package system. This allows creation of releases from the different frameworks.
* Adds a generic interface to load releases (other than the DPN release) see the `ReleaseFetcher` implementation.

To do this:
* The package system has been changed to support an "install dir" as well as to use relative paths as opposed to absolute paths in the generated output to make packages more portable throughout the file system (Note: the source maps still hold absolute paths, but this will be fixed in a subsequent PR, for now we remove them).
* This fixes issues where the package hashes could be unstable due to different iteration orderings on different file systems
* This fixes an issue in the documentation generator where table-of-contents items were leaking from one root template to another. 

This PR is split into two commits:
* The base commit is all of the interesting changes (rust code, configs etc.)
* The top commit is all of the newly generated files

### CODE REVIEW

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` Cargo.toml `
   * ` src/lib.rs `
   * ` .github/workflows/rust.yml `
   * ` .cargo_vcs_info.json `
   * ` Cargo.toml.orig `
</details>
</details>

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` .cargo_vcs_info.json `
   * ` .github/workflows/rust.yml `
   * ` Cargo.toml `
   * ` Cargo.toml.orig `
   * ` src/lib.rs `
</details>
</details>

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  A checksumdir 0.3.0 (direct third-party, crates.io)
    * features: [none]
  A base64 0.10.1 (transitive third-party, crates.io) (other versions: 0.13.0)
    * features: [none]
  A blake2 0.8.1 (transitive third-party, crates.io)
    * features: default, std
  A byte-tools 0.3.1 (transitive third-party, crates.io)
    * features: [none]
  A crypto-mac 0.7.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: std
  A digest 0.8.1 (transitive third-party, crates.io) (other versions: 0.9.0)
    * features: std
  A generic-array 0.12.4 (transitive third-party, crates.io) (other versions: 0.14.4)
    * features: [none]
  A opaque-debug 0.2.3 (transitive third-party, crates.io) (other versions: 0.3.0)
    * features: [none]
  A subtle 1.0.0 (transitive third-party, crates.io) (other versions: 2.4.0)
    * features: [none]
  M byteorder 1.4.3 (transitive third-party, crates.io)
    * added features: default, std
    * (unchanged features: i128)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  A checksumdir 0.3.0 (direct third-party, crates.io)
    * features: [none]
  A base64 0.10.1 (transitive third-party, crates.io) (other versions: 0.13.0)
    * features: [none]
  A blake2 0.8.1 (transitive third-party, crates.io)
    * features: default, std
  A byte-tools 0.3.1 (transitive third-party, crates.io)
    * features: [none]
  A crypto-mac 0.7.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: std
  A digest 0.8.1 (transitive third-party, crates.io) (other versions: 0.9.0)
    * features: std
  A generic-array 0.12.4 (transitive third-party, crates.io) (other versions: 0.14.4)
    * features: [none]
  A opaque-debug 0.2.3 (transitive third-party, crates.io) (other versions: 0.3.0)
    * features: [none]
  A subtle 1.0.0 (transitive third-party, crates.io) (other versions: 2.4.0)
    * features: [none]
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  A checksumdir 0.3.0 (direct third-party, crates.io)
    * features: [none]
  A base64 0.10.1 (transitive third-party, crates.io) (other versions: 0.13.0)
    * features: [none]
  A blake2 0.8.1 (transitive third-party, crates.io)
    * features: default, std
  A byte-tools 0.3.1 (transitive third-party, crates.io)
    * features: [none]
  A crypto-mac 0.7.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: std
  A digest 0.8.1 (transitive third-party, crates.io) (other versions: 0.9.0)
    * features: std
  A generic-array 0.12.4 (transitive third-party, crates.io) (other versions: 0.14.4)
    * features: [none]
  A opaque-debug 0.2.3 (transitive third-party, crates.io) (other versions: 0.3.0)
    * features: [none]
  A subtle 1.0.0 (transitive third-party, crates.io) (other versions: 2.4.0)
    * features: [none]
  M byteorder 1.4.3 (transitive third-party, crates.io)
    * added features: default, std
    * (unchanged features: i128)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  A checksumdir 0.3.0 (direct third-party, crates.io)
    * features: [none]
  A base64 0.10.1 (transitive third-party, crates.io) (other versions: 0.13.0)
    * features: [none]
  A blake2 0.8.1 (transitive third-party, crates.io)
    * features: default, std
  A byte-tools 0.3.1 (transitive third-party, crates.io)
    * features: [none]
  A crypto-mac 0.7.0 (transitive third-party, crates.io) (other versions: 0.10.0)
    * features: std
  A digest 0.8.1 (transitive third-party, crates.io) (other versions: 0.9.0)
    * features: std
  A generic-array 0.12.4 (transitive third-party, crates.io) (other versions: 0.14.4)
    * features: [none]
  A opaque-debug 0.2.3 (transitive third-party, crates.io) (other versions: 0.3.0)
    * features: [none]
  A subtle 1.0.0 (transitive third-party, crates.io) (other versions: 2.4.0)
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` .cargo_vcs_info.json `
   * ` Cargo.toml.orig `
   * ` src/lib.rs `
   * ` .github/workflows/rust.yml `
   * ` Cargo.toml `
</details>
</details>

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: default
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: default
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` Cargo.toml.orig `
   * ` src/lib.rs `
   * ` .github/workflows/rust.yml `
   * ` .cargo_vcs_info.json `
   * ` Cargo.toml `
</details>
</details>

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: default
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` Cargo.toml.orig `
   * ` .github/workflows/rust.yml `
   * ` Cargo.toml `
   * ` .cargo_vcs_info.json `
   * ` src/lib.rs `
</details>
</details>

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` src/lib.rs `
   * ` .github/workflows/rust.yml `
   * ` Cargo.toml `
   * ` .cargo_vcs_info.json `
   * ` Cargo.toml.orig `
</details>
</details>

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` .cargo_vcs_info.json `
   * ` Cargo.toml `
   * ` Cargo.toml.orig `
   * ` src/lib.rs `
   * ` .github/workflows/rust.yml `
</details>
</details>

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
## Dependency update review
### pathdiff updated: 0.2.0 --> 0.2.1

<table><tr><td>No known advisories</td><td>:white_check_mark:</td></tr><tr><td>No change in the build script</td><td>:white_check_mark:</td></tr><tr><td>No change in any file with unsafe code</td><td>:white_check_mark:</td></tr><tr><td>The source and crates.io code are the same</td><td>:white_check_mark:</td></tr></table>

<details>
	<summary>Cilck to show details</summary><br>
<details>
	<summary>Click to show version diff summary</summary><br>
<table><tr><td>total files changed</td><td>5</td></tr><tr><td>total rust files changed</td><td>1</td></tr><tr><td>total loc change</td><td>199</td></tr></table>
</details><details>
	<summary>Click to show changed files</summary><br>

   * ` .cargo_vcs_info.json `
   * ` .github/workflows/rust.yml `
   * ` Cargo.toml.orig `
   * ` Cargo.toml `
   * ` src/lib.rs `
</details>
</details>

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A framework-releases 0.1.0 (workspace, path 'language/diem-framework/releases')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A move-bytecode-utils 0.1.0 (workspace, path 'language/tools/move-bytecode-utils')
    * features: [none]
  A move-package 0.1.0 (workspace, path 'language/tools/move-package')
    * features: [none]
  M include_dir 0.6.0 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: default, glob, search)
```

**Review by emmazzz — APPROVED** [review]
LGTM!

**Pull request closed without merging**
