### PR TITLE
Add support for printing in-scope named addresses and values from Move packages

### PR DESCRIPTION
**Pull request by DreamLinuxer**
## Motivation

Issue #9788

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A ptree 0.4.0 (direct third-party, crates.io)
    * features: ansi, ansi_term, atty, conf, config, default, directories, petgraph, serde-value, tint, value
  A config 0.11.0 (transitive third-party, crates.io)
    * features: default, hjson, ini, json, rust-ini, serde-hjson, serde_json, toml, yaml, yaml-rust
  A directories 4.0.1 (transitive third-party, crates.io)
    * features: [none]
  A dirs-sys 0.3.6 (transitive third-party, crates.io)
    * features: [none]
  A fixedbitset 0.4.0 (transitive third-party, crates.io) (other versions: 0.2.0)
    * features: [none]
  A lazy_static 0.2.11 (transitive third-party, crates.io) (other versions: 1.4.0)
    * features: [none]
  A lexical-core 0.7.6 (transitive third-party, crates.io)
    * features: arrayvec, correct, default, ryu, static_assertions, std, table
  A nom 5.1.2 (transitive third-party, crates.io)
    * features: alloc, default, lexical, lexical-core, std
  A num-traits 0.1.43 (transitive third-party, crates.io)
    * features: [none]
  A ordered-float 2.1.1 (transitive third-party, crates.io)
    * features: default, std
  A petgraph 0.6.0 (transitive third-party, crates.io) (other versions: 0.5.1)
    * features: default, graphmap, matrix_graph, stable_graph
  A rust-ini 0.13.0 (transitive third-party, crates.io)
    * features: [none]
  A serde 0.8.23 (transitive third-party, crates.io) (other versions: 1.0.130)
    * features: default, std
  A serde-hjson 0.9.1 (transitive third-party, crates.io)
    * features: [none]
  A serde-value 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A tint 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M arrayvec 0.5.2 (transitive third-party, crates.io)
    * added features: array-sizes-33-128
    * (unchanged features: default, std)
  M num-traits 0.2.14 (transitive third-party, crates.io)
    * added features: default
    * (unchanged features: i128, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A ptree 0.4.0 (direct third-party, crates.io)
    * features: ansi, ansi_term, atty, conf, config, default, directories, petgraph, serde-value, tint, value
  A config 0.11.0 (transitive third-party, crates.io)
    * features: default, hjson, ini, json, rust-ini, serde-hjson, serde_json, toml, yaml, yaml-rust
  A directories 4.0.1 (transitive third-party, crates.io)
    * features: [none]
  A dirs-sys 0.3.6 (transitive third-party, crates.io)
    * features: [none]
  A fixedbitset 0.4.0 (transitive third-party, crates.io) (other versions: 0.2.0)
    * features: [none]
  A lazy_static 0.2.11 (transitive third-party, crates.io) (other versions: 1.4.0)
    * features: [none]
  A lexical-core 0.7.6 (transitive third-party, crates.io)
    * features: arrayvec, correct, default, ryu, static_assertions, std, table
  A nom 5.1.2 (transitive third-party, crates.io)
    * features: alloc, default, lexical, lexical-core, std
  A num-traits 0.1.43 (transitive third-party, crates.io) (other versions: 0.2.14)
    * features: [none]
  A ordered-float 2.1.1 (transitive third-party, crates.io)
    * features: default, std
  A petgraph 0.6.0 (transitive third-party, crates.io) (other versions: 0.5.1)
    * features: default, graphmap, matrix_graph, stable_graph
  A rust-ini 0.13.0 (transitive third-party, crates.io)
    * features: [none]
  A serde 0.8.23 (transitive third-party, crates.io) (other versions: 1.0.130)
    * features: default, std
  A serde-hjson 0.9.1 (transitive third-party, crates.io)
    * features: [none]
  A serde-value 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A tint 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M arrayvec 0.5.2 (transitive third-party, crates.io)
    * added features: array-sizes-33-128
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A ptree 0.4.0 (direct third-party, crates.io)
    * features: ansi, ansi_term, atty, conf, config, default, directories, petgraph, serde-value, tint, value
  A config 0.11.0 (transitive third-party, crates.io)
    * features: default, hjson, ini, json, rust-ini, serde-hjson, serde_json, toml, yaml, yaml-rust
  A directories 4.0.1 (transitive third-party, crates.io)
    * features: [none]
  A dirs-sys 0.3.6 (transitive third-party, crates.io)
    * features: [none]
  A fixedbitset 0.4.0 (transitive third-party, crates.io) (other versions: 0.2.0)
    * features: [none]
  A lazy_static 0.2.11 (transitive third-party, crates.io) (other versions: 1.4.0)
    * features: [none]
  A lexical-core 0.7.6 (transitive third-party, crates.io)
    * features: arrayvec, correct, default, ryu, static_assertions, std, table
  A nom 5.1.2 (transitive third-party, crates.io)
    * features: alloc, default, lexical, lexical-core, std
  A num-traits 0.1.43 (transitive third-party, crates.io)
    * features: [none]
  A ordered-float 2.1.1 (transitive third-party, crates.io)
    * features: default, std
  A petgraph 0.6.0 (transitive third-party, crates.io) (other versions: 0.5.1)
    * features: default, graphmap, matrix_graph, stable_graph
  A rust-ini 0.13.0 (transitive third-party, crates.io)
    * features: [none]
  A serde 0.8.23 (transitive third-party, crates.io) (other versions: 1.0.130)
    * features: default, std
  A serde-hjson 0.9.1 (transitive third-party, crates.io)
    * features: [none]
  A serde-value 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A tint 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M arrayvec 0.5.2 (transitive third-party, crates.io)
    * added features: array-sizes-33-128
    * (unchanged features: default, std)
  M num-traits 0.2.14 (transitive third-party, crates.io)
    * added features: default
    * (unchanged features: i128, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A ptree 0.4.0 (direct third-party, crates.io)
    * features: ansi, ansi_term, atty, conf, config, default, directories, petgraph, serde-value, tint, value
  A config 0.11.0 (transitive third-party, crates.io)
    * features: default, hjson, ini, json, rust-ini, serde-hjson, serde_json, toml, yaml, yaml-rust
  A directories 4.0.1 (transitive third-party, crates.io)
    * features: [none]
  A dirs-sys 0.3.6 (transitive third-party, crates.io)
    * features: [none]
  A fixedbitset 0.4.0 (transitive third-party, crates.io) (other versions: 0.2.0)
    * features: [none]
  A lazy_static 0.2.11 (transitive third-party, crates.io) (other versions: 1.4.0)
    * features: [none]
  A lexical-core 0.7.6 (transitive third-party, crates.io)
    * features: arrayvec, correct, default, ryu, static_assertions, std, table
  A nom 5.1.2 (transitive third-party, crates.io)
    * features: alloc, default, lexical, lexical-core, std
  A num-traits 0.1.43 (transitive third-party, crates.io) (other versions: 0.2.14)
    * features: [none]
  A ordered-float 2.1.1 (transitive third-party, crates.io)
    * features: default, std
  A petgraph 0.6.0 (transitive third-party, crates.io) (other versions: 0.5.1)
    * features: default, graphmap, matrix_graph, stable_graph
  A rust-ini 0.13.0 (transitive third-party, crates.io)
    * features: [none]
  A serde 0.8.23 (transitive third-party, crates.io) (other versions: 1.0.130)
    * features: default, std
  A serde-hjson 0.9.1 (transitive third-party, crates.io)
    * features: [none]
  A serde-value 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A tint 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M arrayvec 0.5.2 (transitive third-party, crates.io)
    * added features: array-sizes-33-128
    * (unchanged features: default, std)
```

**Review by tzakian — DISMISSED** [review]
This looks great! Happy to land it :) 

/land

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A ptree 0.4.0 (direct third-party, crates.io)
    * features: ansi, ansi_term, atty, conf, config, default, directories, petgraph, serde-value, tint, value
  A config 0.11.0 (transitive third-party, crates.io)
    * features: default, hjson, ini, json, rust-ini, serde-hjson, serde_json, toml, yaml, yaml-rust
  A directories 4.0.1 (transitive third-party, crates.io)
    * features: [none]
  A dirs-sys 0.3.6 (transitive third-party, crates.io)
    * features: [none]
  A fixedbitset 0.4.0 (transitive third-party, crates.io) (other versions: 0.2.0)
    * features: [none]
  A lazy_static 0.2.11 (transitive third-party, crates.io) (other versions: 1.4.0)
    * features: [none]
  A lexical-core 0.7.6 (transitive third-party, crates.io)
    * features: arrayvec, correct, default, ryu, static_assertions, std, table
  A nom 5.1.2 (transitive third-party, crates.io)
    * features: alloc, default, lexical, lexical-core, std
  A num-traits 0.1.43 (transitive third-party, crates.io) (other versions: 0.2.14)
    * features: [none]
  A ordered-float 2.1.1 (transitive third-party, crates.io)
    * features: default, std
  A petgraph 0.6.0 (transitive third-party, crates.io) (other versions: 0.5.1)
    * features: default, graphmap, matrix_graph, stable_graph
  A rust-ini 0.13.0 (transitive third-party, crates.io)
    * features: [none]
  A serde 0.8.23 (transitive third-party, crates.io) (other versions: 1.0.130)
    * features: default, std
  A serde-hjson 0.9.1 (transitive third-party, crates.io)
    * features: [none]
  A serde-value 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A tint 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M arrayvec 0.5.2 (transitive third-party, crates.io)
    * added features: array-sizes-33-128
    * (unchanged features: default, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A ptree 0.4.0 (direct third-party, crates.io)
    * features: ansi, ansi_term, atty, conf, config, default, directories, petgraph, serde-value, tint, value
  A config 0.11.0 (transitive third-party, crates.io)
    * features: default, hjson, ini, json, rust-ini, serde-hjson, serde_json, toml, yaml, yaml-rust
  A directories 4.0.1 (transitive third-party, crates.io)
    * features: [none]
  A dirs-sys 0.3.6 (transitive third-party, crates.io)
    * features: [none]
  A fixedbitset 0.4.0 (transitive third-party, crates.io) (other versions: 0.2.0)
    * features: [none]
  A lazy_static 0.2.11 (transitive third-party, crates.io) (other versions: 1.4.0)
    * features: [none]
  A lexical-core 0.7.6 (transitive third-party, crates.io)
    * features: arrayvec, correct, default, ryu, static_assertions, std, table
  A nom 5.1.2 (transitive third-party, crates.io)
    * features: alloc, default, lexical, lexical-core, std
  A num-traits 0.1.43 (transitive third-party, crates.io)
    * features: [none]
  A ordered-float 2.1.1 (transitive third-party, crates.io)
    * features: default, std
  A petgraph 0.6.0 (transitive third-party, crates.io) (other versions: 0.5.1)
    * features: default, graphmap, matrix_graph, stable_graph
  A rust-ini 0.13.0 (transitive third-party, crates.io)
    * features: [none]
  A serde 0.8.23 (transitive third-party, crates.io) (other versions: 1.0.130)
    * features: default, std
  A serde-hjson 0.9.1 (transitive third-party, crates.io)
    * features: [none]
  A serde-value 0.7.0 (transitive third-party, crates.io)
    * features: [none]
  A tint 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M arrayvec 0.5.2 (transitive third-party, crates.io)
    * added features: array-sizes-33-128
    * (unchanged features: default, std)
  M num-traits 0.2.14 (transitive third-party, crates.io)
    * added features: default
    * (unchanged features: i128, std)
```

**Review by tzakian — DISMISSED** [review]
/land

**Pull request merged**
