### PR TITLE
[move-prover] simplify the transformation pipeline runner with hooks

### PR DESCRIPTION
**Pull request by mengxu-fb**
`FunctionTargetPipeline::run` is overly complicated now. This commit
splits it into two parts:
- `sort_targets_in_topological_order`
- `run_with_hook`

In addition, to facilitate testing and bytecode and CFG dumping,
we also provide two instantiations of the `run_with_hook` function
- `run`: which runs the pipeline with no-op hooks
- `run_with_dump`: which runs the pipeline with bytecode dumping

EDIT: added a second commit that consolidates the transformation
pipeline in a single file (currently the pipeline is constructed in two
files, which is less optimal).

## Motivation

I need to hook the generated bytecode as well, beyond the purpose of dumping...

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

1) CI
2) `mvp --dump-bytecode --dump-cfg <some-file>.move` works as expected

### CODE REVIEW

**Review by wrwg — APPROVED** [review]
Nice. The pipeline file was a left-over from last internship and we were planning to integrate it back into lib, but moving everything there is also a good solution.

**Comment by bmwill** [comment]
/cancel I'm restarting bors I'll re-queue when its back up again

**Pull request merged**
