### PR TITLE
add RefundMetadata struct for generating types

### PR DESCRIPTION
**Pull request by xli**
## Motivation

New RefundMetadata struct is proposed for refund transaction to store original transaction version.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

YES

## Test Plan

Unit test

### CODE REVIEW

**Review by n4ss — APPROVED** [review]
Looks great! Let's take time to discuss the coin purchase/selling refund reasons as well :) (non-blocking and can obviously happen later)

**Review by davidiw — APPROVED** [review]
gogogo

**Review by matbd — APPROVED** [review]

**Comment by noursale** [comment]
Nic

**Pull request merged**
