### PR TITLE
[cli] Create a command to submit writeset reading from path for cli.

### PR DESCRIPTION
**Pull request by runtian-zhou**
## Motivation

Create a command in cli to submit a writeset reading from a path.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
Executed following command in cli:

`dev ws <GIT_ROOT>/language/diem-tools/writeset-transaction-generator/release/release-1.2.0-rc0.blob`

### CODE REVIEW

**Comment by sherry-x** [comment]
How do you provide the Root key for submitting this writeSet? also shouldn't we submit it to a json-rpc endpoint or something?

**Comment by runtian-zhou** [comment]
> How do you provide the Root key for submitting this writeSet? also shouldn't we submit it to a json-rpc endpoint or something?

That is correct! All those info we would need to provide to the cli launcher.

**Review by tzakian — APPROVED** [review]
LGTM

**Pull request merged**
