### PR TITLE
[move-package] Add unit test support and doc templates

### PR DESCRIPTION
**Pull request by tzakian**
This PR adds unit testing support and doc template support to the Move Package manager, along with adding unit test support to the Move CLI package command. 

This PR also makes the Move Stdlib and Nursery Move packages, although they are still compiled for use by the rest of the system in a non-package way currently. There will be subsequent PRs needed to convert other parts of the system in order to move these over to being pure Move packages.

### CODE REVIEW

**Review by tnowacki — DISMISSED** [review]
cool!

**Review by tnowacki — DISMISSED** [review]

**Review by tnowacki — APPROVED** [review]

**Review by tnowacki — DISMISSED** [review]

**Review by tnowacki — DISMISSED** [review]

**Comment by tzakian** [comment]
Third time's the charm? 🙏 🙏 🙏

/land

**Pull request closed without merging**
