### PR TITLE
[move-prover] Update Prover to reject the programs with compile warnings

### PR DESCRIPTION
**Pull request by junkil-park**
If the input program has compile warnings, Prover's model building step does not finish normally. So, Prover should stop the proving process, and produces the proper error message "exiting with model building errors".

This PR updates Prover to treat the compile warnings same as it treats the compile errors.

Resolves https://github.com/diem/diem/issues/8970.

## Motivation

To fix the bug regarding the input programs with the compile warnings

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

cargo test

### CODE REVIEW

**Comment by mengxu-fb** [comment]
Interesting... it seems that when there are compiler warnings, the generated `output.bpl` does not have any code related to the move program and I am wondering why that happens...

**Comment by wrwg** [comment]
> Interesting... it seems that when there are compiler warnings, the generated `output.bpl` does not have any code related to the move program and I am wondering why that happens...

Yes we should definitely be able to run the prover when the compiler has warnings only, so bailing out on warnings is not the right solution, at least in the medium run.

**Comment by mengxu-fb** [comment]
The option 2 from @junkil-park's proposal (see issue #8970) is implemented in #8972. That version allows the prover to continue on programs with compiler warnings only but also allows the warnings to be printed after the model building phase, together with other model building issues and or prover errors.

**Comment by junkil-park** [comment]
Closing this. Handing over the baton to the Meng's PR (#8972).

**Pull request closed without merging**
