### PR TITLE
docs(fix): remove duplicate 'when'

### PR DESCRIPTION
**Pull request by Abdelkrim**
## Motivation

there is a basic duplication of words in the documentation

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

NO, I haven't read it. the change is minor.

### CODE REVIEW

**Comment by davidiw** [comment]
when will you sign the cla ;)

**Review by davidiw — APPROVED** [review]
Please sign CLA, then I will gladly land this.

**Comment by Abdelkrim** [comment]
Dear @davidiw, the cla is signed but I don't know when the label `cla-unsigned` will change.

**Comment by jjwill** [comment]
@Abdelkrim can you sign the individual CLA located here - https://www.diem.com/en-us/cla-sign-individual/#agreement

Once that is complete you will get a thanks you message. Then just come back to this PR and click the Recheck CLA link above. That should allow this PR to be merged.

**Comment by Abdelkrim** [comment]
@davidiw 

1. I signed again the CLA
2. I granted access to Diem to my github account

3. I have contacted docusign, I suspect that the usage of a '+' character into my email jeopardize the process

Be patient :-)

Kind regards

**Comment by davidiw** [comment]
let me know if you have re-enabled that setting ... I may very well just make another PR to address this shortly :P

**Comment by Abdelkrim** [comment]
I have created another 'pull request' : https://github.com/diem/diem/pull/7184

**Pull request closed without merging**
