### PR TITLE
[move-prover] update boogie version to 2.8.33

### PR DESCRIPTION
**Pull request by Ying1123**
## Motivation

Update the boogie version to 2.8.33 in dev_setup.sh

## Test Plan

I didn't change the source code.

## Related PRs

None.

### CODE REVIEW

**Comment by wrwg** [comment]
Looks great. I forgot to mention this, but could you also please change the Boogie version here? https://github.com/diem/diem/blob/main/language/move-prover/boogie-backend/src/options.rs#L19

**Comment by Ying1123** [comment]
> Looks great. I forgot to mention this, but could you also please change the Boogie version here? https://github.com/diem/diem/blob/main/language/move-prover/boogie-backend/src/options.rs#L19

Have addressed.

**Review by DavidLDill — APPROVED** [review]

**Pull request closed without merging**
